### ISSUE TITLE
Allow setting ItemStack Quantity greater than the default maxStackSize

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeAPI#1074]
The maxStackSize of an ItemStack is currently fixed to the default maxStackSize of the ItemType.

So it is not possible to stack items like swords, eggs etc. up to 64 in inventories.
Also when using an itemstack outside of inventories stacksize should not be limited to 64.
For example to represent the items in a sign-shop.

**Comment by CrystalMageX** [comment]
It is a bad idea to set the `maxStackSize` of an `ItemStack` greater than what the actual item supports. 

In-Game:
Stacking doors, signs, and eggs up to 64 would cause no problems, but it would lead to undefined behavior when using tools.

- What happens when you *attack, fish, or mine* with an oversized stack?
- Will *all* of the tools take damage?
- How do I *split* a damaged stack?
- How do I put to stacks *together*?
- What about mods that add tools that have two classes for the same item, and *change the item type* from "Tool (Ready)" to "Tool (Used)" upon use?
- Does the *entire stack* change?

We don't know about how things should behave. Mojang doesn't, so they make the Notch client refuse to stack the items together. Mods might simply start causing a stack of 64 items that it expected to only be a single item, to give you back only 1 item, when you do an action, as opposed to the 1:1 conversion it intended, destroying your other 63 items. We can only specify behavior that is agreed upon across Minecraft, and in this case, the behavior is limiting the max size of the stack to what the item wants.

Sign-shops:
Item stacks represent something you put in a single inventory slot, neither the inventory itself, or any of its slots. If you want to make a sign shop plugin, use `Set<ItemType, Integer>`.

**Comment by Faithcaio** [comment]
ItemType is fine for just basic items. But it won't hold data like enchantments etc.
So i'd need a ```Map<ItemStack, Integer>``` which is what i didn't want

**Comment by chrismack** [comment]
Doesn't vanilla minecraft already handle oversized item stacks? For example:
/replaceitem entity ChrisMack slot.hotbar.7 minecraft:iron_sword 60 0 {ench:[{id:16,lvl:6}]}

**Comment by gabizou** [comment]
I'm personally against having support for oversized `ItemStack`s on the basis of having no knowledge "what's going to happen when..." situations, especially with mods. And considering the past uses on Bukkit have been to mark the items as being "unlimited", it's a dirty hack to rely on, let alone something the API doesn't do well to maintain between versions. Having that said, there are other better ways to deal with making an `ItemStack` "unlimited', especially with the power that plugins have with events.

**Comment by Faithcaio** [comment]
I really like #1092 for the item-shop and items over 64 issue .

Still i think it should be possible to set the quantity up to 64 on every ItemStack since as @chrismack said you can obtain such stacks in vanilla.
Maybe add a ```setQuantity(int quantity, boolean unsafe)``` so you cannot accidentally set more than allowed.

Users on my server (still on Spigot) quite like that "feature" to stack minecarts, boats, potions and other items together.

Also another idea: Would it be possible to change the max-stack-size for an ItemType on the whole server? So e.g. limiting SpongeBlocks to 42.

**Comment by Faithcaio** [comment]
Another use-case:
```
player.getInventory().offer(ItemStack.of(ItemTypes.STONE, 200))
```
Without allowing oversized Stacks I would have to manually split up the amount into max size itemstacks and offer them one after the other.
The Inventory should be able to do that itself.

**Comment by ryantheleach** [comment]
If item stacks won't support > maxStackSize amounts, then https://github.com/SpongePowered/SpongeAPI/blob/74a6311b865e2ecc35e6e7851ccbc681e0119f97/src/main/java/org/spongepowered/api/item/inventory/Inventory.java#L142 should be turned into returning a collection of itemstacks, or mention that int can not exceed maxStackSize.

**Comment by modwizcode** [comment]
I think the problem I see in @Faithcaio's case above represents a need to be able to offer a set amount of items at once. Which implies maybe a secondary `offer(ItemStackSnapshot, int quantity)` type method to allow offering a set quantity of the data. This would allow the API to instantiate the needed quantities of ItemStacks based on the max sizes known to the implementation.
