### ISSUE TITLE
Plugin identification

### ISSUE THREAD

**Issue by windy1** [SpongePowered/SpongeAPI#1083]
Stemmed from https://github.com/SpongePowered/SpongeAPI/pull/1081/files#r53494740

This issue is to discuss how plugins should be identified. Currently, plugins are assigned an "id" string defined by the plugin developer. The issue I personally have with this is the prospect of duplicate IDs. I would like to propose that plugins be identified by their containing class.

For example, dependencies could be defined like

```java
@Plugin(name = "MyPlugin", dependencies = @Dependency(SomePlugin.class))
```

Some helper methods that could be added to PluginManager with this new approach:

```java
pm.getPlugins("name");
pm.getPlugin(SomePlugin.class);
pm.getDependencies(myPlugin);
```

**Comment by kenzierocks** [comment]
This won't work with soft dependencies, as the class won't be present in
some cases.

**Comment by ST-DDT** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/1081/files#r53496690

> ````java
@Plugin(group = "net.minecrell", id = "testplugin", dependencies = @Dependency(group = "com.sk89q", id = "worldedit"))
````

@Minecrell I really like the maven idea with group and id. This would hopefully encourage more people to use build tools.

@windy1 Defining class dependencies is always a bit hacky IMO. Because some plugins provide extra API bundles, that are much more lightweight, because they don't use/contain any/much impl, forcing a user to specifiy an extra plugin class will just block this way. And I hope you agree with me that writing against an API is usually better than using the impl directly.

**Comment by windy1** [comment]
@kenzierocks Sure it could, just catch the ClassNotFoundException.

**Comment by windy1** [comment]
@ST-DDT Not sure what makes it hacky but if a plugin dependency has an API all it has to do is make a superclass/interface for the implementing plugin and then the dependents can just use that.

**Comment by kenzierocks** [comment]
That won't work (maybe it will? Not well though) if you have multiple soft
dependencies.

**Comment by windy1** [comment]
@kenzierocks Not sure why you don't think it would work with multiple soft dependencies. 1, 2, 600, it doesn't matter.

**Comment by ST-DDT** [comment]
@windy1 You cannot catch a `ClassNotFoundException` in an annotation (AFAIK).

**Comment by windy1** [comment]
@ST-DDT You would catch it when loading the plugin class.

**Comment by Minecrell** [comment]
@windy1 If there is an exception during the class load the class will fail to load, you can't say like "Oh, annotations failed to load? Whatever, load the class anyway!". I don't think Java actually throws exceptions for annotations until they're accessed via reflection so this would only cause real issues as soon as Plugins are trying to use some kind of annotation on plugin classes (like Updatifier: https://github.com/FlibioStudio/Updatifier)

**Comment by windy1** [comment]
@Minecrell You mean you can't do something like? (psuedo-code)

```java
try {
    load("com.example.plugin.MyPlugin");
} catch (ClassNotFoundException e) {
    load(e.getMessage());
}
```

**Comment by Minecrell** [comment]
@windy1 ... Then you don't have the plugin class, which should still load for soft dependencies (**optional dependencies**) :P

**Comment by ST-DDT** [comment]
@windy1 

Eclipse won't let my compile this, due to unreachable code:

````java
try {
    get(ClassThatIsAbsentAtRuntime.class);
} catch (ClassNotFoundException e) {
    System.out.println("Caught");
    e.printStackTrace();
}
````

This works:

````java
try {
    get(ClassThatIsAbsentAtRuntime.class);
} catch (NoClassDefFoundError e) {
    System.out.println("Caught");
    e.printStackTrace();
}
````

**Comment by windy1** [comment]
@ST-DDT tomato, tomato :p 

@Minecrell Soft dependencies could be declared with the class name instead of the actual object.

**Comment by Minecrell** [comment]
@windy1 Well that makes the whole thing less nice, then we might as well go the group way, which is usually a bit shorter but still unique enough :P

**Comment by ST-DDT** [comment]
Is there a way to merge (required) plugin dependencies and (required) service dependencies?

Example: I need an economy plugin/service, but I don't care which one.

**Comment by simon816** [comment]
One thing I really don't want is referencing the class name directly. That means that your plugin a) Has to know the internal structure of the dependency and b) Refactors will make the plugin incompatible, even if the plugin exposes an API that remains the same

**Comment by windy1** [comment]
@Minecrell I think I still personally prefer class definitions as it's less work for the dependency. Maybe it's a little longer for soft decencies on the dependent's side, but it's certainly shorter for hard dependencies.

**Comment by kenzierocks** [comment]
@simon816 refactors would break plugins that explicitly reference the class anyways, so that point is really that big. I do hope that we can depend on something that isn't an `@Plugin` if we choose class definitions because then plugins can expose API that can be used and versioned, and people can rely on that instead of the underlying plugin which may suffer from refactors.

The reason for that is that this is what the id system currently allows. For example, you compile against `worldedit-core`, but your plugin states that it needs `worldedit` at runtime. If WorldEdit refactors the `worldedit-sponge` part, your plugin is not affected as it only relies on `-core`. However, if we could only depend on the `@Plugin` then you couldn't do that.

**Comment by ST-DDT** [comment]
Maybe we can split things into smaller pieces:

````java
@Plugin(group,id...)
@Dependency(SomePluginClass.class)
@Dependency(group="foo", id="bar")
@Dependency(EconomyService.class)
@SoftDependency(group="fool", id="beer")
@SoftDependency("org.spongepowered.api.service.PermissionService")
@Provides(ShopService.class)
@Provides(MyPluginAPI.class)
public class MyPlugin implements MyPluginAPI {

````
I just tested it annotations are only evaluated if you access them directly.

Well I'm not quite sure yet, but maybe using a `Class` for required dependencies and a classname for soft dependencies should be the recommended way to go.

Workflow:
* Load Plugin classes
* Check `@Provides` annotation
* Check `@Dependency`

So you could load your class with a fixed class in the dependency in the annotation, and then when we evaluate the dependencies we will get the `NoClassDefFoundError` error and can show the user the associated message. It does not really matter that the plugin loads to fail, because if the dependency is missing then it is lost anyway. However this might make things complicated for plugin repositories to detect (Ore?). How do we specify an min version?

Soft dependencies must be declared using a classname, because the actual class might be absent.
(SoftDependencies are only used for update checkers and maybe plugin repositories)
Maybe we can extend the event `@Listener` to respect the `@SoftDependency` as well so you use listeners that will only exceute if the given soft dependency is present. This would prevent code that must catch the `NoClassDefFoundError` explicitly. In that event handler the plugin can initialize the compatibility module or do some stuff.

````java
@Listener
@SoftDependency(".....EconomyService") // Maybe even @Dependency(EconomyService.class)
public void initEconomy(ServerAboutToStartEvent event) {
    myPlugin.arenaFeatures.add(new EconomyFeature(Sponge.getService(EconomyService.class)));
}
````



`@Provides` must specify a class (Plugin API or service class) that this plugin provides.

**Comment by Minecrell** [comment]
I personally think if we decide to go with an additional component to make sure plugins are unique the Maven-like group is the better option because it would also integrate well if Ore adds a Maven repository for plugins, at that point you'd need a group and an ID anyway, no matter which option we choose.

**Comment by progwml6** [comment]
My main problem with the maven group is that sometimes people d

**Comment by Aaron1011** [comment]
I'm not sure that this is a good idea. For one thing, I don't foresee duplicate ids being much of a problem. For anything other than a private plugin, developers should do a basic check to ensure that their plugin name is unique. With Ore, this will be even easier, and can in fact be done automatically when a jar is uploaded.

Also, under what circumstances would two plugins have the same name, but not the same id? In practice, I feel that this would cause just as many problems as duplicate ids would, without causing an actual error at load time. Explicitly allowing for duplicate names, as in your example, seems to jonly create a headache for dealing with plugins.

**Comment by ST-DDT** [comment]
The most common case of plugin name/id clashes are arena plugins such as (Bow-)Spleef, SurvivalGames, Paintball.... This is usually the case if a common name is used as name/id.

**Comment by simon816** [comment]
Just thought I'd link this here because it's been discussed somewhat before:
https://github.com/SpongePowered/SpongeAPI/commit/49832340555f3270a5a46b283c312296eda55eb3#commitcomment-7775892

**Comment by Aaron1011** [comment]
The way I see it, there are a few different scenarios under which an id conflict can occur:

1. Your project has exactly the same name as another project.

  It should go without saying that **this is already an issue**. Take, for example, @hsyyid's plugin `EssentialCmds`. If I decide to create my own project, which I *also* call `EssentialCmds`, then a conflicting id is the *last* thing I need to worry about. Assuming my userbase consists of more than just myself, referring to the projects is going to be a huge issue.

2. Your project has a different yet similar name, but the same id.

  Continuing with the above example, let's say I create a plugin called `EssentialCommands` (as opposed to the already existing `EssentialCmds`). Ignoring the practical concerns of having two plugins with names that are so similar, the soluton is simple - simply change your id to the actual name of your project.

**Comment by Deamon5550** [comment]
I think the largest benefit of removing the id is we no longer have this wishy washy behaviour around an id conflict. Currently we have to not load one (or both) of the conflicting plugins if we have a conflict. If you have two different plugins and a server admin puts them both in their mods folder, their intention is to use both of them. If they conflict on the id then they simply can't. Now if instead we identify plugins by class (or by group-id) then there is no conflict between these two different plugins. And then the only case of a conflict is a plugin being added twice, which is the only case in which its safe to not load one of them.

**Comment by progwml6** [comment]
99 times out of 100 when there is a conflict on the ID it will be because someone forgets to delete the old version of a plugin when updating.

**Comment by Deamon5550** [comment]
@progwml6 And in that case using a group-id or class **will still conflict** and resolving it by not loading one or both is the correct action.

The important usecase is when two **different** plugins conflict because in that case not loading one or both is certainly the wrong action.

**Comment by progwml6** [comment]
I can't see a single reason that getting rid of id's would provide either the team or users a better experience. I only see increased difficulty when integrating with forge mods, and Mojang's code. 

Systems that the vanilla game code has thought of expanding of rely on these named IDs which are persistant. Examples include blocks,items,images,localization files and other resource files.

Regarding the suggestions to use classes instead: We purposely early on avoided the usage of classes for compatibility and other such usage. I don't unfortunately have those IRC logs handy.
I personally feel that for compatibilty that I should be able to develop against the ID that is used for persistance, and an API jar when working with someone else's code and not need to understand how a plugin itself is coded or lock a developer into a specific class name/package for a main class.

 As interaction between plugins matures, and we enhance api interaction I feel it would be a step back to head towards using instanceOf and classforname checks, for interaction verse simple string lookup checks. which can easily be expanded upon long term with pseudoplugins for things like API's etc.
Something like the pseudocode below would be far faster than the reflective based operations necessary when classes/classnames are being used.
if( isLoaded("pluginID")) {
//do compatibility here
}

using non persistant UUID's or other generated non persistant identifiers in place of a constant UUID will likely cause compatibility issues with forge mods which WILL use your plugin ID for persistance purposes.

Plugin ID's should in my opinion be lower case only and compatible with mojang's ResourceLocation class, and other restrictions imposed by that system in order to make them more resilient for future uses and better integration with.

Having ID's around would be beneficial if we ever decide to allow creating blocks/items in the future, as vanilla's code requires an ID for blocks/items.

Plugin names are currently mainly for display and can contain characters that wouldn't be tolerated in things like mojang's resource system or command processing. This system is very strict as to what characters it allows. Spaces in systems like commands of these will break processing code which regularly splits on spaces.

regarding suggestions for @provides type of things that should probably be hooked into a separate annotation that is tied to packages/classes providing api's and associated hooks necessary to strip out definitions at runtime interfaces/methods that would cause crashes working from optional dependencies(similar to FML/Forge @API/@Optional annotations)

if changes are considered I recommend that those who propose them consider the following:
1: how would this type of dependency with a group be mixed with forge mod dependencies from a plugin's dependency system or a mod's dependency system.
2: What the behavior should be when someone forks a plugin that other people have dependencies on to make a simple fix changing maven groups for shipping would likely be required but would not necessarily break compatibility.

another thing that was mentioned was changing plugin ID's:
Changing pluginID's(or another identifier such as group/id) is something that will likely need an event to allow the plugin to specify that an ID has changed to allow world persistance storage to convert from old to new.

regarding some of the common minigames: on the docs site we should probably regardless recommend that jimbob's spleef use an ID like "jimbobspleef" and names like "Jimbob's Spleef"  instead of just "spleef" . This will result in less headaches with commands overlapping(those use id's currently)

**Comment by kashike** [comment]
I don't like the idea of dependencies using classes/class names - just seems stupid in general.
In my opinion, if two plugin IDs conflict the authors should be shot - the ID is supposed to be unique, name doesn't have to be.

**Comment by windy1** [comment]
Closing this as the general consensus seems to be to stick with the current system and/or add group ids. I also agree that this is probably the better solution. This issue was simply to discuss the possibility of class identified plugins.
