### ISSUE TITLE
Implement standardization option for resources within plugin.

### ISSUE THREAD

**Issue by windy1** [SpongePowered/SpongeAPI#1119]
It would be very helpful, especially within the, in progress, localization system if we could uniformly retrieve resources from plugins. I would like to propose a system where plugins may specify a "resource" directory where they store their assets in the plugin meta file. This directory could default to `assets/<package>` as this seems to be the current standard within the Forge community.

A possible implementation could look something like:

```java
Optional<InputStream> resource = Sponge.getResourceManager().getResource(Object plugin, String name);
// and / or maybe
Optional<InputStream> resource = pluginContainer.getResource(String name);
```

We could create a `Resource` object to wrap the `InputStream` too if that is desired.

**Comment by Mumfrey** [comment]
This is a great idea.

> as this seems to be the current standard within the Forge communit

Just to add some clarification to this, the standard actually comes from *Minecraft* rather than forge. Resource packs have an internal structure of `assets/<domain>/path/to/resource.ext` and the only standard that mods impose atop this is that the `domain` is the `mod id`.

This translates to a `ResourceLocation` which is specified in text form as `domain:path/to/resource.ext` or as two separate strings `domain` and `path`. If `domain` is omitted then it is inflected to `minecraft`.

Just some corollary info.

**Comment by Zidane** [comment]
Love this change and seriously need this for Almura.

**Comment by Zidane** [comment]
@windy1 's AssetManager in API 4 covers this.
