### ISSUE TITLE
[Discussion] DataTransactionResult and CompletableFuture

### ISSUE THREAD

**Issue by windy1** [SpongePowered/SpongeAPI#1139]
So, there might be instances, and are instances, where the result of a data transaction ought not to be available immediately. One example of this is with skulls. We should be updating the GameProfile of a skull asynchronously whenever it is set or removed but that is not currently the case. (My latest commit regarding skulls makes updating async for updating from within the base game). I would like to propose that we wrap DataTransactionResult in a CompletableFuture in almost, if not all, methods that return a DataTransactionResult or at any other data processor mutators. This will allow for asynchronous data manipulation.

This would also be a great boon to possible data processors that perform I/O operations.

**Comment by modwizcode** [comment]
This seems like a reasonable proposal. However I don't really think it should be the default behavior, plenty of data (in fact most of the data) should be non-asynchronous. It's my view that this should be an additional variety of data with these properties. That might be simply too much work to maintain two distinct systems like that, but using CompletableFuture for an operation does complicate the plugin code, and there's no reason to suggest operations are asynchronous when they are not.

**Comment by windy1** [comment]
The great thing about `CompletableFuture` is that it doesn't actually have to be in the future. Non-asynchronous data transactions would just create a new future and call `complete(V)` on it right away.

**Comment by modwizcode** [comment]
Good point, given that there should be no reason we don't switch to `CompletableFuture`

**Comment by gabizou** [comment]
While it's interesting to note, I'm curious what the implications could mean, since this would allow for theoretical async data access where the completable future just waits to re-sync back to the main thread. Having that said, for the case of skulls, it would be certainly interesting, but at the same time, the asynchronous aspect is probably not going to be well understood, and in the event an async task completes but for example, a `TileEntity` is no longer present, the task should fail.

The implications to handle processing in such ways would be interesting. I'll have to give this some thought as the implementation plumbing is very reliant on being on the main thread.

**Comment by windy1** [comment]
@gabizou Could you elaborate on "theoretical async data access"? The only thing that would be running on a different thread here should be the processors themselves and for mutators only. Those mutators would returns a future of a result and a plugin dev could either `get()` it and block the main thread until completed or `handle` it which would run a `BiConsumer` with the result and an exception if failed. It might not be a bad idea to implement our own `Future` as well to make these definitions a bit more strict as `CompleteableFuture` allows you to pretty much do whatever you want with the result and thrown exception, disregarding the actual intent of the future.
