### ISSUE TITLE
Tile -> Block

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#1147]
In Sponge, we represent vanilla block entities as "TileEntity"/"tile", while they are known both internally (assumed from "BlockEntity" being referenced in error/debug messages) and to the community as "BlockEntity"/"block entity". The only existing references to "tile" are old/legacy code/options (gamerule `doTileDrops` for example).
The wiki states:
> A block entity (previously named tile entity) is extra data associated with a block, beyond the block ID and 4 extra bits of data that every block has.

In my opinion, we should rename the associated API elements to be "BlockEntity"-based instead of "TileEntity". I'm willing to submit PRs to *bleeding*.

**Comment by liach** [comment]
Yet those people in forge and mcp does not agree with this change, but Sponge is to build an api for different (include custom) minecraft clients and servers, and following mojang's rule would be great.

**Comment by simon816** [comment]
I don't think something like this is necessary as there have been no complains about it being called a tileentity and I'm sure a lot of people are used to that name anyway.
There's no reason to stick that tightly to Mojang's naming just because we learn that's what they call it, It could just be known as a TileEntity when it comes to SpongeAPI

**Comment by kashike** [comment]
Why would be call a **block** entity a **tile** entity? Tile isn't used anywhere else in the API, block is - being consistent in calling things block is preferred to mixing terms.

**Comment by ryantheleach** [comment]
I don't like BlockEntitie People are used to TileEntities, and it's too easy to confuse it with a "Falling"BlockEntity

**Comment by Meegooo** [comment]
It makes more sense to change Tile to Block. But TileEntity is more known than BlockEntity (I've never seen anyone using BlockEntity before). Mod developers have been calling them TileEntity since god knows when. If you ask me what is BlockEntity is, I would stay confused for couple seconds.

Plus it would be confusing if NMS had TileEntity and Sponge called the same thing BlockEntity. No one uses Mojang names (because we don't know them), everyone uses mcp names.

**Comment by kashike** [comment]
And it makes sense to have two different terms here? A `BlockEntity` represents extra data/functionality on a `Block`. The SpongeAPI doesn't use the term anywhere else, it uses `Block`.
When using vanilla commands that modify the NBT of a `BlockEntity`, people use `BlockEntityTag`. `Tile` is what `Block` used to be called in Minecraft, but not anymore.

**Comment by modwizcode** [comment]
I think that either way, we need to be consistent, however I think that moving away from MCP names, just to be arguably more correct, is not worth making the API more confusing to read for the people we want to use it. If we want to correct the naming decision, I would say best case is going to MCP and convincing them, otherwise it's just a hassle for Sponge developers and plugin developers alike.

**Comment by Mumfrey** [comment]
If achieving parity with internal nomenclature is the goal then changing `Tile` to `Block` would just be the beginning. Keep going and change `Chunk` to `ChunkColumn`. Too controversial for you?

Much as I agree that for consistency sake it should probably be `BlockEntity`, you can't let one design goal trump another without weighing the benefits/drawbacks of each.

*What does `BlockEntity` have?* Consistency.

*What does `TileEntity` have?* Familiarity (and arguably, if you look at other environments, also consistency, eg. consistency with MCP).

Idealism and purity of design are noble goals, but when it gets to the point that navel-gazing leads you to abandon common sense, and ultimately make things harder for people to use; it's at that point that you need to take a step back and think about whether your idealism is causing you to lose sight of what's actually relevant.

Stand firm, and shout from the rooftops: *"they may take our Tiles, but they can never take our TileEntities"*

**Comment by modwizcode** [comment]
@Mumfrey <3

**Comment by Mumfrey** [comment]
Why?
