### ISSUE TITLE
Add a HumanReadable Name to Subjects

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeAPI#1181]
When accessing the PermissionService API to add a permission or option to a group you currently have to know the Identifier of the group.
The problem is the Identifier is "Not guaranteed to be human-readable."

So if another plugin takes user-input to add smth. to a group it wont work properly (typing in a uuid is not realistic) unless the implementing Service actually uses humanreadable names for its group-ids too.

So I'd like to propose adding:

```getName()``` to ```Subject``` (or ```Contextual```?)
and
```getByName(String)``` to ```SubjectCollection```

**Comment by zml2008** [comment]
the permissions plugin is not usually the one that knows how to calculate a human-readable name            that's usually part of a CommandSource. PEX has some subject type definition type-thing that allows plugins to provide more information about their subject types and to establish links between Subjects and CommandSources, but that API is super rough and would need to be polished for anything beyond internal use. Essentially this issue is asking asking for the equivalent of a player's getDisplayName, but it's not the permissions plugin's job to know what that is.
