### ISSUE TITLE
Expose child commands to help system.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1190]
Currently there is no way to see nested tree's of child commands in the help system.

Child commands need to be more exposed in the API, and more explicit, otherwise there is very little point in using child commands over your own command parsing apart from utility.

**Comment by dualspiral** [comment]
In API-8, we're not going to handle the `/help` command, and due to the way commands are structured in API-8, you may not necessarily be able to get child commands in the first place. 

If you can get the `Command.Parameterized` [then you can get subcommands](https://github.com/SpongePowered/SpongeAPI/blob/api-8/src/main/java/org/spongepowered/api/command/Command.java#L259), but this is by no means universal and I don't think I provide a way to get the `Command.Parameterized` out in the first place. If someone makes a compelling argument to do so then I can expose it on the specialist registrar, but otherwise, this isn't going to happen.
