### ISSUE TITLE
Additional "Database API" that utilises JPA / Hibernate

### ISSUE THREAD

**Issue by octo-byte** [SpongePowered/SpongeAPI#1211]
As a plugin developer, I want to be able to use the javax.persistence API in order to manage persistent data objects. This, preferably, would be Hibernate or a lightweight alternative if a suitable one can be found (not ebeanserver).

I honestly think something like this has a lot of potential, especially surrounding metadata that persists over server restarts. Bukkit notoriously lacked a solid framework for JPA (ebean was an unmaintained mess). Hibernate could make plugins much more maintainable, because there would literally almost no need to write SQL queries again for a lot of common functions.

I am willing to put time into working on this if there can be a discussion on how and where it should go. Bear in mind however, I do have a full time Java Dev job that does take a lot of energy out of me - so some support would be appreciated.

**Comment by ryantheleach** [comment]
I wonder how well this could work with data.

**Comment by octo-byte** [comment]
Still wanting input from some of the core devs on how you think this might work. In the meantime, I'll draft up something on a fork

**Comment by octo-byte** [comment]
Basic implementation started on my fork

https://github.com/octo-byte/SpongeAPI/commits/persistence
https://github.com/octo-byte/SpongeCommon/commits/persistence

**Comment by octo-byte** [comment]
How I'm expecting this to work, is that an EntityManager JPA instance is defined for each plugin as and when it's needed. The plugin author should be given the flexibility to use another backing JDBC connection if they want (eg. the default being H2, but the plugin dev wants MySQL). The PersistenceConfiguration should allow for this.

**Comment by zml2008** [comment]
The way we decided to go for Sponge was to leave any ORM support up to plugin developers since there wasn't any sort of agreement among anybody over what to use, but provide a common connection pool and JDBC drivers in Sponge through the SqlService. I don't think any of the reasoning behind that decision has changed, so I don't think this is suitable for Sponge itself. An appropriate path would probably be writing a plugin that provides this service and exposing a stable API for other plugins to adopt.

**Comment by octo-byte** [comment]
For future reference, this is now being implemented as a plugin for those wanting ORM. 
https://github.com/octo-byte/sponge-hibernate
