### ISSUE TITLE
No way to access spawn egg of creature

### ISSUE THREAD

**Issue by Meronat** [SpongePowered/SpongeAPI#1321]
I was attempting to go from a mob(animal or monster) and checking to see if they have a spawn egg equivalent and if they do get that actual item, but I could not figure out a way. @Aaron1011 told me that Forge had a registry for this, but unfortunately Sponge does not expose this. I think this would be a great addition to the API, possibly added as a method in Creature like `getSpawnEgg()` which would return an `Optional<ItemType/ItemStack>` of the spawn egg or similar.

**Comment by gabizou** [comment]
It would have to be returning an `Optional<ItemStackSnapshot>` if it made sense because it can have a singleton instance of a snapshot, but at the same time, have no snapshot to begin with. What i'm tempted to do is to make it a `Property`, since it fits well within the realm of Data properties, it would make sense to keep it messed in that sort of system. Since the properties themselves are already wrappers of actual values (in a vague sense).

**Comment by parlough** [comment]
This is not necessary anymore. You can offer the `EntityType` to an `ItemStack` of `ItemTypes.SPAWN_EGG` with `SpawnableData`.
