### ISSUE TITLE
Update Configurate to 3.1.2 to fix file permissions

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeAPI#1331]

**Comment by Minecrell** [comment]
Configurate will be updated once a new version was released, there is no newer release yet.

**Comment by Zidane** [comment]
@Minecrell 

Overriding this decision and reopening this. Either get @zml2008 to push a new release or bump to a specific snapshot.

**Comment by Minecrell** [comment]
@Zidane
We can't bump to a snapshot unless we upload the snapshots to our Sponge repo because it will otherwise break dependency resolution for plugins using SpongeAPI with Gradle. In that case a new configurate release would be probably easier.

@zml2008 Is there anything holding back the new release?

**Comment by zml2008** [comment]
Configurate 3.2 has been pushed to central and will be available within the next few hours
