### ISSUE TITLE
Modify SendCommandEvent

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/SpongeAPI#1409]
Currently `SendCommandEvent#getResult()` always returns an empty `CommandResult` since the event is thrown before the command is executed. The method is almost useless. I propose to split `SendCommandEvent` in `SendCommandEvent.Pre` and `SendCommandEvent.Post` and move the current method to `SendCommandEvent.Pre#getResult()`

**Comment by ryantheleach** [comment]
Related: https://github.com/SpongePowered/SpongeAPI/pull/1333

Note that there is a usecase for having getResult on the pre-event, it's the result in the case that the event is cancelled currently. 

As noted on that PR I don't know if this is behaviour we should be keeping, or if it's an intentional design feature, that can't be replicated any other way.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/7dd9f3faeea31e89b4b34b5eb188d3e434995a9e

(the name is slightly different: `ExecuteCommandEvent.Pre` and `ExecuteCommandEvent.Post`)
