### ISSUE TITLE
..

### ISSUE THREAD

**Issue by drakmirv** [SpongePowered/SpongeAPI#1457]

**Comment by kinggoesgaming** [comment]
This gotta become a sponge meme x.X

**Comment by liach** [comment]
What happened?

**Comment by simon816** [comment]
..

**Comment by Mumfrey** [comment]
.. ..-. / -.-- --- ..- / -.-. .- -. / .-. . .- -.. / - .... .. ... --..-- / - .... . / --. .- -- .

**Comment by ewized** [comment]
@Mumfrey How dare you, I was winning for a long time. :confused:

**Comment by drakmirv** [comment]
I'm sorry, not sure how this got opened by me.  It was not my intention to open an empty issue.

**Comment by srs-bsns** [comment]
This issue is now hamsters.

![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
![hamsterdance](http://www.nihilism.ca/misc/images/hamsterdance.gif)
