### ISSUE TITLE
PaginationService : FontSize

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeAPI#1512]
Hi,
To use Unicode's Private Use Area,
I need to modify the size of caracters because the default value is 0.

Can you create a function to modify this variable ?
[PaginationCalculator.java](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/service/pagination/PaginationCalculator.java#L54)

**Comment by ryantheleach** [comment]
@lesbleu unless these values are not matching on the server, I believe you would also need to update them on the clients. Reading Mojira bug reports has me believing that specifying them in a server resource pack wouldn't be enough.

Yes it's an issue, one we could probably solve by recreating these values if a serverside resource pack was specified, but it's a lot of work. 

The Unicode Private Use Area is super useful though, I'd love to see some richer chat interfaces because of it. 

I just feel that including this in the pagination calculator, with no other utilities however is probably too small of a Usecase.

Would you be happy just specifying these values yourself (easy but not a nice API)? Have the server calculate them from a resource pack instead (hard, current method relies on client side only code, would have to be re-implemented and kept up to date on the server)? 

Another option to consider, is in the 2 years since this file was introduced, running sponge on the client has become a possibility, maybe we should just expose the ability to read 

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/resources/org/spongepowered/common/service/pagination/font-sizes.json

From an external location, generatable by users using Sponge on the client, and promote the code within to a proper command?

**Comment by dualspiral** [comment]
I'm going to close this. The PaginationService in API-8 is replaceable - and I would suggest those wanting extra functions like this should create their own service.
