### ISSUE TITLE
Add Cause : when entity trample farmland

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeAPI#1518]
Hi,
Can you create a new cause when player trampled farmland for event "ChangeBlockEvent.Place" and "ChangeBlockEvent.Break".

**Comment by gabizou** [comment]
You can listen to `ChangeBlockEvent.Post` to get the trampled farmland destruction and cancel it that way. Since it's still a player, you can use some simple logic to figure out whether it's "trampling" of land etc.

To be more precise to the issue itself, causes are an implementation thing, not an API thing (as to what goes in the cause is from the implementation).
