### ISSUE TITLE
Multiple flags in a command leading to errors

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/SpongeAPI#1520]
I'm currently using the lastest SF version from Github

Sponge command parsing seems to be confused when a command has multiple flags.

**Example:**
```
CommandSpec testCommand = CommandSpec.builder()
			    .executor((src, args) -> {
			    	src.sendMessage(Text.of("X: ", args.hasAny("x"), Text.NEW_LINE, "Y: ", args.hasAny("y")));
			    	return CommandResult.success();
			    })
			    .arguments(GenericArguments.flags().flag("x").buildWith(GenericArguments.none()), 
			    		GenericArguments.flags().flag("y").buildWith(GenericArguments.none()))
			    .build();
Sponge.getCommandManager().register(plugin, testCommand, "testcmd");
```

When only the first flag is used, everything is fine:
![Only first flag](https://ss.myftb.de/nw9QS_EN.png)

When the second flag is used it throws an exception:
![Second flag](https://ss.myftb.de/rdn3WhaR.png)

Using both flags also doesn't work:
![Both flags](https://ss.myftb.de/zhZ7mrNJ.png)

**Comment by dualspiral** [comment]
I meant to comment on this a while ago. This isn't so much a bug really. Each command should only have _one_ flag parser, your code should be:

```java
CommandSpec testCommand = CommandSpec.builder()
			    .executor((src, args) -> {
			    	src.sendMessage(Text.of("X: ", args.hasAny("x"), Text.NEW_LINE, "Y: ", args.hasAny("y")));
			    	return CommandResult.success();
			    })			.arguments(GenericArguments.flags().flag("x").flag("y").buildWith(GenericArguments.none())
			    .build();
Sponge.getCommandManager().register(plugin, testCommand, "testcmd");
```

The reason is that the flag parser checks all flags it comes across. The first flag succeeds because the `-x` flag is known to the first parser. The second flag _doesn't_ succeed, because the _first_ parser you specify (for `x`) doesn't know about `y`. Flag arguments are designed to take more than one flag, however, so just chaining them in the one flag argument would work as intended.
