### ISSUE TITLE
ItemStackSnapshot is not Translatable

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeAPI#1594]
`ItemStack` is translatable, and for good reason. One can't simply translate its `ItemType`, since various things (mods, data values, etc) can affect what the resulting translated name of the item is. And yet to accomplish this functionality with `ItemStackSnapshot`, one must call `createStack()`. I'm curious whether this would be a good idea given the implementation, and if not, why.

**Comment by ST-DDT** [comment]
While it is a good idea the main problem is in the impl. Because the current impl relies on the itemstack itself we would have to create it in the impl anyway.

See https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/item/MixinItemStack.java#L232

**Comment by stephan-gh** [comment]
@ST-DDT `ItemStackSnapshot` already maintains a private stack we can use for that: https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/item/inventory/SpongeItemStackSnapshot.java#L74

**Comment by ST-DDT** [comment]
Well if we already have a itemstack instance anyway then i would really agree on adding such a method.
