### ISSUE TITLE
Check if inventory contains slot

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeAPI#1615]
It is a pain to try and find out if a slot in inside an inventory in an event.
E.g. Check if clicked slot is in player inventory.

Therefore I propose adding `Inventory#containsSlot(Slot)` (or Inventory?) to the API

@Mumfrey @Zidane

**Comment by Mumfrey** [comment]
I'd personally prefer `hasChild(Inventory)` because it's consistent with the general contract of inventories (eg. that everything is an inventory) but also has utility in case you have any other kind of subinventory.

**Comment by Faithcaio** [comment]
hasChild would only be for direct subinventories?

**Comment by Mumfrey** [comment]
My interpretation would be that it means the child is anywhere in the descendent tree of the inventory, and that it could be used to determine whether a Slot appears in an Inventory, a Row appears in a Grid, etc. a Row appears in an Inventory, etc.

Your stated goal is "is Slot in Inventory", but the general case of that is "is Inventory in Inventory" is what I was saying. If you prefer `Inventory::containsInventory` rather than `Inventory::containsChild` then I'm ok with that. It's the contract I was more interested in than the name.

**Comment by Mumfrey** [comment]
I suppose the question at that points is whether `containsInventory` respects the identity function. Eg. does `someInventory.containsInventory(someInventory)` return true?

**Comment by Faithcaio** [comment]
so that should work too?
`inventory.query(firstrow).containsInventory(inventory.query(stoneitems))`
basicly checking if each slot is contained in the other inventory

**Comment by Mumfrey** [comment]
The contract of query states that if the query matches every child of a particular inventory, then the inventory is returned. So in your example above the `inventory.query(stoneItems)` were to return a single slot or multiple slots there are two possibilities for the contract of `containsInventory`:

1. That `containsInventory` returns `true` if the supplied `Inventory` is anywhere in the inventory's heirarchy. This would return `true` for a single slot, or `true` if the query matched all slots in the row and thus returned the row itself, but `false` for multiple slots since they'd be returned in a `ResultInventory` which isn't a child of the originally queries inventory, unless

2. The `containsInventory` returns `true` if the supplied `Inventory` **or** all of its children. In which case it would return `true` in the scenarios above but also in the situation that all the slots in the result were children of the row.

Personally I think the first, simpler contract is better because it's more obvious what it does and satisfies the main use-case of checking whether a particular inventory is a child of another.

**Comment by Faithcaio** [comment]
Why not both?
But instead going into another direction for the second one:
As Inventories are a bit like Sets
why not add 
`Inventory#intersect(inventory)` returning slots that are present in both (wrapped in an inventory ofc)
and also
`Inventory#union(inventory)`. returning all slots in both inventories

**Comment by Mumfrey** [comment]
Indeed, would be pretty cool because then you can satisfy the latter using `inv.query().intersect(inv.query()).isEmpty()`

I like that in that it keeps the contract of `containsInventory` much simpler but also allows some more powerful procedures to be run in an expressive way.
