### ISSUE TITLE
Confusion of arguments and parameters in commands

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1617]
Same issue as #1452:

`GenericArguments` should be `GenericParameter`, `SingleArg` should be `SingleParam` and so on.

**Comment by dualspiral** [comment]
In #1587, `GenericArguments` will become part of (via some heavy changes) `Parameter`s for that reason - that would be correct - the are part of the definition of the command. However, I believe that the name `SingleArg` is _correct_, because it represents the data going into the command, and not the definition of the command. Same with `CommandArgs`, that doesn’t contain the definition, it contains the data, and so doesn’t contain parameters, it contains arguments _to_ those parameters.

There is, however, an argument for renaming `arguments` on the `CommandSpec` to `parameters`, and is something else that should be considered.

As we’ve got a large Command API refactor looming, please put your thoughts on #1587 - lots of changes yet to go there so it makes sense to discuss them all there so we just break everything at once, rather than in bits and pieces.

**Comment by randombyte-developer** [comment]
Ah, yeah, I forgot about the large PR. Looking forward to that!
