### ISSUE TITLE
Issue with throws CommandException, IOException

### ISSUE THREAD

**Issue by spide-r** [SpongePowered/SpongeAPI#1631]
Im trying to make a command change a text file in a directory. However whenever I try to use both of those declarations in my command executor, my IDE says that those two are not compatible. Is there a reason for that?

I am using SpongeAPI 5.1.0
My IDE is Eclipse Neon 4.6.2

**Comment by Zidane** [comment]
We need to see some code.

**Comment by spide-r** [comment]
Here is my executor:

```@Override
	public CommandResult execute(CommandSource src, CommandContext args) throws CommandException, IOException
	{
		String word = args.<String>getOne("Word To Add to the file").get();
		myReaderWriter write = new myReaderWriter();
		try {
			write.addToFile(word);
		} catch (IOException e) {
			e.printStackTrace();
		}
			return CommandResult.success();
		}
```

Here is the method I am calling to add words to the file:
```
public void addToFile(String str) throws IOException{

		String path ="wordFile" + File.separator + "words.txt";
		File words = new File(path);
		words.getParentFile().mkdirs();
		words.createNewFile();
            
   FileWriter writer = new FileWriter(path, true);
	writer.append(str);
	writer.append("\n");
    writer.close();
	}
```

**Comment by dualspiral** [comment]
The `execute` method does not include the checked exception `IOException` - you can't add an exception like that. Nor do you have a need to, because you already trap the `IOException` in your code, so the `IOException` in your `execute` method signature is totally unnecessary.

The execute method should be `public CommandResult execute(CommandSource src, CommandContext args) throws CommandException`

**Comment by spide-r** [comment]
It worked! Thanks for helping :)
