### ISSUE TITLE
Missing get/set yield in ExplosionEvent

### ISSUE THREAD

**Issue by Cayviel** [SpongePowered/SpongeAPI#1643]
Although it seems the get/set yield methods for explosions during an explosion event were added a couple years ago (see https://github.com/SpongePowered/SpongeAPI/issues/416) they seem to be missing now. These are important aspects of the explosion event and should be included.

**Comment by gabizou** [comment]
This is because the [ExplosionEvent.Prime allows you to change the explosion](https://github.com/SpongePowered/SpongeAPI/blob/9aeb46721b8bcaa45c96e1b73ef0ddd18c4d78ff/src/main/java/org/spongepowered/api/event/world/ExplosionEvent.java#L61) which has a [radius](https://github.com/SpongePowered/SpongeAPI/blob/9aeb46721b8bcaa45c96e1b73ef0ddd18c4d78ff/src/main/java/org/spongepowered/api/world/explosion/Explosion.java#L60) of which the explosion will affect, amongst other things. It isn't missing at this point, it's been replaced by another name.

**Comment by Cayviel** [comment]
Radius and yield are different: Yield is the percentage of destroyed blocks which drop as itemstacks to the ground after the explosion. Radius is only the radius. It is important important to change the yield without changing the radius. For instance, setting yield to 1.00 should force every block destroyed by the explosion to become an item stack dropped to the ground. This is how it worked before someone removed it from the API. Radius cannot replace yield since it is a different concept entirely. Please re-open the issue

**Comment by gabizou** [comment]
So, looking into the implementation *from two years ago before the event was rewritten*, the event and method you're referring to was not implemented at all.

That being said, I'm going to ignore the fact that you're asking about an event without an implementation in the past and "missing" the mechanic. As it stands currently, the `radius` for an explosion directly dictates the `yield`, as in implementation there is no difference. The mechanic/calculation you're talking about doesn't even exist in the implementation as you're mentioning.

Likewise, even in an [older API, the yield refers to the radius of the explosion](https://github.com/Bukkit/Bukkit/blob/f210234e59275330f83b994e199c76f6abd41ee7/src/main/java/org/bukkit/entity/Explosive.java#L9). So no, there's nothing missing, just modify the radius of the explosion and consider it the size, unless you want to write a PR to the implementation to modify the resistance factoring away from the actual size of the explosion.
