### ISSUE TITLE
Confusing error with player argument

### ISSUE THREAD

**Issue by MinusKube** [SpongePowered/SpongeAPI#1647]
There is a confusing error when the `player` argument is used inside a subcommand and it's not the last argument of the command:
![image](https://user-images.githubusercontent.com/13206601/30497487-4d1ab84a-9a53-11e7-96f5-4b6530eb20dd.png)
(The usage is also wrong, but it has already been said in another issue)

When it's not used inside a subcommand or when it's the last argument, it works as expected:
![image](https://user-images.githubusercontent.com/13206601/30497533-72af7c26-9a53-11e7-9418-33b08d799c11.png)

Example code to reproduce the issue:
```java
CommandSpec addEcuSpec = CommandSpec.builder()
        .executor((src, args) -> {
            Player player = args.<Player>getOne("player").get();
            double amount = args.<Double>getOne("amount").get();

            src.sendMessage(Text.of("Target: " + player.getName() + ", amount: " + amount));
            return CommandResult.affectedEntities(1);
        })
        .arguments(onlyOne(player(Text.of("player"))), doubleNum(Text.of("amount")))
        .build();

CommandSpec ecuSpec = CommandSpec.builder()
        .executor((src, args) -> CommandResult.empty())
        .child(addEcuSpec, "add")
        .build();

Sponge.getCommandManager().register(this, ecuSpec, "ecu");```

**Comment by ryantheleach** [comment]
I'm having troubles believing this hasn't raised it's head earlier, maybe it has but people couldn't track it down or it's new?

Have you tried without onlyOne? or using playerOrSource? Just trying to narrow it down further.

**Comment by MinusKube** [comment]
Yeah I tried with onlyOne, it's the same. I didn't try with playerOrSource, I think it will work but I don't want the source.

Also, it really happens in a specific case : player + child + not last argument, so it maybe explains why nobody noticed it.

**Comment by dualspiral** [comment]
This is effectively the same as #1165, #1272, #1542.

What happens is that if a child command can't be parsed, Sponge tries to fallback to the parent command, and starts from a clean slate - meaning that it will only report parsing errors for the parent. There is no way (currently) to specify that if you use the child command keyword, you should _never_ fallback to the parent.

I'm solving this in my refactor (see #1587). I'm not too sure the best way to try to patch up the current command system to make this better - but this is a quality issue that perhaps we shouldn't brush under the carpet until we finalise the re-write, even if it's more patch work rather than a proper solution.

To solve your specific issue though, because you have an empty executor in your parent command spec, just remove the executor. You _can_ specify child commands without an executor: as there is no fallback, the usage string/error message should be correct.

**Comment by ryantheleach** [comment]
I'm guessing that the empty executor is actually populated, and it was just omitted for brevity / example.

**Comment by dualspiral** [comment]
In the latest SF for API 7 snapshot, I've added method `childArgumentParseExceptionFallback` to the `CommandSpec`. You need to set this to `false` to get the behaviour you expect above, I opted to make this a non-breaking change for API 7.
