### ISSUE TITLE
[Feature] Add @Instance(modId/pluginId) annotation

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeAPI#1661]
An annotation similar to Forge's `@Instance(modId)` could be pretty useful. Syntax could be something like this:

```
@Inject
@Instance("luckperms")
private static Object luckperms
```

This should work for both plugins and mods when running on Sponge-Forge.

If the type is Object or the type of the main class the direct object should be injected, when the type is a PluginContainer the corresponding plugin container should be injected instead.

**Comment by ST-DDT** [comment]
Does declaring `@Instance("luckperms")` make luckperms an optional or required dependency?
The [javadocs](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/Mod.java#L320) aren't quite clear on this.

Why do you want to access the plugin directly vs its exposed services? (just curious)

**Comment by kashike** [comment]
It's a shortcut for `this.game.getPluginManager().getPlugin("id")`, basically.

**Comment by BrainStone** [comment]
@ST-DDT First of all I'd personally use it the set my plugin instance without having to manually set it. And then some plugins have special methods you want to call.  
For example when you have a core plugin, plugins that depend on it may need to call methods on the instance of the core plugin.

**Comment by ryantheleach** [comment]
I thought you could get the plugin containers of other plugins injected already , and from that the plugin instance.

Where possible though, I think it's better to get plugins to register explicit services using our service manager.

**Comment by dualspiral** [comment]
You couldn’t do this with injectors, especially ctor injectors, because at the time we apply them, some plugins that you target may not have even been instantiated yet.

My worry is that something like this could harm the startup time of somone who has a lot of plugins - I haven’t looked into this much, but my feeling is that we would have to (re)scan all the plugin classes ourselves for `@Instance` annotations on fields after they are all instantiated. This is one of those cases that I feel like syntactic sugar could impact us badly when you could easily do as @kashike suggests above.

**Comment by XakepSDK** [comment]
And how to handle ChangeServiceProviderEvent? Reinject?
How to handle, if there is no such plugin/mod? Null injection?
If plugin name equals to mod name?

I think, sponge needs something like ModContainer(like PluginContainer). 
For api providing you can use service manager.

**Comment by kashike** [comment]
We have [`PluginContainer`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/plugin/PluginContainer.java) already.

**Comment by XakepSDK** [comment]
Yeah, but for mods. Is there any api to get mod list or mod main class instances?

**Comment by Cybermaxke** [comment]
@XakepSDK `PluginContainer`s are also available for mods.

**Comment by Zidane** [comment]
@dualspiral @kashike we could limit this simply to the Plugin itself. I'm seeing a lot of plugins having a public static reference to their plugin object because they store their own game objects in it (managers, factories, etc). To do so, they have to either add a constructor and set the reference to this or a GameConstruction event listener and set it to this on line 1. This would remove that need.

Let me stress though that it'd only work for the plugin itself. In no way should it work for other plugin instances.

**Comment by kashike** [comment]
I don't think such a thing is necessary, really. It removes 1-3 (depending on if you have a constructor already or not) lines of code at most - and static references to the plugin should really be discouraged.

**Comment by dualspiral** [comment]
I'm in broad agreement here. The original issue was to do this to inject _other_ plugin references into a plugin, and it's been said this shouldn't work for that anyway. As @kashike said, it's 1-3 lines of code for a plugin add this, while adding code to scan for annotations on fields and then using reflection to supply the instance of itself to said field is going to be more code than this, and _much_ slower.

I see little benefit for a lot of work (comparatively) for an annotation I don't think will get used that much which ultimately provides a plugin object that you have to cast yourself anyway. What's the point of making more work for everyone involved when the tactic of `instance = this` (whether it should be discouraged or otherwise) does the same job?

Again, I worry that this would impact startup performance and is just another layer of code and logic that we ultimately just don't need.
