### ISSUE TITLE
Crop trampling

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1698]
According to bloodmc https://github.com/MinecraftPortCentral/GriefPrevention/issues/525#issuecomment-345590668 its not possible to cancel block break events fired when an entity falls down on a crop-block due to missing cause/context in sponge.

**Comment by ryantheleach** [comment]
I'm assuming the best way to implement this is with a player-move cause and or context frame?

So that way crop-block, pressure plates, trip wires, redstone ore, all trigger as a collision with a player?

Crop Smushing might be slightly different... but I'd prefer if it wasn't since it conceptually makes sense somewhat.

**Comment by ryantheleach** [comment]
I'm not sure the API needs additional events to deal with this, and it might be easily handled purely in implementation.

**Comment by ryantheleach** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @NeumimTo! I've moved your issue to [SpongePowered/SpongeCommon#2041](https://github.com/SpongePowered/SpongeCommon/issues/2041).
