### ISSUE TITLE
Finer control of the experience bar

### ISSUE THREAD

**Issue by Techdaan** [SpongePowered/SpongeAPI#1739]
Involves both Sponge 6.0.0 and 7.1.0 running on Forge.

I am currently working on a plugin which requires finer control of the experience bar. Currently, the only way is changing the `Keys.EXPERIENCE_SINCE_LEVEL` property on a player depending on the value of the key `Keys.EXPERIENCE_FROM_START_OF_LEVEL`. Sadly, this does not allow for a fine control of the experience bar, especially at low levels where there's only a few experience points required to level up. This means it's impossible to fill up the experience bar to exactly `0.241f`.

Spigot offers the method `Player.setExp(float exp)` to fill up the experience bar partially (And even over 1, which results in multiple action bars)

The same can be achieved with Forge by manipulating the `EntityPlayer.experience` field, which is a float too.

I have tested modifying the Forge fields on both Minecraft 1.10.2 (Sponge 6.0.0) and Minecraft 1.12.2 (Sponge 7.1.0) and it works.

**Comment by ryantheleach** [comment]
I've marked this API 8, as it's my suspicion that it will require API breakage in order to properly expose fractional experience values. 

That said, I entirely agree that this usecase should be supported while possible, even if it means leaking implementation details slightly. 

It's possible we could expose a `setExp(float exp)` that represents a percentage from 0 to 1 of how full the experience bar is to mimic Minecraft internals, but I still feel that it should be thought of as a utility / helper method should the internals change in the future.

In my eyes, the best method of fixing this would be to expose floats or doubles as the values that we show in the experience, but, I'm also not sure of the side effects this might have on the serialization.

That said, the serialized player dats currently store, `XpTotal: 0` `XpLevel: 0` and `XpP: 0.0F` so it would appear to have some duplication, but supports the idea that it should be reasonable to expose it.

@JBYoshi I've seen you tackling rounding errors in the XP calcs previously, so I would appreciate your input on this issue.


Edit:

I do wonder though, if it were possible to expose this on the Viewer interface instead, allowing additional control of the client UI to plugins, without necessarily changing the experience system itself.

**Comment by Defman** [comment]
I can see a few problems with this, one of them being "what is exp in minecraft". It's a bar, it shows the progress of exp points until next level. This is how the minecraft client sees the exp bar, this is not something we can change. We can expose a api to set the exp as a procentage but it will depend on the players current level. If the player is level 1 and we set the bar to 50% it will result in setting the players exp to 3 or 4 since it requires 7 exp to reach level 1.

**Comment by ryantheleach** [comment]
@The-Defman I appreciate the sentiment, that's basically the point I was making in the post above, but the base game actually have a lot finer control over the bar then integer amounts of xp, which is why @Techdaan made the issue in the first place.

So it's more a question of abstraction then anything else.

Worst comes to worst, if we offer a setExp() method, we can adjust the xp, just make the resolution implementation specific, allowing it to change in the future without breakage.

**Comment by JBYoshi** [comment]
My thought is that this would be more of an issue for contextual data, once that comes out.

**Comment by ryantheleach** [comment]
I honestly don't see how it relates to contextual data at all, aside from purposely causing a server/client desync. @JBYoshi Could you elaborate?

**Comment by JBYoshi** [comment]
Contextual data is primarily intended for making different players see different data on an object. However, I also see it as a way to set client data that differs from the server data. That's what this appears to be requesting.

**Comment by ryantheleach** [comment]
I mean, you could construe it that way, but I think most people would be happy enough just being able to see the granularity of experience of a player between level 0 and 1. At the moment because of the rounding and it being measured in discrete points on Sponges side, it's hard to control the bar accurately.

I definitely see it being contextual data if you want to manipulate it independently of the server, but at minimum the request is just to be **able** to control it at a sub-point level.

**Comment by ImMorpheus** [comment]
API8 has `Keys#EXPERIENCE` which allows for finer control of the xp bar when combined with `Keys#EXPERIENCE_FROM_START_OF_LEVEL` so the issue is solved
