### ISSUE TITLE
Provide more getters and setters for data that is genuinely connected to the corresponding objects

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeAPI#1830]
The issue at hand is that to access and modify data of objects (like ItemStacks) you have to make use of the data API. While having this is really useful it seems very very clunky for data that is genuinely interconnected with the respective object.

Examples of this would be enchantments of ItemStacks. While an ItemStack might not always have enchantments, enchantments are still very closely connected to ItemStacks.

Another example would be Players and sneaking. Or the EntityDamageEvent and a DamageSource.

While it is possible that these object may have been contructed in a way that they don't have the data, this will only be the case if they have been constructed in an artificial way. (Like the EntityDamageEvent being manually contructed)  
These implementations could be very simple like:

```java
public interface ItemStack ... {
  // ...

  default List<Enchantment> getEnchantments() {
    this.get(Keys.ITEM_ENCHANTMENTS).orElseGet(Collections::emptyList);
  }

  default void setEnchantments(List<Enchantment> enchantments) {
    this.offer(Keys.ITEM_ENCHANTMENTS, enchantments);
  }

  // ..
}
```

The reason behind this would be to simplify working with the API. Especially inexperienced developers have a hard time getting used to this system. So while naturally not all data can or even should be accessible through simplified methods, I think it would be very useful to many developers and would even speed up developing plugins.

I do realize that this would increase the burden of maintaining these getters, however I think the benefits (especially for developers new to the API) outweigh the disadvantages.

**Comment by gabizou** [comment]
I'm going to have to shut this down as in the past, we've seen where API's have to change, for good or for bad. While our deprecation policy is pretty good in terms of deprecating and removing the next major API version, I don't see the benefit of introducing what would be considered guarantees to various objects. The only reason why these guarantee methods exist on `Entity` interfaces is due to the hierarchy of classes having different components/implementations based on those interfaces.

The point of the Data API is to remain as abstract as possible to allow for flexibility and changes that can be allowed to take place without breaks or maintenance on the API implementation itself. Keeping as little implementation in the API as possible (even with `default` methods) is our goal, and this would re-introduce potential implementation issues in the future or incompatibilities with mods in the future past or present with method signatures. The reason the default methods can exist on `Entity` interfaces is because it is something unique to SpongeAPI, both in return types and accepting types. Re-introducing the proposed methods would clash with the existing implementation (in development granted) but potentially any other mod adding similarly named methods with similar return types (again, generics).

Working with Data API is fairly simple when the only concept you have to grasp is `get(Key)` and `offer(Key, Value)`.
