### ISSUE TITLE
TextTemplate does not support multiple colors

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/SpongeAPI#1855]
```java
public TextTemplate claimCreateSuccess = TextTemplate.of(TextColors.GREEN, TextTemplate.arg("type"), TextColors.AQUA, " created!", TextColors.LIGHT_PURPLE, "Use /trust to share it with friends.");
```

Here is a screenshot showing output of the above text template.

![bug](https://i.imgur.com/mVP9LWT.png)

The issues I see are as follows 

1. You cannot use multiple colors as the last specified seems to win.
2.  `TextColors.GREEN` should make argument green. I know you can set the arg color on the template itself but this shouldn't be required.
3. TextTemplate args should support passing colors with the argument.

**Comment by randombyte-developer** [comment]
Possibly related to https://github.com/SpongePowered/SpongeCommon/issues/1152

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 7) of SpongeAPI. Support for API 7 ended in January 2022.

API-7 is now end-of-life. We will not be issuing any more API updates for version 7 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API7/1.12.2[^2]
___


The Text API is now supplied by the [Kyori Adventure library](https://github.com/KyoriPowered/adventure/) so this issue is no longer relevant to this repository.

[^1]: https://forums.spongepowered.org/t/status-update-8th-january-2022-spongeapi-8-released/39861#minecraft-1122-spongeapi-7-10
[^2]: https://forums.spongepowered.org/t/sponge-status-update-28th-may-2022/40135#api-71122-community-support-8
