### ISSUE TITLE
Allow specificity within InvisibilityData (or by other means)

### ISSUE THREAD

**Issue by FerusGrim** [SpongePowered/SpongeAPI#1865]
Currently, a Player's VANISH state is binary: Off or On

There seems to be no way to specify to whom a player should be hidden.

I think I speak for a number of people when I say this is a pretty important feature for the API - I'm honestly surprised no one else has made an issue for this.

**Comment by FerusGrim** [comment]
After a more thorough searching of issues (including closed), it seems as though this is a duplicate of #1461.

Although, I'm unsure of why #1461 would have been closed when the related PR (#1046) hasn't been merged. This is still, obviously, an issue.

**Comment by gabizou** [comment]
@FerusGrim The issue was closed because the PR is going to resolve the issue. It doesn't make sense to continue discussion when the PR itself is requiring discussion. There's quite a few cases where we've closed API issues because a PR that is *expected* to be maintained and merged into the API would completely resolve it (also keeps multiple discussions and potentially outdated information out of confusion when it's focused on one discussion thread). This is still a core issue of having contextual data setting and getting, so I don't see why multiple discussions are necessary (and why we closed the original issue).
