### ISSUE TITLE
Change how Configs are Injected to Plugins

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeAPI#1886]
1. ~~Replace `ConfigDir` and `DefaultConfig` with `Config`~~

2. ~~Add option to choose configuration impl. (hocon/yaml/toml/xml/smth else)~~

3. ~~Allow to choose config name in annotation~~(superseded by p.6)

4. Inject `ConfigurationLoader<ConfigurationNode>` instead of `ConfigurationLoader<CommentedConfigurationNode>`

5. Drop `File` injection support. `File` has bad design and many newbies don't know, how to use `File` properly. They do these constructions: `new File("my/dir" + configDir);` <- completely wrong usage. May give unpredictable results on different platforms, while `configDir.resolve("my").resolve("dir")` gives predictable result and is more readable.

6. Add support to choose path + filename to `ConfigDir` and `DefaultConfig` annotations.
e.g. `String[] path() default {};` - injects path.resolve(path()) result.
`@DefaultConfig(sharedRoot = false, path = {"my", "subdir", "config.conf"})`
Restrictions for `path` array argument - alphanumeric chars, underscore, dash. `[a-zA-Z0-9_-]`

**Comment by ryantheleach** [comment]
I don't see the point of injecting a wildcard? Wouldn't it be better to just inject the concrete type of what they want?

> Add option to choose configuration impl. (hocon/yaml/toml/xml/smth else)

We could, but it was my understanding that the annotated injected versions were supposed to be "easy mode" and for anything more complex or harder the developer would be expected to do it themselves.

Basically a way of biasing the community towards whichever standard Sponge prefers.

> Allow to choose config name in annotation

That seems reasonable.

> Replace ConfigDir and DefaultConfig with Config

I need more details.

Injecting the Config directory should stay, it's there for people to manage their own configuration manually, and I don't see a **good** reason to break it.

The annotation name "DefaultConfig" could do with some work maybe? But I'd need to see a proposal that's better.

**Comment by jamierocks** [comment]
Afraid that choosing the config name in the annotation isn't currently possible using Guice. :(

Wanted to do the same thing with another project

**Comment by XakepSDK** [comment]
At this moment i can't just inject `ConfigurationLoader<ConfigurationNode>`, i should explicitly inject `ConfigurationLoader<CommentedConfigurationNode>`. Will wildcard injection allow this?(iirc, yes)
We have 2 annotations to do nearly same thing. For now `ConfigDir` support injecting `File` and `Path`, why not replace these 2 annotation with just `Config` annotation?

**Comment by dualspiral** [comment]
*Nearly*, but *not* the same. There are valid use cases for both, we shouldn't drop one or the other.

**Comment by XakepSDK** [comment]
They inject config path or config loader, they have same `sharedRoot` field, why there should be two annotation for nearly exact same thing?

Also, i propose drop for `File` injection, because so many hello-world coders don't know how to use it correctly and they hardcode things like path separetor.
(`new File("dir1/dir2" + confDir)`) `confDir.resolve("dir1").resolve("dir2")` looks 100 times better and safer.

@jamierocks its possible - https://github.com/google/guice/wiki/CustomInjections

**Comment by dualspiral** [comment]
Because they both target a `Path` or `File` and return different paths?

To be honest, I'm not seeing overwhelmingly good reasons for dropping the annotations you suggest. If your strongest argument is that they are nearly the same, then I don't see that gaining traction. They both have uses. You may be dynamically generating config files with unknown names at runtime (extreme module system or something), or have configs in subdirectories, so having the root directory is useful. We should generally only remove functionallity if it's going to be obsolete or harmful in the future - neither of these occurs here.

Injections and annotations don't solve everything. At some point we need to draw the line, I was overrelying on DI and Guice with Nucleus and it actually got me in all manner of problems. I'm not saying Sponge is misusing DI so much (Nucleus certainly was, boy were there some serious performance problems with what I was doing!), but we really don't need to start making everything annotation driven.

It is good to remember the developer base here. Many of our community are learning Java just to use Sponge. The overuse of concepts like this may cause confusion down the road, and while you might argue that they should be learning Java first, things like DI and using annotation driven behaviours are advanced concepts that serve to confuse and don't help teach the basics. We don't need to muddy the water further, what we have quite possibly could be improved, but not to the extent here.

`DefaultConfig` and `ConfigDir` describe what they are - the path for the default config file and the path for the plugin allocated config directory.

> Basically a way of biasing the community towards whichever standard Sponge prefers.

Yes, exactly this. We don't enforce the default, but it makes things easier for both us and for those that are starting out. HOCON? YAML? JSON? Why should we force them to make that decision when the default is perfectly adequate?

To be honest, while I see the value in some of your points, please ensure you explain your rationale behind why you want what you want. You've just said "we should do this", there is no justification.

**Comment by XakepSDK** [comment]
Good opinion. Now i can agree with you. See first post edit for.

**Comment by ryantheleach** [comment]
5. Whilst there needs to be correct escaping for various file platforms, using `/` isn't terrible.

https://stackoverflow.com/questions/2417485/difference-between-file-separator-and-slash-in-paths/2417546#2417546

**Comment by XakepSDK** [comment]
@ryantheleach this is win nt feature, iirc. `fs.normalize(String)` just removes extra separators.
From `UnixFileSystem`:
```java
public String normalize(String pathname) {
    int n = pathname.length();
    char prevChar = 0;
    for (int i = 0; i < n; i++) {
        char c = pathname.charAt(i);
        if ((prevChar == '/') && (c == '/'))
            return normalize(pathname, n, i - 1);
        prevChar = c;
    }
    if (prevChar == '/') return normalize(pathname, n, n - 1);
    return pathname;
}

private String normalize(String pathname, int len, int off) {
    if (len == 0) return pathname;
    int n = len;
    while ((n > 0) && (pathname.charAt(n - 1) == '/')) n--;
    if (n == 0) return "/";
    StringBuffer sb = new StringBuffer(pathname.length());
    if (off > 0) sb.append(pathname.substring(0, off));
    char prevChar = 0;
    for (int i = off; i < n; i++) {
        char c = pathname.charAt(i);
        if ((prevChar == '/') && (c == '/')) continue;
        sb.append(c);
        prevChar = c;
    }
    return sb.toString();
}
```

**Comment by XakepSDK** [comment]
Oracle says, that `File` is legacy and has many issues.
https://docs.oracle.com/javase/tutorial/essential/io/legacy.html

**Comment by kashike** [comment]
> 2. Add option to choose configuration impl. (hocon/yaml/toml/xml/smth else)

:+1:

> 3. Allow to choose config name in annotation

Use case?

> 4. Inject `ConfigurationLoader<ConfigurationNode>` instead of `ConfigurationLoader<CommentedConfigurationNode>`

:+1: - down with HOCON!

> 5. Drop `File` injection support. `File` has bad design and many newbies don't know, how to use `File` properly. They do these constructions: `new File("my/dir" + configDir);` <- completely wrong usage. May give unpredictable results on different platforms, while `configDir.resolve("my").resolve("dir")` gives predictable result and is more readable.

:+1:, for API 8.

> 6. Add support to choose path + filename to `ConfigDir` and `DefaultConfig` annotations.
e.g. `String[] path() default {};` - injects path.resolve(path()) result.
`@DefaultConfig(sharedRoot = false, path = {"my", "subdir", "config.conf"})`
Restrictions for `path` array argument - alphanumeric chars, underscore, dash. `[a-zA-Z0-9_-]`

Use case? Personally, I'd go for something like:
- `sharedRoot = true`: `config/<id>.<extension>`
- `sharedRoot = false`  `config/<id>/config.<extension>`

Anything else should require be done manually, in my opinion.

**Comment by XakepSDK** [comment]
6. \- you can directly inject required loader without manually creating it. I find it useful, it gives ability to lessen you code for 3-4 lines.
Also, if 3. will be implemented, file extension may be automatically appended by implementation.(e.g. forces loader-specific extension yml/conf/json/toml/xml)

**Comment by ImMorpheus** [comment]
I was working on 4 but noticed that the configurationnodeprovider used by guice is calling https://github.com/SpongePowered/SpongeAPI/blob/04ac0913422e99251dbfca455005845f8cd9edf0/src/main/java/org/spongepowered/api/config/ConfigRoot.java#L75

We would need to change that too (and I disagree with that, the return type is there to state that the plugin config supports comments). Additionally the implementation uses a `HoconConfigurationLoader` https://github.com/SpongePowered/SpongeCommon/blob/f22e4da9392cdcbe124ddf8d1ac97f0d2cf6a6a1/src/main/java/org/spongepowered/common/config/PluginConfigRoot.java#L66  which extends `AbstractConfigurationLoader<CommentedConfigurationNode>`

https://github.com/SpongePowered/SpongeCommon/pull/3125 solved 5 and the others have been fixed. I think this can be closed.
