### ISSUE TITLE
Better javadocs for CommandElements, especially those which can return multiple instances

### ISSUE THREAD

**Issue by benjaminmordaunt** [SpongePowered/SpongeAPI#1892]
The documentation for many of the `CommandElement`s should be updated to inform the programmer that they are capable of returning multiple instances. In some cases, the vocabulary used suggests directly that only a single instance can be returned.

This is especially important as the method signature gives no information about the type(s) it stores (as it just returns a `CommandElement`).

For example:
![playerdocsfial](https://user-images.githubusercontent.com/17656637/43690214-3e33fd0a-98fe-11e8-95df-16a04ee3b303.png)

It is inconvenient to keep referring back to the Sponge Docs to clarify. GenetricArguments.player may match with multiple players and an `onlyOne` wrapper may need to be used.

**Comment by ryantheleach** [comment]
You should not use an onlyOne wrapper unless it is impossible for your plugin to accept more then one player, instead you should be acting upon all users passed in.

Otherwise you prevent your users from being able to use Minecraft Selectors, among other things.

That said, your issue about the JD is valid.

**Comment by benjaminmordaunt** [comment]
Slip of the tongue, amended.
