### ISSUE TITLE
Inventory NoSuchElementException error

### ISSUE THREAD

**Issue by Shmeeb** [SpongePowered/SpongeAPI#1894]
![image](https://user-images.githubusercontent.com/141554/43991790-fad16ebc-9db2-11e8-8976-d653e42e6e89.png)

![image](https://user-images.githubusercontent.com/141554/43991794-07838cc6-9db3-11e8-808f-ab852d0f3ad7.png)

Running: 

![image](https://user-images.githubusercontent.com/141554/43991796-0e8a5982-9db3-11e8-872b-7ae24d18bf16.png)

**Comment by ryantheleach** [comment]
In future, having the text is immensely more helpful then images of text.

It allows the developers to copy the text, search for things in the text, and scan/read it in the format they prefer, with the browser styles they prefer, AND REMAP the obfuscation mappings.

Luckily the logs you posted didn't **have** obfuscated mappings, so in this specific case it's almost bearable.

Images hosted elsewhere are also annoying in they tend to go down at inopportune moments.

I've edited your post to take the externally hosted images, and pasted them directly into your post, so it will survive the life of this issue.

Additionally, this has been posted to the SpongeAPI issue tracker, where this issue is more appropriate to SpongeCommon/SpongeForge

**Comment by ryantheleach** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Shmeeb! I've moved your issue to [SpongePowered/SpongeCommon#2057](https://github.com/SpongePowered/SpongeCommon/issues/2057).
