### ISSUE TITLE
BlockChangeFlag is not extends CatalogType

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/SpongeAPI#1946]
The `BlockChangeFlag` interface is not extends `CatalogType`. This creates big problems for serialization of this object. I hope there is no such thing anywhere else...

**Comment by Cybermaxke** [comment]
This was intentional, although I don't remember the reason for that. @gabizou ?

**Comment by gabizou** [comment]
It's difficult to make it serializable because it's based on an integer value passed from implementation of which some mods have their own bits they pass around for their own statefulness. There's no real good way to serialize the flag aside from having the exposed flags, but again, implementation has it's own set of flags it needs to follow (including sponge created ones for the api).

Sponge knows of 6 bit flags, but mods can introduce more.

**Comment by Lignium** [comment]
Will there be any solution for this issue? Of course, I can refuse such functionality, however, it would be nice to think up something about this.
