### ISSUE TITLE
Renaming of TileEntityArchetype to BlockArchetype and something else

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/SpongeAPI#1985]
I suggest renaming the class `TileEntityArchetype` to `BlockArchetype`. The fact is that this class is essentially a snapshot of the block with all its data, but except for its original position and world. When applying an archetype, it works similarly to restoring a `BlockSnapshot` with a given position and world. The class is misleading by its name, without revealing its true purpose.

Let's compare the block classes with the entity classes:

`EntitySnapshot` <-> `EntityArchetype`
`BlockSnapshot` <-> **`TileEntityArchetype`**
_`LocatableSnapshot`_ <-> _`Archetype`_

The most interesting thing is that with `TileEntityArchetype` you can call the `toSnapshot` method, which will result in a conversion to `BlockSnapshot`.

I now needed a block class with all data (`BlockState` is not suitable, since it does not contain tile entity data) without location and without comparing position and world for `equals` method (well, and for `hashCode`).

I would also like to note that both archetypes (`EntityArchetype` and `TileEntityArchetype`) lack the implementation of the `hashCode` and `equals` methods.

And it will be like a bonus, I accidentally saw it:

https://github.com/SpongePowered/SpongeCommon/blob/199420d4ec71ca0096a0ae1d5845ebdf8344536b/src/main/java/org/spongepowered/common/block/SpongeTileEntityArchetype.java#L84

**Comment by gabizou** [comment]
Not going to rename it to `BlockArchetype` because it's based on the concept of a [`TileEntity`](https://github.com/SpongePowered/SpongeAPI/blob/b2736425ce386018267484f3fed65c9950e5d984/src/main/java/org/spongepowered/api/block/tileentity/TileEntity.java#L50). Unless we do decide to rename [`TileEntity` to `BlockEntity`](https://github.com/SpongePowered/SpongeAPI/issues/1957), I'm not really keen on renaming this class either.

To add on 

> The most interesting thing is that with `TileEntitySnapshot` you can call the `toSnapshot` method, which will result in a conversion to `BlockSnapshot`.

That's because `BlockSnapshot` is a sometimes misused object to guarantee that the block will be restored, regardless whether the location matches or not. `TileEntityArchetype`s design was to place a `TileEntity`, regardless whether the `BlockState` supports it fully or not (examples are pistons, done a lot of handling with those, implementation details mean that not all `TileEntity` instances are actually backed by a `BlockState` that supports tile entities). Likewise, because `TileEntityArchetype` has no reference to a `Location` or position, or world, or identifying information except the raw data that it needs to apply *to a location*, the method `toSnapshot` is used to create a snapshot. It's also why applying to a location does a similar validation check. The `BlockState` is there because more often than not, a `TileEntity` will check itself that it's "contained" in the correct `BlockState`, otherwise you run into problems of the `TileEntity` removing itself (as I've been fighting with Pistons for the last two weeks over).

> I now needed a block class with all data (`BlockState` is not suitable, since it does not contain tile entity data) without location and without comparing position and world for `equals` method (well, and for `hashCode`).

I'm not sure what you mean by this. `BlockSnapshot` contains literally all the pertinent information to recreate the *exact* data at the location (including `TileEntity` information, [if there's a `TileEntity` at that position](https://github.com/SpongePowered/SpongeCommon/blob/199420d4ec71ca0096a0ae1d5845ebdf8344536b/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L1916-L1952), because during [block event handling, those snapshots need to be restored if their transactions are cancelled](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/tracking/TrackingUtil.java#L599-L608). If you want to compare block information for tile entity information, you have to use `TileEntity` instances, snapshots aren't likely to support what you want, but archetypes can be reworked to suit your needs to add a `dataEquals()` or something of that kind.



> I would also like to note that both archetypes (`EntityArchetype` and `TileEntityArchetype`) lack the implementation of the `hashCode` and `equals` methods.

Implementation detail, make an issue on SpongeCommon for that please.

**Comment by Lignium** [comment]
Alternatively, you can add a method to access the tile entity data as a `DataView` object and a method to determine the type of tile entity:

1. `DataView BlockSnapshot#getTileEntityData()`
2. `TileEntityType BlockSnapshot#getTileEntityType()`

In this case, I can manually compare the BlockState and tile entity data.

**Comment by Zidane** [comment]
Closed in api-8.
