### ISSUE TITLE
No raw data for ImmutableDataHolder

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeAPI#2003]
Unlike DataHolder's `setRawData`, there is no `withRawData` method for "setting" raw data on ImmutableDataHolder.

**Comment by gabizou** [comment]
Many immutable structures just don't support raw data or `DataView`s in general. Case in point: `BlockState`, `FluidState`, `LocatableBlock`. The ones that *would technically support it* are `ItemStackSnapshot`, `FluidStackSnapshot`, `EntitySnapshot`, and `BlockSnapshot`. The fun part is that `BlockSnapshot` already has a `withContainer` method, but it seems that we ended up missing that for `EntitySnapshot` when it was created.

**Comment by pie-flavor** [comment]
I do feel like it should be *some* kind of superinterface that specifies such a method.

**Comment by ImMorpheus** [comment]
Fixed in API 8 with the Data API refactor.

`SerializableDataHolder.Mutable#setRawData` https://github.com/SpongePowered/SpongeAPI/blob/992ef50c171183070bede2d234379052613d830e/src/main/java/org/spongepowered/api/data/SerializableDataHolder.java#L81
`SerializableDataHolder.Immutable#withRawData` https://github.com/SpongePowered/SpongeAPI/blob/992ef50c171183070bede2d234379052613d830e/src/main/java/org/spongepowered/api/data/SerializableDataHolder.java#L112
