### ISSUE TITLE
Get and modify the block that contains a painting or item frame entity

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/SpongeAPI#2015]
Paintings and item frames have data about the block in which they are contained. In NBT tags, these parameters are called `TileX`, `TileY` and `TileZ`. SpongeAPI does not allow to obtain and modify these data, which leads to the fact that it is impossible to move an existing item frame or painting. The moved painting or item frame may fall down after some time, since the block on which it hung may no longer exist.

I ran into this problem when trying to move an existing structure along with all the entities inside, item frames and paintings fell.

Or maybe the API already has this feature?

**Comment by gabizou** [comment]
> SpongeAPI does not allow to obtain and modify these data, which leads to the fact that it is impossible to move an existing item frame or painting

Pretty sure it does, if you're using the Schematic/EntityArchetype API, you have full access to the compound that is read in to the entities.

> The moved painting or item frame may fall down after some time, since the block on which it hung may no longer exist.

I'd be curious to find out where that's happening as that's likely an implementation issue.

Otherwise, this issue is already resolved in the API, you just need to know the [format of the Entity to manipulate the targeted tile data](https://minecraft.gamepedia.com/Item_Frame#Entity_data).

**Comment by Lignium** [comment]
> I'd be curious to find out where that's happening as that's likely an implementation issue.

~~Just checked. Item frame works out well, there are no problems, but a painting just disappears when moved, it doesn't even fall out.~~

**UPD:**
And no, I'm wrong. Everything is much more interesting... It turns out that the painting is simply not visible when moving, if I rejoin to server, it appears in a new place. Looks like this is the problem of the game itself?
