### ISSUE TITLE
RequiringPermission fails even though child CommandElement is optional.

### ISSUE THREAD

**Issue by alexstaeding** [SpongePowered/SpongeAPI#2083]
Currently, supplying an argument like:
```java
GenericArguments.requiringPermission(  
    GenericArguments.optional(GenericArguments.onlyOne(GenericArguments.user(Text.of("user")))),
     "some.permission"
)
```
will always fail for a user without the permission "some.permission" because parsing fails before it checks whether a child argument is optional.

**Comment by ItsDoot** [comment]
Do this instead:
```java
GenericArguments.optional(
    GenericArguments.requiringPermission(
        GenericArguments.onlyOne(GenericArguments.user(Text.of("user"))),
        "some.permission"
    )
)
```

**Comment by dualspiral** [comment]
Okay, I finally had some time to consider this issue and... this issue isn't really representative of what was talked about. I recally reading the issue at the time it was made, and the conversation surrounding it. What @ItsDoot said here is correct, but it's not actually the reason I asked for an issue to be created.

The problem is to do with the usage, it'll potentially leave `[]` in the usage string. I just need to eliminate that ghost.
