### ISSUE TITLE
Can't get item from block

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/SpongeAPI#2100]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.10
- SpongeVanilla version: spongevanilla-1.12.2-7.1.10

**Issue Description**
There isn't a way to get item from block as middle button do.
![image](https://user-images.githubusercontent.com/19922286/76372682-2e778980-6379-11ea-8b58-022bbc1c2dee.png)
But the middle button can get the item correctly
![image](https://user-images.githubusercontent.com/19922286/76372710-3e8f6900-6379-11ea-82c5-16808d2114c0.png)

**Comment by dualspiral** [comment]
Huh, I already thought it was there! Well, it’s clear that’s what they want to do so it’s worth tracking it.

**Comment by SettingDust** [comment]
> Fair enough, I'll move this to the SpongeAPI repo then.

I just think it's a bug of `BlockType.getItem()`. My fault

**Comment by Picoseconds** [comment]
but that feature would be nice so please don't close

**Comment by gabizou** [comment]
> I just think it's a bug of `BlockType.getItem()`

It's not a bug of `BlockType.getItem` it's a missing location based property to be able to get from a position in the world. The reason why it's not on `BlockType` is because there's the "basic" item that a block can be represented as in the creative inventory, and then there's the location state aware item that would be otherwise presented as in the inventory (pick block).

**Comment by SettingDust** [comment]
@gabizou So, it my fault. Thanks

**Comment by Picoseconds** [comment]
but please add this feature of location based

**Comment by ImMorpheus** [comment]
Duplicate of https://github.com/SpongePowered/SpongeAPI/issues/1384
