### ISSUE TITLE
Account Documentation is unclear and contradictory

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/SpongeAPI#2121]
`Account#hasBalance` states:

https://github.com/SpongePowered/SpongeAPI/blob/79fb019bd6245e8415016dcfc71a75242f298f55/src/main/java/org/spongepowered/api/service/economy/account/Account.java#L93-L96

But `Account#getDefaultBalance` is contradictory:

https://github.com/SpongePowered/SpongeAPI/blob/79fb019bd6245e8415016dcfc71a75242f298f55/src/main/java/org/spongepowered/api/service/economy/account/Account.java#L137

https://github.com/SpongePowered/SpongeAPI/blob/79fb019bd6245e8415016dcfc71a75242f298f55/src/main/java/org/spongepowered/api/service/economy/account/Account.java#L126-L127

https://github.com/SpongePowered/SpongeAPI/blob/79fb019bd6245e8415016dcfc71a75242f298f55/src/main/java/org/spongepowered/api/service/economy/account/Account.java#L150

https://github.com/SpongePowered/SpongeAPI/blob/79fb019bd6245e8415016dcfc71a75242f298f55/src/main/java/org/spongepowered/api/service/economy/account/Account.java#L144-L145

Additionally it is not clear what `Account#getDefaultBalance` is used for:

https://github.com/SpongePowered/SpongeAPI/blob/79fb019bd6245e8415016dcfc71a75242f298f55/src/main/java/org/spongepowered/api/service/economy/account/Account.java#L79-L82

The doc states the default balance is used when _retrieving_ but does that mean it needs to be ignored during deposit/withdraw ?

Ex.
1. Default balance is 100
2. `Account` has no balance
3. Try to deposit 50. What's the expected result ? 50 ? 150 ?

**Comment by dualspiral** [comment]
This is an opinion, not a fact, and we need more people to weigh in on this. 

---

Based on the commit history:

https://github.com/SpongePowered/SpongeAPI/blob/79fb019bd6245e8415016dcfc71a75242f298f55/src/main/java/org/spongepowered/api/service/economy/account/Account.java#L126-L127

was an OCD fix and the rest was there before. I believe that this was added without thinking about the wider class.

Amusingly, I went to look at the two current implementations and they do different things:

* [TotalEconomy returns `ZERO` - i.e. follows the Javadocs to the letter](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/config/TEAccount.java#L150).
* [EconomyLite returns `getDefaultBalance()`, consistent with everything else the `Account` does.](https://github.com/Flibio/EconomyLite/blob/master/src/main/java/io/github/flibio/economylite/impl/economy/account/LiteUniqueAccount.java#L78-L83)

I expect that if you have a default balance of 100 spongeolians, it should become 150 spongeolians after depositing 50 spongeolians to an account with no balance (as opposed to a 0 spongeolians balance).

**Comment by ImMorpheus** [comment]
> Based on the commit history:
> https://github.com/SpongePowered/SpongeAPI/blob/79fb019bd6245e8415016dcfc71a75242f298f55/src/main/java/org/spongepowered/api/service/economy/account/Account.java#L126-L127
> was an OCD fix and the rest was there before. I believe that this was added without thinking about the wider class.

It wasn't.
The [commit](https://github.com/SpongePowered/SpongeAPI/commit/fc1c57803a130fd49d655cdc46cc37d2a6536535#diff-1f777496bd11eabe7792efa505366df4R119) you are referring to didn't change the structure of the comment.

https://github.com/SpongePowered/SpongeAPI/pull/995 is the original PR which added the Economy API.
https://github.com/SpongePowered/SpongeAPI/pull/995/files#diff-1f777496bd11eabe7792efa505366df4R119
That line was there since the beginning.


> This is an opinion, not a fact

This is what happening right now:

- `getBalance(Currency currency, Set<Context> contexts);` should return 0 when the account does not have a balance
- `getBalance(Currency currency);` should return `getDefaultBalance` when the account does not have a balance
- `getBalance(Currency currency);` is default implemented to return the result of `getBalance(Currency currency, Set<Context> contexts);`

One of them is wrong, they can't coexist. 
Even if we assume the jd is correct and the two `getBalance`s return different things, the default implementation of `getBalance(Currency currency);` would be wrong since it's not doing what the jd states. 
This is how the default implementation should be if we assume the validity of the jd:
```
default BigDecimal getBalance(Currency currency) {
    if (!hasBalance(currency)) {
        return this.getDefaultBalance(currency);
    }
    return this.getBalance(currency, this.getActiveContexts());
}
```

The current method is just calling `getBalance` (which, if implemented following the jd, should return 0).

> and we need more people to weigh in on this.

That was my intention for opening an issue instead of a PR. (I will add the proper label to make it more explicit).

**Comment by dualspiral** [comment]
> It wasn't.
> The commit you are referring to didn't change the structure of the comment.

Yup, must have looked at the wrong method in the base commit. Point taken. However, my opinion doesn't change based on my incorrect suggestion that it was the OCD commit. To clarify, I think the JDs are wrong on the `getBalance(Currency)` method - it makes no sense to have a default balance that is ignored in **one** method but not all the others.

I know I've pointed this out already, but it _is_ important to note that the two current implementations (that are well known) have done different things. My usual tactic with these sort of things is precedent - what has happened before. Well... that's out of the window here.

Your opinion is valid here too @ImMorpheus. I would also want to know what you think.

That said, to be brutally honest, the more I think about it, the more in favour I am of just making the change to the JDs to change `ZERO` to `getDefaultBalance` and closing this issue. I think it's an oversight and if you look at the rest of the interface, it's clear what the intention is. What's the point in having `getDefaultBalance` if the default is zero? Why does the non-contextual version have a different default to the contextual version? It does not make sense. 

If a project lead (@gabizou or @Zidane) agrees, let's just go ahead and do that.

Otherwise, I would like to put a time limit on this to stop this dragging on. Can I suggest we keep this open for about a week, and revisit this time next week? We might not get any comments, in which case we'll come to a decision then.

**Comment by ImMorpheus** [comment]
> Your opinion is valid here too @ImMorpheus. I would also want to know what you think.

I agree with your analysis. `hasBalance` and the rest of the interface were what lead me to believe the JD was wrong (and assuming it to be correct would lead to a wrong default implementation of `getBalance`).

> That said, to be brutally honest, the more I think about it, the more in favour I am of just making the change to the JDs to change ZERO to getDefaultBalance and closing this issue. 

+1

EDIT: for the implementation not following the JD we can open an issue when this has been sorted out.

**Comment by gabizou** [comment]
> let's just go ahead and do that.

^^^

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/d871149cbd3ca6004436e730419b58757affb1cd
