### ISSUE TITLE
[API-8] Commands - Support generic parameter validation

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/SpongeAPI#2156]
It would be nice to have some way of validating a parameter's output during argument parse time, rather than at execution time.

An example:
```java
Pattern nameRegex = Pattern.compile("^[a-zA-Z0-9]{2,32}$");

Parameter.string()
    .validate(name -> {
        if (!nameRegex.matcher(name).matches()) {
            // throw an exception maybe?
        }
    })
    .build();

**Comment by dualspiral** [comment]
Why not just create your own `ValueParser` to do that instead?

**Comment by dualspiral** [comment]
I've added this as a separate parameter, `VariableValueParameters#createValidatedStringParameter(Pattern pattern)`. The impl is something like this:

```
if (pattern.matcher(input).matches()) {
    return input;
}
// exception thrown here.
```

It will return a string. 

I do not want to add a generic "validate" to all parameters because that depends on parameters:

* parsing a string
* providing an appropriate point to hook into the system

It's not worth it with the number of caveats there will have to be. So, I'll add the validated string parser, but if you're wanting to create your own objects via a parser, you're better off just writing the value parser yourself.
