### ISSUE TITLE
Location issues with getExtend()

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeAPI#2196]
As of SpongeAPI 7.2.0, Location is a bit over-complicated to use with getExtend().
1- the documentation doesn't make sense:
The note says the return value can be null if the Extent is unloaded and garbage collected.
The final comment says it throws an exception when Extend is null.
Implementation is actually throwing exception and, by extension, will never return null.
=> please pick one

2- there's no way to check if the extent is null, so we're forced to use a try/catch instead of a simple null check. In other words, we can't use getExtent() in a conditional expression.
=> please return null or provide an hasExtent/isExtendLoaded() method

Another thing to consider is whether we really need the Extend to be loaded. For example, if location is a player back location in another dimension, I don't see why the Location would become invalid because the world is unloaded. Right now we need to redefine our own localization object. I would prefer something like Nucleus internal NamedLocation object:
- getExtend() returns Optional only set when world is loaded, (or just gets marked as deprecated in favor of the new API?)
- loadAndGetExtend() has an helper to load the extend or throws an exception if it has no UUID
- getExtendUUID() returns the Optional a UUID to save the Extend reference on disk and reload it later on
- constructor would accept ExtendUUID to reload the location

**Comment by dualspiral** [comment]
1- dealt with. An unloaded world or extent will throw an exception.
2- I'll add `isAvailable` (which will map to what API 8 will offer).

> For example, if location is a player back location in another dimension, I don't see why the Location would become invalid because the world is unloaded.  Right now we need to redefine our own localization object.

It will change for API 8. See [Location](https://github.com/SpongePowered/SpongeAPI/blob/api-8/src/main/java/org/spongepowered/api/world/Location.java) and [ServerLocation](https://github.com/SpongePowered/SpongeAPI/blob/api-8/src/main/java/org/spongepowered/api/world/ServerLocation.java). 

However, for 7, because of how it's been done, we can't really change how this works now. We cannot add UUID based methods because the location doesn't necessarily operate on a `World`, but an `Extent`. The new location objects will operate on worlds and will resolve this issue.
