### ISSUE TITLE
Player#getLocale returns incorrect values

### ISSUE THREAD

**Issue by Iltotore** [SpongePowered/SpongeAPI#2255]
The title says all. When  I get my own locale using Player#getLocale, it returns `en_US` (server default) instead of `fr_FR`, my client language.

I'm using SpongeForge 1.12.2-2838-7.3.0

[Javadocs](https://jd.spongepowered.org/7.2.0/org/spongepowered/api/command/CommandSource.html#getLocale--) don't tell about this possible feature so I think it's a real issue.

**Comment by dualspiral** [comment]
Javadocs do say something about it (though there is a typo, which I'll correct to make it sensical):

> If this CommandSource does **not** have a Locale configured or does not support configuring a Locale, Locales.DEFAULT is used

That's what you're seeing. You've said nothing about when you're checking this - for example, the locale is NOT available during player join. This is also not a SpongeAPI issue, this would go on SpongeCommon.

I'm closing this because a) this is the wrong repo and such a ticket would need to follow the template on the appropriate repo and b) it's doing what it's supposed to do - if the client hasn't yet (or ever) reported the locale, there is _nothing_ we can do about it and we fallback to the default.

**Comment by Iltotore** [comment]
Okay, but what about after joining ? It still returns the default Locale when I'm ingame (and I re-call Player#getLocale)
