### ISSUE TITLE
Drop some method prefixes

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#2276]
I propose that we drop some method prefixes (drop `get` and `set`, but keep `with`) in the API for the following reasons:
- `get`/`set` prefix for everything is useless noise - use it where it makes sense - for example:
  - `registry.get(key)`
  - `state.get(property)`
- many other projects have either completely dropped the prefixes,or are not using them for new things - for some examples:
  - Adventure 4+: no prefixes
  - Configurate 4+: no prefixes
  - JDK: see [Java 11's `HttpResponse`](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpResponse.html#method.summary) for an example
- it makes reading code a lot cleaner as well - compare these examples:

Without `get` prefixes:
`player.inventory().hotbar().selectedSlotIndex();`
`player.serverLocation().world().chunk(0, 0, 0).block(0, 0, 0);`
`game.server().worldManager().worlds();`

With `get` prefixes:
`player.getInventory().getHotbar().getSelectedSlotIndex();`
`player.getServerLocation().getWorld().getChunk(0, 0, 0).getBlock(0, 0, 0);`
`game.getServer().getWorldManager().getWorlds();`

**Comment by Zidane** [comment]
Personally I approve this change and the registry changes coming are going to make dropping prefixes that aren't needed all the more important.

**Comment by zml2008** [comment]
I'm in favor of this -- what I've gone with in Configurate is only using `get/set` to refer to the operation of extracting or inserting a value in a container (so I have `get`, `set`, `getList`, `setList`, and such in `ConfigurationNode`) and dropped their usage everywhere else.

While this does make things a little more awkward for our Kotlin users, it's not a huge difference, and either way I'm not a huge fan of changing API design for a different programming language.

**Comment by dualspiral** [comment]
In what will be no surprise to some people, as a matter of preference, I disagree with this change in general. I am very much in the camp of using `get`/`set` when you are getting or setting something and I don't think it reduces visibility or readability at all. I'm not 100% against dropping every prefix, but in an API, the method name is part of the documentation and `get`/`set` aids that.

I've said it on a different issue, but I'll say it here as well - my preferences:

* Verbosity over brevity: a method name should be clear as to its function - often using verbs to provide the action (for example, I prefer the use of get, set, with etc.).
* Distinctiveness: two methods on the same object that do not do the same thing should not be named the same thing.

The only real place that I've not followed this so much is the builder pattern, where I've not used a `add` prefix for methods that add an. I've still added `set` to methods where the incoming value replaces something else - that is incredibly important - the verb sets the context of the value. I would not be upset if we were to add the `add` prefix!

The argument that "others do it, so we should too" is weak and I've never liked it. We should never be beholden to what a library does, we are our own project and we need to decide what's best for us and our users. 

Not written here but has been mentioned in the past: I also dislike the argument that "it saves characters" - we use IDEs and we're going to press tab more often than not. I can kind of see the whole "you'll get to what you want quicker if you don't have to type `get` first", but most IDEs will account for `get`/`set` if you start from the bit after anyway.

Am I going to lose sleep over this? No. There are far more important things to be worrying about. However, I don't think this is necessarily the right thing to do and thus I am making the comment here.

**Comment by dualspiral** [comment]
I had a shower thought. How would this handle, for example, `World#getBlock` and `World#setBlock`?

In API 7 we have on `World` (via the interfaces it extends):

* [`BlockVolume#getBlock(int, int, int)`](https://jd.spongepowered.org/7.3.0/org/spongepowered/api/world/extent/BlockVolume.html#getBlock-int-int-int-)
* [`Extent#setBlock(int, int, int, BlockState, BlockChangeFlag)`](https://jd.spongepowered.org/7.3.0/org/spongepowered/api/world/extent/Extent.html#setBlock-int-int-int-org.spongepowered.api.block.BlockState-org.spongepowered.api.world.BlockChangeFlag-)

Ignore that there are API 7 methods, because the premise is the same. The naming scheme dropping `get` and `set` generally relies on the fact that it's clear from the parameters what is going on - the getter would have no parameters, the setter would have one. In this case, that is not the case. And while, yes, one could look at the return type - developers, including myself, don't tend to do so as a first port of call. Similar story with the parameters.

Would the consensus be to add `get` and `set` prefixes here? I'm more against stripping the prefixes in this scenario because the defining factor of whether it has a parameter or not is gone - I see the argument where it's `Blah blah()` and `void blah(Blah)` (though I disagree), but not in this scenario. Yes, you could say "but the one with `Blah` is clearly the setter, duh", but that requires more thought. 

Regardless of what happens, we need to keep things clear and not make a sweeping change that hurts the users of the API. To that end, I'd be interested to see what consumers of the API, rather than us writers of the API, think. This is a large change and I think _they_ need to weigh in before any decision is made. I can adapt and use what's handed to me. How do they feel?

**Comment by alexstaeding** [comment]
I generally agree with @dualspiral on this; Most of the time, dropping a tiny three-character prefix doesn't make sense.

This is especially true in cases where both the accessor and mutator are present. Methods are always actions and their names should reflect this. The missing distinction between different actions hurts discoverability and clarity. In my opinion, something like this should really be avoided:

```java
Bar bar = foo.bar();
foo.bar(bar);
```

That being said, I do think that it is sometimes valid to drop the verb-prefix on a method name when dropping this prefix does not lead to identically named methods that act differently on the same property. Examples of this are:
- As mentioned in dual's first comment on this issue, the builder pattern: There's no need to prefix "add" if it's the only thing you can do.
- Simple getters for final properties. The only issue I see with this is if a class has some prefixed and some non-prefixed methods. The style within a class should stay the same.

I believe leaving the verb-prefix will always be a safer and clearer option. I would only remove the prefix in cases where it is certain that a conflicting method name will not be added in the future.

Especially after reading the example in dual's second comment, you definitely don't want multiple identically named methods that differ so drastically in action where the only outward distinction is a small change in parameters.

**Comment by tyhdefu** [comment]
I can see the argument for this style but I don't think it fits well in the Sponge API. If I take a look at the main plugin I write, it very rarely chains as many calls together as you are showing in your example. This is for API 7.
A couple of the longest chains I have are:
`Sponge.getServer().getConsole().getMessageChannel().send(Text.of(id + " " + ids.length));`

This **gets** the server, and it throws an exception if its not available. I feel that if the method was named .server(), it would always be available, and should never throw an exception. I think .console().messageChannel() would be a bit cleaner however.

`block.getExtent().getBlock(x, y, z)`.

Again, both, .getExtent() and .getBlock() having makes me think that they are doing more than just field access. .getExtent() (in api 7) throws an exception if its unloaded, and .getBlock() throws an exception if its out of bounds in the given extent.

The only times I chain calls is usually in builders. When im working with inventories I usually need to keep hold of the reference to the inventory for something like checking they have an item before removing it, or checking if they have space before giving them an item.

I think setters using this pattern is straight up terrible because I would not expect that doing something like block.blocktype(BlockTypes.AIR) ends up setting the block immediately and causes lots of block updates. If something has side effects it should be prefixed with `set`. In builders its very logical to not use .set because you're building an object with a .blockType(BlockTypes.AIR), and that has no side-effects and is very likely to be chained.

I think a lot of methods can throw exceptions if they are not done on the main thread, so acting as if its a simple field access when infact it does a lot more is confusing and misleading.

Another minor detail is that I sometimes start typing (.set or .get) and that limits the results when im unsure exactly what I want to set is called. Dropping the prefixes could double the amount of methods I need to sift through to find the method I want.

**Comment by ryantheleach** [comment]
I know I've been largely absent, but as someone who started on Java and went to C#, Knowing the context of properties with behavior behind them and fields, was a constant irritation compared to Java conventions of having getters and setters, to the point where I had to install custom IDE extensions to color them differently to cope.

The way languages such as Kotlin avoid such irritation, is clever class design, meaning that 'data classes' are treated differently, and you usually understand when you are dealing with a data class / builder, vs an API service or actor-like object.

I agree that Java is trying to move their library design to more closely mimic these other languages, but without 'true' properties (using assignment to run hidden logic on property change, and having field accessor notation for getters, along with the IDE support to differentiate them) I believe it's ultimately flawed in terms of usability, as it will present a very similar issue in that Properties will be confused with Methods.

Although, many other languages have succeeded against similar inconvenience, by having highly disciplined libraries and conventions, 

As for the specific example of HTTPResponse, it's quite clearly modelled as an immutable data class / record. It has a single purpose, to group data.

Adventure also largely seems to concern itself with building up and manipulating various data classes, using chained builders.

These largely feel like very narrow situations where you could feasibly drop the prefixes for convenience, But I worry what the on-going usability effects would be for an API as large as Sponge, crafted over time, with more authors. There are certainly *areas* of SpongeAPI that could benefit, But I then worry about consistency, backwards compatibility, maintenance arguments as people switch them back and forth, docs, and budding programmers who are trying to make plugins as their first projects.

So whilst I'm against it, since Sponge API8 uses both Configurate, and Adventure, it feels inevitable that we should concede *some* of the prefixes for consistencies sake, since both Configurate and Adventure are being used outside of Sponge, and Sponge's chained builders have **already** dropped the prefixes.

Maybe we could break this into parts, and examine it system by system? e.g. try it out on all the events first.
