### ISSUE TITLE
Optional usage in API

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#2366]
Since the beginning of SpongeAPI, we have been a heavy adopter of `Optional`s throughout our codebase, and it has worked well for us... but not everybody shares the same love for `Optional` as we do.

At this time, we are interested in hearing from the community whether they like the use of `Optional` in SpongeAPI, or if the community would rather they be replaced with `@Nullable` values.

A few helpful references:
- https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html
- https://homes.cs.washington.edu/~mernst/advice/nothing-is-better-than-optional.html
- https://stackify.com/optional-java/

The replies to this post will be evaluated by the leadership of Sponge to determine if a change should be made to this policy. We ask for one reply only, we appreciate that this could be a healthy debate but we want to gauge individual view points. Regardless of being for or against the change, we ask people to give us their thoughts below. We ask for everyone to be respectful.

If Optionals are determined to be removed, the change will occur **before API-8 is frozen**. Leadership is fully aware that API-8 is semi-frozen currently but we have no interest in triggering the massive plugin breakages that occurred from API-7 to API-8 for API-9 and therefore this sort of change needs to be evaluated now.

We apologize for the inconvenience but we felt the best way to help with this decision was to find out what our community wants, to hear your voice on this matter.

PS Please do not react to this post or any replies, they will have no bearing on a decision, one way or another, and will be ignored.

**Comment by mosemister** [comment]
Personally I rather Optional then @nullable. While sure I could just make the @nullable a Optional with ``Optional.ofnullable`` its not quite the same as just being handed it. 

I personally prefer Optional due to the mapping, default (orElse), etc, but it ties into the more modern Java tropes such as Stream. 

Not only that but IDEs that don't support the checking and warning of nullable may discorage newbies to Sponge as they keep getting null references. While there is the question of why they don't move to one that does support it, one thing I have found is people will stick with what they like.

**Comment by astei** [comment]
Uninvolved observer looking in (but one who's had to face this question before). I generally believe that using nullability annotations are the better move in almost every case, _at least for now_. I'm qualifying this because Mojang has given every indication they wish to aggressively utilize new Java features, and given the future evolution of the Java programming language, it is evident that `Optional` is the desired way for new code to indicate the potential absence of a value, but nullability is likely to persist due to the sheer weight of strong backwards compatibility that Java is known for. However, in my opinion, Java currently lacks the features (mostly this would be lightweight value types, being developed in Project Valhalla) that would truly make `Optional` superior to nullability, so my vote is to "use nullability annotations, but re-evaluate each major version."

The only benefit of `Optional`, as of now, is that it can make for more fluent code - but if this is essential to a user, there's always the option of using `Optional.ofNullable()` to wrap the return value. Even considering this, there are better solutions out there - consider [JavaScript optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) or [Kotlin's safe calls](https://kotlinlang.org/docs/null-safety.html#safe-calls).

@mosemister 

> I personally prefer Optional due to the mapping, default (orElse), etc, but it ties into the more modern Java tropes such as Stream.

While using `Optional` can make for more fluent code, `Optional` still retains many of the same pitfalls as null values. Now, if Java had lightweight value types and `Optional` was one of those types, I'd have a very different opinion if applied to modern code targeting a modern version of Java.

> Not only that but IDEs that don't support the checking and warning of nullable may discorage newbies to Sponge as they keep getting null references.

The point of the nullability annotations is to point out to the IDE (and the user) that the method may return a `null` reference. In my opinion, an IDE that does not report these sorts of errors to the user is itself faulty.

**Comment by tyhdefu** [comment]
I am in favour of Optional rather than @Nullable
This is mainly because of all the utility methods it provides and the explicit clarity provides is worth a lot.
Additionally, I have had wrong assertions with the nullability framework. Especially with minecraft, it does not properly annotate its methods/fields which causes incorrect assertions that something cannot be null. I don't know whether the nullability framework is able to guarantee this using some sort of compile-time checker, but atleast for minecraft, it seems to have failed.

The utility methods on Optional are not always useful / needed, but when they can be used, they normally provide a huge improvement.
Even more useful methods have been added in Java 9. I think it would be a shame to drop Optional just as we unlock access to more of its methods. (Also note that the link to the Optional documentation in the original post is java 8, and 1.16 support java 16 and then in 1.17 java 16 is the standard).

For example, .or() which takes a supplier to another optional, can be chained as many times as wanted to make far cleaner code - I personally have seen autocompletions for or() and found it as the ideal thing to use, only to realise I was on java 8.
Also added are:
.stream(), ifPresentOrElse(), and orElseThrow() with no-args to explicitly say you are making an assertion, which removes the Optional.get() before .isPresent() warning.

I also think that it is easier to opt-out than opt in. For example, a chained: `apicall.orElse(null);` vs a wrapping Optional.ofNullable(...). Chaining is always better than wrapping in my opinion.

To finish off, here is a code snippet from something that I've done a good few times, an argument or raytrace.
Without Optional (8 lines):
```java
ServerLocation serverLocation = ctx.one(BLOCK);
if (serverLocation == null) {
    Player player = ctx.cause().first(Player.class);
    if (player == null) {
        throw new CommandException(Component.text("You must provide a block or be a player to use this command!"));
    }
    serverLocation = raytraceEntity(player);
}
```       
With Optional (6 lines), java 8
```java
final ServerLocation icLocation = args.one(BLOCK).orElseGet(() -> {
    return src instanceof Player ? rayTraceEntity().orElse(null) : null
});
if (icLocation == null) {
    throw new CommandException(Component.text("You must provide a block or be a player to use this command!"));
}
```

With Optional (3 lines), java 9+
```java
final ServerLocation serverLocation = ctx.one(BLOCK)
        .or(ctx.cause().first(Player.class).flatMap(this::raytraceBlock))
        .orElseThrow(() -> new CommandException(Component.text("You must provide a block argument or be a player and ray trace to use this command!")));
```
Also note that in the first case, it prevents the variable from being `final`. You could make it so that it was final but it would increase the line length, and so i've not done that.
I also *strongly* believe that the third option is far easier to read, it almost reads like plain english, get a parameter, or raytrace, otherwise throw an exception. And furthermore, this is just a single .or(), you can have as many as you like!

**Edit**: .or() takes a supplier, so example 3 with java 9 and optional should be:
```java
final ServerLocation serverLocation = ctx.one(BLOCK)
        .or(() -> ctx.cause().first(Player.class).flatMap(this::raytraceBlock))
        .orElseThrow(() -> new CommandException(Component.text("You must provide a block argument or be a player and ray trace to use this command!")));
```
This means that the ray-trace is lazily evaluated. This would have been a compile time error, and forced me to use a supplier correctly. Apologies for any confusion caused by this.

**Comment by astei** [comment]
@tyhdefu

> I don't know whether the nullability framework is able to guarantee this using some sort of compile-time checker, but atleast for minecraft, it seems to have failed.

Actually, the "nullability framework" does not exist in base Java. You have to use external tools to check if the nullability contract is being followed, such as [Checker Framework](https://checkerframework.org/) or [Uber's NullAway](https://github.com/uber/NullAway/). My understanding is that systems like these are rarely, if ever, used in the ecosystem.

But going back to the internals of the server not using nullability annotations, that is a separate issue from the Sponge API using nullability annotations or not. This is not an argument for not using nullability arguments, it is simply evidence that Mojang does not pay careful attention to code quality, and whether or not they use `Optional` or nullable values plays no role in that. (Quite the opposite: there are many ways to improperly use `Optional`!)


As for fluency, I'm led back to the question of language support for richer support of nullable types. Your example can be turned into a Kotlin one-liner, like so:

```kotlin
  val serverLocation = (ctx.one(BLOCK) ?: ctx.cause().first(Player.class::java))?.let { rayTraceEntity(it) }) ?: throw CommandException(Component.text("You must provide a block argument or be a player and ray trace to use this command!"))
```

**Comment by astei** [comment]
@tyhdefu

> I don't know whether the nullability framework is able to guarantee this using some sort of compile-time checker, but atleast for minecraft, it seems to have failed.

Actually, the "nullability framework" does not exist in base Java. You have to use external tools to check if the nullability contract is being followed, such as [Checker Framework](https://checkerframework.org/) or [Uber's NullAway](https://github.com/uber/NullAway/). My understanding is that systems like these are rarely, if ever, used in the ecosystem.

But going back to the internals of the server not using nullability annotations, that is a separate issue from the Sponge API using nullability annotations or not. This is not an argument for not using nullability arguments, it is simply evidence that Mojang does not pay careful attention to code quality, and whether or not they use `Optional` or nullable values plays no role in that. (Quite the opposite: there are many ways to improperly use `Optional`!)

> I also think that it is easier to opt-out than opt in. For example, a chained: apicall.orElse(null); vs a wrapping Optional.ofNullable(...). Chaining is always better than wrapping in my opinion.

This is not a opt-out - you are still paying the cost of the `Optional` wrapping either way. If I don't want to use `Optional`, I should ideally not be forced to pay that cost upfront.

**Comment by alexstaeding** [comment]
I personally would really like to see Sponge moving from Optionals to Nullable types. [Velocity](https://github.com/VelocityPowered/Velocity) has also already made this move.

I may be slightly biased as a Kotlin user, where you can write functional-style code directly with nullable types as opposed to Java. In the cases where you *do* need functional-style code in Java, it's relatively easy to wrap the return type with `Optional.ofNullable()`.

**Comment by Logiquo** [comment]
I personally prefer `Optional`. Notice that @Nullable is not supported by all IDEs; and since it is not enforced in the base Java, people could just simply ignore it, which makes the @Nullable contract useless. In the contrast, `Optional` makes it clear that a `null` value may exist.

**Comment by shinyafro** [comment]
I personally wish to see nullables. As we move java up in version it's actually going to be a lot easier to deal with nulls, especially in java 16 since you can use an instanceof to check for null and assign the type in one expression basically, which means you can use it as a null coalescing operator of sorts in theory from what I understand. Also they tend to be placed in the most annoying of locations. I would not mind if we had two methods one that returns  the value as-is and one that then wraps it. As long as we have choice but a lot of the time they are placed in locations that make 0 sense. Great usage for optional is the command package where you can just throw right in there and it sends to the player a message.

**Comment by Yeregorix** [comment]
I have a love-hate relationship with Optionals. I use them to declare methods return type but almost all my calls are followed by `orElse(null)` because I hate to have it in a variable. Additionally, I avoid using Optionals in certain critical performance paths.

> Notice that @nullable is not supported by all IDEs

Examples? Also you can still use annotation processors at compile-time without any IDE.

> With Optional (3 lines), java 9+
> 
> ```java
> final ServerLocation serverLocation = ctx.one(BLOCK)
>         .or(ctx.cause().first(Player.class).flatMap(this::raytraceBlock))
>         .orElseThrow(() -> new CommandException(Component.text("You must provide a block argument or be a player and ray trace to use this command!")));
> ```
> 
> Also note that in the first case, it prevents the variable from being `final`. You could make it so that it was final but it would increase the line length, and so i've not done that.
> I also _strongly_ believe that the third option is far easier to read, it almost reads like plain english, get a parameter, or raytrace, otherwise throw an exception. And furthermore, this is just a single .or(), you can have as many as you like!

This third example doesn't exactly behave like the first one. `raytraceBlock` may be evaluated when it is not needed. Execution order is different and performance impact is different. In some situations it is negligeable, in others it is not.

This brings me to the performance drawbacks of Optionals:
- extra object allocation
- extra method calls
- unnecessary expression evaluation

As I said before it is clearly negligeable in most situations and can be a price to pay to improve code quality.

Some people find `Optional` methods chains to be more easy to read. This is totally subjective, personally I think the opposite way.

**Comment by shinyafro** [comment]
Seeing your edit, I will say if we are using Java16 anyway and have the new cast system you can have it final in 4 lines, Someone might be able to do better but in theory it will compile, since as I said in my previous post you can use an instanceof check as a null check which should in theory be able to assign to a variable just like any other instanceof assign statement
> **Edit**: .or() takes a supplier, so example 3 with java 9 and optional should be:
> 
> ```java
> final ServerLocation serverLocation = ctx.one(BLOCK)
>         .or(() -> ctx.cause().first(Player.class).flatMap(this::raytraceBlock))
>         .orElseThrow(() -> new CommandException(Component.text("You must provide a block argument or be a player and ray trace to use this command!")));
> ```
> 
> This means that the ray-trace is lazily evaluated. This would have been a compile time error, and forced me to use a supplier correctly. Apologies for any confusion caused by this.


```java
final ServerLocation serverLocation;
if (ctx.one(BLOCK) instanceof ServerLocation blockLoc) serverLocation = blockLoc;
else if (ctx.cause.first(Player.class) instanceof Player p && raytraceBlock(p) instanceof ServerLocation blockLoc) serverLocation = blockLoc;
else throw new CommandException(Component.text("You must provide a block argument or be a player and ray trace to use this command!"));
```

**Comment by octylFractal** [comment]
@shinyafro You _cannot_ use an `instanceof` pattern to do a null-check on the same type, https://gist.github.com/octylFractal/4f7508de417791eb1dd2551c7a44cff3 will fail with:
```java
InstanceofPatternNullCheck.java:3: error: pattern type String is a subtype of expression type String
        if (myFunction() instanceof String foo) {
                         ^
1 error
error: compilation failed
```

However, all hope is not lost for succinct pattern code if `Optional` is left in! Project Amber will likely introduce [static patterns](https://cr.openjdk.java.net/~briangoetz/amber/pattern-match.html#static-patterns), so your example could be written as:
```java
final ServerLocation serverLocation;
if (ctx.one(BLOCK) instanceof Optional.of(ServerLocation blockLoc)) serverLocation = blockLoc;
else if (ctx.cause.first(Player.class) instanceof Optional.of(Player p) && raytraceBlock(p) instanceof Optional.of(ServerLocation blockLoc)) serverLocation = blockLoc;
else throw new CommandException(Component.text("You must provide a block argument or be a player and ray trace to use this command!"));
```
It's a little more wordy, but it's got the spirit! I think I would agree with @astei here, 
> my vote is to "use nullability annotations, but re-evaluate each major version."

Edit: adding a variant of the pattern matching using `switch` instead, which is even better at solving this fluently:
```java
final var serverLocation = switch (ctx.one(BLOCK)) {
  case Optional.of(var blockLocation) -> blockLocation;
  default -> switch (ctx.cause.first(Player.class)) {
    // There might be a more optimal way to write this, but I don't think the syntax for joined patterns is finalized yet
    case Optional.of(var player) && raytraceBlock(player) instanceof Optional.of(var blockLocation) -> blockLocation;
    // You might need a block here? I think a special exception was added for `throw` in switch expressions.
    default -> throw new CommandException(Component.text("You must provide a block argument or be a player and ray trace to use this command!"));
  }
};
```

**Comment by Andre601** [comment]
I never had that much to do with Optionsl, but from what I worked with was it not that bad of an experience.
In fact it either wss the same (i.e. returned also null as default) or (which I hate more) required me to add an extra if just to check for nullability.

Here is an example of how switching from optional to nullable made code larger, even if it was just 2 lines:
```java
// Old

// Returns a non-null default object
SomeObject object = SomeClass.get("key");

SomeUtil.handleObject(object);

// New

// Returns a nullable object
SomeObject object = SomeClass.get("key");

if(object == null)
    return;

SomeUtil.handleObject(object);
```

While some see this as not that bad, aka. "It's just 2 extra lines to add", is it for me already bloat.

So I suggest to stick with optionals, if they return non-null default objects.

**Comment by dscalzi** [comment]
Just a quick note, I much prefer Optionals when working with streams or functions that are intended to be used in streams. They're really nice to work with in these scenarios because their structure supports the chained functional call layout.

For general utility calls i do prefer a nullable value and a doc which says when this function returns null. Often times in these scenarios i just call the function and do an .orElse(null) call because I don't want to deal with the optional semantics.

So overall it depends on the usage, i wouldn't do a blanket policy that all functions must or must not use optional return value.

**Comment by Katrix** [comment]
From a Scala perspective. I'd love to keep `Optional`. Scala IDEs don't support `@Nullable`, and neither does the Scala 3 compiler AFAIK. IDEs I assume because everything is assumed to be non null, so the worth of adding the feature wouldn't be much. For the Scala 3 compiler it's because it treats everything from Java as nullable. Instead `@NotNull` and similar is what changes behavior for the Scala 3 compiler. If Sponge went and added `@NotNull` to all methods that don't return null (no tricks to add it to packages don't count, and are not detected), then I might be on board, but otherwise for me personally it's a pretty hard no.

As it is currently I don't need to check the annotations on the method, or check the JavaDocs to see if it returns null. With `@Nullable` I do.

**Comment by XakepSDK** [comment]
I'm pro optionals.

Annotations are just metadata, meanwhile Optionals are API hard-requirement. Everybody is free to add or remove annotation, but you can't add or remove Optional return type. It will be breaking change.

Contributors with direct access and without may forget to add them. Plugin developers will ignore or miss all warnings in IDE.

Sponge implementation is high quality and almost never returns nulls when return type is non-optional. When i deal with Sponge API, i feel safe, because nulls never returned. Annotations will not give me same confidence.

**Comment by astei** [comment]
> Annotations are just metadata, meanwhile Optionals are API contract

Annotations like `@Nullable` are very much part of an API contract. I don't get your argument.

**Comment by XakepSDK** [comment]
Re-worded it. What everything else in my comment except 2nd sentence?

**Comment by Pulverizer** [comment]
> I'm pro optionals.
> 
> Annotations are just metadata, meanwhile Optionals are API hard-requirement. Everybody is free to add or remove annotation, but you can't add or remove Optional return type. It will be breaking change.
> 
> Contributors with direct access and without may forget to add them. Plugin developers will ignore or miss all warnings in IDE.
> 
> Sponge implementation is high quality and almost never returns nulls when return type is non-optional. When i deal with Sponge API, i feel safe, because nulls never returned. Annotations will not give me same confidence.

I agree.

**Comment by AuroraLS3** [comment]
I'm a big fan of Optional. I'm also a fan of the nullability annotations, since both help avoiding NPEs.

When reading code in a non-IDE environment like PRs and documentation, Optional makes it very clear that a method might return nothing. Annotations on the other hand need to go to the code - or requires paying more attention when writing documentation to make sure that the nullability contract comes across to the reader.

Consider clarity:
```java
// Optional
Optional<Thing> thing = findThing();
Thing thing = findThing().orElse(backupThing);
Thing thing = findThing().orElseThrow(() -> new IllegalStateException());

// Nullability annotations
Thing thing = findThing();
thing = thing != null ? thing : backupThing;
if (thing == null) throw new IllegalStateException();
```
With nullability annotations a null comparison is necessary for conveying the nullability contract outside of the IDE.

**Comment by LemADEC** [comment]
As a java developer, `Optional` helps in some cases, but it doesn't prevent you to make the same mistake. In other cases it adds clutter more than anything. It's more of a coding style preference, something we can discuss endlessly with no universal answer.

As server owner, from a performance stand point, we shouldn't use `Optional`. SpongeForge is getting better but it's still a bit laggy, so anything that can help improve speed, I'll take it.

Now, if I take a bit of distance, Optional and nullability annotations are just "Syntactic sugar" or workaround as in they don't really address the root cause : null are evil (ask the guy who invented it). So, how many such Optional/Nullable are in the API ? how many could be changed to NotNull ?

**Comment by Iltotore** [comment]
## For Optionals
As a Java and Scala developer, `Optional` is a good, functional way to handle nullabillity. Even if Java isn't actually that "functional", Optionals, Monads are still useful in big programs/API like Sponge:

Example:
```java
Optional<ItemStack> hand = Sponge.getServer()
  .getPlayer("Il_totore")
  .flatMap(ArmorEquipable::getItemInHand);
```

I'm a big fan of monads and I think Sponge should keep using them. It's actually a big argument to use Sponge.

## Against the NotNull Annotation
`@Nullable` creates an assertion and throw an IllegalArgumentException but generally we don't want our program to create a runtime, unexpected exception. In [functional error handling](https://docs.scala-lang.org/overviews/scala-book/functional-error-handling.html), we want a monad, for example en Either, an Optional, to manage unexpected cases better.

What if we have multiple `IllegalArgumentException` ? How can I know which value didn't pass without making:
```java
try {
  something(a);
} catch(IllegalArgumentException e) {
  //Handle illegal value
}

try {
  something(b);
} catch(IllegalArgumentException e) {
  //Handle illegal value
}

try {
  something(c);
} catch(IllegalArgumentException e) {
  //Handle illegal value
}
```


To conclude, I think Sponge __should__ continue to keep Optionals and monads for their API as it's becoming more and more popular in the Java ecosystem (Vavr, Akka, Java 16 etc...)

**Comment by pie-flavor** [comment]
Everything I'd say has been said (by pro-Optional people). So instead I'll respond to a couple of other things that have been said.

* Regarding that Optionals do not prevent you from making the same mistakes: You can throw the same exception by calling Optional#get. But, importantly, you know you're doing it when you're doing it. Null tracking simply can't be perfect without it being part of the type system, and so what's an explicit "I know what I'm doing" with Optional becomes very possibly implicit. Furthermore, this exception gets thrown at the #get() call-site, rather than waiting until you try to fetch a member; with Optional you can never find yourself wondering where e.g. a null element of a list came from.
* Regarding that Optional could be a performance issue: I would bet money that this is a drop in the bucket. Minecraft already uses loads of ResourceLocation, BlockPos, etc. They don't swamp performance because the JVM is smart and won't allocate if it doesn't need to.

**Comment by shinyafro** [comment]
for something like an int you're looking at a 10x memory footprint increase due to the fact it is being double boxed (Optional, then Auto-boxed primative for generics) for instance, so the performance reasoning can be quite there. Until valhalla drops reference types will be a persistent issue. No real chances of it hitting in  J17 either, which is LTS. Feature frozen currently iirc. My main issue with optionals is they seemingly just get used for everything, like when you use optionals for itemstacks you got to be scratching your head since if it's null just return an empty item stack? When getting nbt why does getOrCreate return an optional? Sometimes core game systems are optional like the game can physically boot without them and honestly I don't get why we can't just have a method appended with "OrNull" and then have another one in the API that wraps that in a nullable. The service provider does this nicely where you can provide unchecked or get an optional, not sure why we can't do this for other key areas. Honestly sometimes i will just use the forge API to avoid optionals simply because they make things so much less concise. Infact, that may be the meta whenever spongeforge ever comes out since we can just use an instanceof to check for null while casting to sponge at the same time, without having to worry about boxing.

**Comment by XakepSDK** [comment]
What is double boxed? I don't understand. Optional has variants for primitives.

**Comment by shinyafro** [comment]
Even without double it's about  4-5x more of a footprint. A lot of developers already complain about blockpos and the likes, we even have fastutils to go to far lengths to avoid boxing. To say boxing is not a performance concern is a bit silly.

**Comment by Katrix** [comment]
If you're have an Nullable int, then that int is already boxed, and the performance has already been paid. Adding Optional to that is not that much more expensive, and as said, if you use on of the primitive variants, it might even be LESS expensive.

**Comment by shinyafro** [comment]
An int can just have a value that is indicative of undefined or null, or rather it has to since you can't really null a value type since how would you even? Also more importantly, now that it is a reference now the GC has to keep track of it since we don't know how many references this value has, whereas before it could only possibly be one.

**Comment by LemADEC** [comment]
Since ItemStack.EMPTY was added to the base game (or is it just in forge?), could we update the API so Sponge doesn't allocate an optional when returning an ItemStack? Could we use similar schemes on other objects to simplify and reduce GC impacts?

**Comment by pie-flavor** [comment]
> An int can just have a value that is indicative of undefined or null, or rather it has to since you can't really null a value type since how would you even? Also more importantly, now that it is a reference now the GC has to keep track of it since we don't know how many references this value has, whereas before it could only possibly be one.

If there were anything *more* liable to cause bugs than null, it would be such 'indicative' values. At least nulls have IDE-checked annotations at all.

**Comment by shinyafro** [comment]
> > An int can just have a value that is indicative of undefined or null, or rather it has to since you can't really null a value type since how would you even? Also more importantly, now that it is a reference now the GC has to keep track of it since we don't know how many references this value has, whereas before it could only possibly be one.
> 
> If there were anything _more_ liable to cause bugs than null, it would be such 'indicative' values. At least nulls have IDE-checked annotations at all.

Usually it makes sense though and is documented in the return. There will always be a performance vs developer usability trade-off I guess but I don't see the issue with reading the docs, while a method name may make sense to use you never know if it does something completely different upon inspection. In the case of something like NBT you could easily just have a method that returns a supplied default for example upon finding no value which a few mods quite often do already anyway.

As I said previously, my main concern with optionals is they get over used to the point where there is no codepath that it would return an Optional.Empty, or the object it is returning has a representation that is empty. Like I said, the item stack being a key example, size 0 or of type air with the isEmpty() method simplifying the check, or the getOrCreate method would be another example where it should be throwing an exception instead of returning an empty optional since failing to do so indicates something exceptional has happened, as it not only has failed to get , but also create nbt data for the item.

**Comment by Iltotore** [comment]
> for something like an int you're looking at a 10x memory footprint increase

**x10** memory footprint for a single wrapper ? I want your benchmarks. The GC is smart and optimized enough to not multiply by ten the memory footprint for an Optional.

**Comment by Faithcaio** [comment]
Using empty Optional for empty ItemStacks should be completly gone in API8.
But `Optional<ItemStack>` still exists to represent something else e.g.: 
- `Inventory#peekAt(idx)` returns an empty optional if the slot at given index does not exist.
- `Container#cursor` returns empty optional when the container is closed.

**Comment by dualspiral** [comment]
Guys.... this conversation has gotten really stupid.

We've asked you for your opinions and we _specifically_ asked for people not to reply to others. We wanted your honest, unabated opinions, and we didn't want people to argue about boxing, the extent of performance loss, etc.

Make your point - back it up with data if necessary. Don't try to invalidate others' points _because you don't like it_. At the end of the day we're asking this question because we want opinions from all sides of the camp. Most of the discussion has been fine and some of the points have been really well made, but I do not want to see people drown others out because they think they are right and _only_ they are right.

If you've made your stance known, leave it at that. When it comes to decision making **we** will make a judgement call and validate any dubious claims. Let's not try to make anyone feel invalid here because of the way they see things. 

If people choose to ignore this comment and this continues I'm just going to close and lock this issue. You have been warned.

**Comment by varrix** [comment]
Definitely am for the continued use of Optionals in the API. Most of my feelings and opinions surrounding it have been touched on briefly if not in-depth, so I'll just leave it at a thumbs-up :+1:

**Comment by Zidane** [comment]
I want to take a moment to thank everyone for the above feedback. It didn't go quite per my request (one post per person only) but you all kept it respectful and (mostly) to the point which is what I hoped to achieve but well...we know programmers, ourselves, and the internet.

With that said, we are keeping the status quo as is. The pendulum does not shift one way or another on this and while there is agreement that Valhalla will fix this issue overall, we cannot break the API quite completely to remove them just to bring them back whenever Valhalla is merged. There is simply not enough counter feedback against them to outweigh some of the benefits they bring. Especially with overturning the historical usage of them throughout the project.
