### ISSUE TITLE
Help, How Does This Work?

### ISSUE THREAD

**Issue by ItsAlexOffiical** [SpongePowered/SpongeAPI#2380]

**Comment by dualspiral** [comment]
**Github issues are for reporting bugs and requesting features in Sponge.** As this issue is has aboslutely no context and I expect is a request for support, I am closing this issue.

The following resources are available to support you in using Sponge - please use these in future unless you are reporting a bug or asking for a new feature:

* Sponge Docs (available in multiple languages): https://docs.spongepowered.org
* Sponge Forums: https://forums.spongepowered.org/
* Sponge Discord: https://discord.gg/sponge
