### ISSUE TITLE
Expose FastUtil in API

### ISSUE THREAD

**Issue by octylFractal** [SpongePowered/SpongeAPI#2408]
As [requested](https://github.com/EngineHub/WorldEdit/pull/1771#discussion_r790432140) by @zml2008. WorldEdit would like to have FastUtil promised by Sponge API so we don't need to shade it.

**Comment by zml2008** [comment]
I think this is a reasonable dependency to include, since it is explicitly included by Mojang in its entirety. We can probably revisit that choice once Valhalla is available in the MC release we target though.

**Comment by dualspiral** [comment]
We've thought about it, but we have decided that we're not going to add fastutil as a dependency to the API.

I understand SpongeAPI is indeed an abstraction layer over Minecraft and the Mojang server is our target. However, we have no control over the fast-util dependency that Mojang ships, nor do we wish to dictate what any interested third party implementors might wish to ship. Further, while this is unlikey, if Mojang changes the version of fastutil in point updates, such that they share an API - we may end up having to break our stable API because we bump a dependency, and that is not ideal. Indeed, we might get to a point where the link between SpongeAPI version and Minecraft version weakens as we mature more and more, this could end up being more a problem.

I do understand that the API uses _some_ dependencies that Mojang ship, but that API does use these and we do carry that risk, it's an API detail. However, we do not make use of fastutil in the API - why would we then add a dependency to such a library? That's an implementation detail, not an API one.

The reality is, including fastutil as a dependency to SpongeAPI has no upsides for us and many downsides -- we don't use it in our public facing API at all. It makes no sense for us to include it.
