### ISSUE TITLE
Networking / packet API

### ISSUE THREAD

**Issue by sk89q** [SpongePowered/SpongeAPI#341]
A networking / packet API has been requested.

**Comment by gabizou** [comment]
I can imagine having a PlayerConnection that we can have the following structure:

```java

public interface PlayerConnection {

    int ping();

    InetAddress getHostAddress();

    String getHostName();

    Optional<Player> getPlayer();

    void sendCustomMessage(Object plugin, String channel, byte[] rawMessage);

}

```

I have some reasons that packets shouldn't directly be within the API mostly because packets are entirely implementation based (Compare a packet from Flowstone to vanilla Minecraft and even custom packets created by forge mods). The only packet I can imagine supporting are the custom payload packets that is a basic requirement.

**Comment by gabizou** [comment]
I wrote a PR #363 to handle things like this.

**Comment by modwizcode** [comment]
I think it's been fully agreed that beyond the official mod communication packet, SpongeAPI will not contain a packet API. As that part is already complete, this issue is fixed.
