### ISSUE TITLE
getMaxAir, setMaxAir

### ISSUE THREAD

**Issue by AzureusNation** [SpongePowered/SpongeAPI#380]
In EntityLiving/Base the is a couple of methods that can physically not be done.

This is an extract from the Mixins implementation
```Java
in maxAir = 300;

public int living$getRemainingAir() {
        return getAir();
    }

    public void living$setRemainingAir(int air) {
        setAir(air);
    }

    public int living$getMaxAir() {
        return this.maxAir;
    }

    public void living$setMaxAir(int air) {
        this.maxAir = air;
    }
```

This can physically not work as Air is set in the datawatcher and even if you change nbt to something higher than 300 it always gets reset. Also this would not be able to save the maxAir as the var is not being saved by NBT or the world.

I believe this feature should be removed as it is not possible.

**Comment by gabizou** [comment]
> This can physically not work as Air is set in the datawatcher and even if you change nbt to something higher than 300 it always gets reset.

The only place I see it getting reset is in the constructor of `Entity`, of which is overwritten when readFromNBT is called (or a plugin listens to an EntitySpawnEvent of sorts and increases the air capacity).


> Also this would not be able to save the maxAir as the var is not being saved by NBT or the world.

I do believe it possible to save extra data to entities, you just have to assume that a) This extra data will NOT persist under vanilla Minecraft circumstances, b) The data will only be legible by the Granite server modification, and c) Other server modifications may already save this extra data in other ways.

Seeing as we've all experienced the vast difference of the Vanilla MC server and the legacy server mod, CraftBukkit, CB did indeed save extra data to entities that otherwise would not be readable on vanilla server. I'm sure as well that other server mods may too save extra data for the sake of their functionality.

**Comment by AzureusNation** [comment]
Ah I finally see how this will work. Closing Issue.
