### ISSUE TITLE
EntityCreature

### ISSUE THREAD

**Issue by AzureusNation** [SpongePowered/SpongeAPI#390]
I don't know if someone wants to look into it but have Ageable extend Creature as Creature has some interesting methods that could be used. Here's just a few:
  * getCanSpawnHere
  * hasPath
  * isWithinHomeDistanceCurrentPosition
  * detachHome
  * hasHome

Looks interesting to say the least for AI intergration. What do you think. I'll make a PR if people would like it.

**Comment by ryantheleach** [comment]
How do these relate to ageable? an entity can implement multiple interfaces..

**Comment by AzureusNation** [comment]
In minecraft there is a layer (entitycreature) between EntityAgeable and EntityLiving. Its just to be consistent with the current api layout/structure

**Comment by ST-DDT** [comment]
Isnt Creature the same as Agent?
Especially hasPath is AI stuff.

**Comment by gabizou** [comment]
I'd like to say that almost all of Creature is AI Related.

With Home related things:

> isWithinHomeDistanceCurrentPosition
> detachHome
> hasHome

I chose not to include these as this is ENTIRELY up to the creature having the idea of a home and whether to utilize it. This is entirely AI related, in fact, if you look at the source, the "home" is always defined as the `BlockPos.ORIGIN`, which, guess what, is 0,0,0.



> hasPath

Again, more AI stuff. Doesn't belong in a separate interface, irrelevant to most mobs aside from AI, seeing as most AI targets have a different utility for this method, the AI API should settle this. This doesn't belong in the overall API of a `Creature`.

 

> getCanSpawnHere

This is ludicrous as a) if you're calling this method, the entity is already spawned..... b) This is covered by `EntitySpawnEvent` with plugins able to override it and c) Why would this belong in `Creature` specifically? If anything, `EntityUniverse` should have a method `canSpawnHere`.

Sorry to be blunt, but I selectively excluded most internal methods because 
- They don't belong in the API
- The API is not governed to duplicate the structure of Vanilla Minecraft
- They don't belong in the API.
