### ISSUE TITLE
Client API - Basic Blocks/Items

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#429]
Been talking some with blood, sk, and the others about adding basic client API  to Sponge. I want to lay some ground rules:

- No we aren't sending plugins to the client
- No we aren't sending full classes to the client (lol...)
- No we aren't foregoing our promise that Vanilla clients can join a Sponge server
- No, you'll NEVER be able to add a block/item to the game with the same level of customization as a mod can do with Forge.

With that out of the way, lets get right down to it with what the system would entail:

- API will be added for a plugin to add basic block/item "descriptors" that "describe" a block or item. At the beginning blocks will behave quite like stone, dirt, etc...basically doesn't do anything and just sits there.
- This API will only be available before the server starts
- (Fun stuff) When a client joins, they'll be sent a resource pack with the sponge "missing block or item" texture. This includes Vanilla. This does require the player to accept the resource pack (a necessary evil).
- A Vanilla player will not be able to interact with blocks/items added with plugins.
- Plugin blocks and items will utilize resource packs to send the custom model and texture to the client.

Questions, comments, concerns? Lets hear it.

**Comment by sk89q** [comment]
To clarify, there are two types of client modding:

* Full blown modding -- let people write code that can run on the client
* "Server-side-dictated" modding -- A more limited setup where the server can tell the client pre-programmed things to do, like spawn particles.

The latter is currently doable, but it is extremely limited. You cannot create truly new blocks, new particles, etc. So, to make it less limited, we'd need to create a client mod that people would need to install to let mods on the server side create new blocks, particles, and so on. Players would need this client mod installed, but at least it's only one mod that they would need to be kept updated.

The downside with this approach that Sponge mods/plugins can only do what the Sponge mod has pre-programmed. Of course, it would be pre-programmed to let Sponge plugins/mods on the server create new blocks, entity types, and so on, and models and whatnot could be provided by a resource pack, but you couldn't, for example, write custom rendering code to use on the client.

----

That aside, in my opinion, we should go for the full blown modding approach, and on which we can build the other approach upon. This is because I see the gap between any form of modding and vanilla to be much larger then the gap between full blown modding and the more limited form of modding, so we might as well support full blown modding.

**Comment by simon816** [comment]
A while ago I drafted a concept way of sending block information to a client using JSON. It supported simple code execution using any java object however that could be restricted.
A demo JSON output: http://pastebin.com/7kJmKW2R

**Comment by progwml6** [comment]
sending arbitrary java code information to execute is a recipe for disaster

**Comment by Zidane** [comment]
We wont be sending arbitrary code to the client.

**Comment by ST-DDT** [comment]
But maybe we should add a plugin list (with version + download links) to the client to tell him, you need plugin x+y to join this server/use all features provided by this server.

The links should probably be limited to some trusted sources (similar to bukkit.org), or show a frightening warning otherwise.

On the other hand it should be possible to "use the client" plugin to gain information about what plugins are installed on the client (to restrict access to specific areas with special features) and potentially disable them, for particular areas or entirely, so that a player can have a entity radar in a city map but cannot use it in pvp. Of course this will not affect plugins that aren't recognized by Sponge, but its something you can start with.

Summary
- Required/Optional plugin list send to client
  - Specified Version(s)
  - Optional Download link
- Ability to check active client plugins
  - list client plugins
    - client may (partially) refuse to do so, but the server will be notified
  - enable/disable client plugins
    - via blacklist or whitelist, requirementslist
    - client may refuse to do so, but the server will be notified

**Comment by boformer** [comment]
The only problem is that the user must accept the ressource pack. Is it possible to detect if the user activated the pack? (...and kick if not??)

**Comment by Aaron1011** [comment]
With the addition of the [Resource Pack Status](http://wiki.vg/Protocol#Resource_Pack_Status) packet, yes.

However, there are problems with relying on this, such as the fact that `FAILED_DOWNLOAD` is only sent for an invalid url, not a failed download.

**Comment by mcsnetworks** [comment]
Another possibility is to add extended webApi support to the Mod detector when you try to login to the server.  Example:  a client tries to connect using Forge, display a message on the screen, that is easier to read than the current one, which instead of a basic list, presents a easily readable listing, describing which mod's they are missing with corresponding links to download them at.

I'm not sure how we could handle that from a vanilla perspective.

**Comment by ryantheleach** [comment]
easy. Link to the sponge website, pass the list of mods in as get parameters.

**Comment by Aaron1011** [comment]
Yes

**Comment by ST-DDT** [comment]
In the Attributes API there was a suggestion to use custom Attributes (DEX, INT, STR) for RPG plugins, so it would be cool to add the ability to show custom attributes of items to the client through the use of the plugin. 

Example: 
Boots of Strength
+5 Strength

**Comment by kamcio96** [comment]
any changes?

**Comment by TheAwesomeGem** [comment]
IMO, they should start working on this once the base API and implementation is done.

**Comment by Xemiru** [comment]
@kamcio96 its not going to change until a lot later since this is further down the line when Sponge has completed all its server-side things.

**Comment by kamcio96** [comment]
I don't expect the code, but only conversation about it. 

I think Client API can change minecraft forever ;)

**Comment by simon816** [comment]
In terms of a GUI API, I thought of some sort of HTML-esque feature. Similar to the web browser model.

**Comment by Zidane** [comment]
Closing this as we won't be going down the client route until we have a stable product with most if not all of our API implemented.
