### ISSUE TITLE
Zombie implementation issues

### ISSUE THREAD

**Issue by AzureusNation** [SpongePowered/SpongeAPI#444]
Hi All,

Just implementing Zombie and noticed that a few stray methods have been added that cannot be achieved.

```java
public boolean canBreed() {}

public void setBreeding(boolean b) {}

public int getAge() {}

public void setAge(int i) {}
```
Could these be removed or is there an actual use for them. If they were to be removed there would have to be a new interface called "Breedable" to separate age and breeding.

**Comment by modwizcode** [comment]
Can't baby zombies exist? Or is that not implemented with an age? As for breading, that should be split off in my opinion.
.

**Comment by AzureusNation** [comment]
baby zombies are not done by age but by size and a datawatch object.

**Comment by gabizou** [comment]
> baby zombies are not done by age but by size and a datawatch object.

Baby zombies are defined as a boolean value stored in a DataWatchObject. Nothing regarding size is actually stored or defining whether the zombie is a baby or not. 

In regards to separating `Ageable` and `Breedable`, it doesn't make sense as a zombie can technically have an age of a "Child" ergo, being a baby, the "age" factor can be handled by the implementation. Age is not a defined number that will always increase per tick, and a baby Zombie can be the clear example of that. 

In regards to breeding, Zombies do breed upon death. When a zombie dies, it has the chance to "come back' as a new zombie, in this case, breeding a new zombie or many zombies. This is why I chose to keep "breeding" a part of the Zombie. 

So no. This is not going to be split off and Zombies will stay Agreeable and breeding.

**Comment by AzureusNation** [comment]
@gabizou I would love to see how you are going to implement this as it makes no sense what so ever

**Comment by modwizcode** [comment]
@AzureusNation just add some member variables? Isn't age and breeding
stored in a LivingEntity which is inherited by Zombie?

**Comment by gabizou** [comment]
> I would love to see how you are going to implement this as it makes no sense what so ever

Already done with https://github.com/SpongePowered/Sponge/commit/158a7d78aa78ada74052df2855db70772569b6b3.

**Comment by AzureusNation** [comment]
1. your not really setting an age just whever it is a baby or not (basicly duplicate entrys)
2. It's not really breading because a Zombie calls for reinforcements
3. this should have more than one person to review the API @Zidane

**Comment by gabizou** [comment]
> your not really setting an age just whever it is a baby or not (basicly duplicate entrys)

To the developer, that's an implementation detail. It really doesn't matter.

> It's not really breading because a Zombie calls for reinforcements

I spoke with Zidane in IRC about it and he agreed that it was "breeding" regardless whether it's calling in for reinforcements.

> this should have more than one person to review the API @Zidane

You really should stop pinging Zidane, he is busy enough as it is. There are several people that review the API. Just because you don't see the discussion doesn't mean it didn't take place. I'll ask again, please stop being so combative, you're beginning to sound like a child.

**Comment by Deamon5550** [comment]
@AzureusNation I think it would help your understanding to stop thinking about age and breeded as being locked into the specific actions done by passive mobs and think about them more in the general sense. For age this is easy. For breeding just think of it as any mob that may through any action create more of itself.

And yes as gabizou said just because there aren't more people replying doesn't mean we aren't still always reading through issues and PRs.

**Comment by AzureusNation** [comment]
ok thanks for that @Deamon5550 sorry btw @gabizou
