### ISSUE TITLE
Entity and setLocation() Issue

### ISSUE THREAD

**Issue by Soren025** [SpongePowered/SpongeAPI#453]
From what I understand ```Extent``` is not guaranteed to be a world or even related to a world. So having a method to set the location of a player accept ```Location``` seems a bit strange. [the method](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/Entity.java#L79)

You could throw an exception if the extent is not a world but that does't feel right to me in this case.

It was brought up before and I am unsure what people's thoughts on the subject but as a possible solution to the issue I feel having Location be generic as ```Location<T extends Extent>``` and use an object that extends location ```WorldLocation extends Location<World>``` when dealing with entities would be a good idea. It would make it clear that the location is in fact is for a world.

This would also allow people to better extend Location for use in their own implementations of extent.

Also with https://github.com/SpongePowered/SpongeAPI/pull/451 making the block equivalent the same would make sense for the same reasons.

**Comment by Soren025** [comment]
> This would also allow people to better extend Location for use in their own implementations of extent.

What I mostly mean by this is the method ```Location setExtent(Extent extent)``` can't be overridden to ```MyLocation setExtent(MyExtent extent)```. To extend location to cater to a plugins implementation of extent you would either have to keep it and have it throw an illegal argument exception if the wrong type of extent is passed, or create a new method throwing an unsupported operation exception for the existing method.

However with generics it can be ```Location<T> setExtent(T extent)``` and would not need to be overridden at all.

**Comment by gratimax** [comment]
I think you need to explain yourself some more(maybe with some concrete examples), because I don't really get what you're saying at all.

> From what I understand Extent is not guaranteed to be a world or even related to a world. So having a method to set the location of a player accept Location seems a bit strange.

I don't follow the last sentence. 

> You could throw an exception if the extent is not a world but that does't feel right to me in this case.

If the extent is not a world, then two things happen:

1. If the extent is 'grounded'(this is determined by an impl) in a world different from where the entity currently is, the entity switches worlds.
2. The entity teleports to the location from the coordinate system of the extent(which is most likely different from the coordinate system of the world it's grounded in).

Note that some of the time both of these operations can be compressed into the same teleport packet, but other times there's some more hacking(in order to simulate multi-world teleportation for worlds in the same dimension).

>  but as a possible solution to the issue I feel having Location be generic as Location<T extends Extent> and use an object that extends location WorldLocation extends Location<World> when dealing with entities would be a good idea. It would make it clear that the location is in fact is for a world.

I guess this shows your misunderstanding. It was never said that Location is "for" a world, it simply has an extent as a reference point.

> This would also allow people to better extend Location for use in their own implementations of extent.

Location literally calls 0 extent methods, which means that it makes no difference if there's a different implementation of extent behind the interface... Again I might be missing some more concrete examples.

> To extend location to cater to a plugins implementation of extent you would either have to keep it and have it throw an illegal argument exception if the wrong type of extent is passed

Same as above, all locations/extents are valid for teleportation.

**Comment by Soren025** [comment]
@gratimax I would first like to note that I do not deny not understanding a lot of things, however I post about what I see and if my understanding is wrong then so be it.

As a minor example, say I do ```new Location(new Vector3i(0, 2, 5), chunk)```. How would ```setLocation(Location location)``` handle a non world location. Better yet if I were to implement extent my self as

``` java
public interface Arena extends Extent {
    World getWorld();
}
```

how would it handle it then? Say another plugin returns a location and you have no idea what it is a location for. If the ```setLocation(Location location)``` method throws an exception like I said you could do above then you would have to check and make sure all locations you or the server did not provide was that of world.

In regards to extending location for my above example it is a minor issue and has solutions but still a bit annoying.

``` java
public ArenaLocation extends Location {
    ...
    // Cant override and change parameter
    @Override
    public ArenaLocation setExtent(Extent extent) {
        //throw new UnsupportedOperationException();
        // or
        // if (!(extent instanceof Arena)) {
        //     throw new IllegalArgumentException();
        // }
    }
    ...
}

**Comment by ST-DDT** [comment]
Wasn't there a PR with extend parenting?
If all extends have a parent (except the world), that can be tracked back to a world this wouldn't be an issue anymore. Because whatever you push in there you can still get the real world coordinates from it.

**Comment by Soren025** [comment]
@ST-DDT Don't think extent parenting is going to happen. @sk89q made some good points in his comment on that PR.

**Comment by ST-DDT** [comment]
Mhh. I agree with him that the root extend may not be a world. A copied selection is not connected to a world anymore.

If the extend's hierarchy does not share an extend with the other extend's hierachy. You cannot convert them from one to the other.

But you can only use extends in two ways.
- Provide a CoordinateTransformer as method argument as used in WE.
- or have a CoordinateTransformer setup in the extend.

Ok well there is also the alternative of using
`Function<Location,Location> getLocationTransformer(boolean reverse)`
Which will propably be the most definition with most capeabilities.

For your suggestion with `Entity.setLocation(WorldLocation)` this is not a good approach because of the virtual copies of selections that are no longer connected to worlds. You may want to move an entity inside this copy or schematic as well. I will write some examples tomorrow. Did you get my point so far?

**Comment by Soren025** [comment]
@ST-DDT I get where your coming from. Sending an entity to what you call "virtual copies" would be useful. But I don't think it's actually possible for an entity as it is now to exist in anything other than a world.

You bring up something good however. If an entity can not exist without a world, and it is possible for an extent to have no relationship with a world. Then how do the ```EntityUniverse``` methods work for that?

**Comment by boformer** [comment]
I got another use-case for this: http://dev.minetest.net/TODO#Voxel_Area_Entities
Let's say you have a mod that adds large, moving boats. The location of entities on the boat is relative to the boat's coordinates (``BoatLocation``).

**Comment by ST-DDT** [comment]
@boformer Are you referring to generic locations or coordinate transformations?

**Comment by sk89q** [comment]
Entities work in WorldEdit Extents -- they are copies of the entities' data. There isn't really "moving" an entity though -- there is copying an entity to a different extent by grabbing an entity snapshot, putting it on the new extent, and deleting it in the old extent. For that reason, there is no setLocation() or teleport().

Of course, that approach has an issue with simulated extents like World because the entity is a Java object that we don't want to destroy and recreate. In addition, there is the problem of trying to move a player from a World to a custom Extent which brings a number of issues.

I pondered about the issue a few months back but I am not sure how to best resolve this. For simple world -> world teleports, we can do simple instanceof checks of course.

**Comment by boformer** [comment]
Extents are a nice abstraction layer, but in 99.9% of all use cases, the extent will be a ``World``. It would be easier to understand if ``Location`` just had a ``getWorld()`` method.

**Comment by sk89q** [comment]
The problem is that it doesn't fix the teleport problem.

**Comment by Soren025** [comment]
Perhaps a subclass to extent, one that identifies it as an extent that an entity can teleport to, containing the methods for ```setLocation(Location)``` to make use of for the teleportation.

For example
``` java
public interface WorldExtent extends Extent {
    World getWorld();
    Function<Vector3d, Vector3d> transformation();
    Function<Vector3i, Vector3i> blockTransformation();
}
```

Of course you would still need to throw an exception in the ```setLocation(Location)``` method but not as much. Tho a solution with no exceptions to be called would be preferable.

**Comment by Soren025** [comment]
Another idea I had. What about creating a super type to ```Entity``` similar how ```User``` is to ```Player```. Move appropriate methods over and create an abstraction layer to split a live world ```Entity``` from one that is simply a template in an isolated extent.

Modify ```EntityUniverse``` to use this abstraction type and the ```WorldExtent``` idea above could be used to override those methods to once again return ```Entity```.

**Comment by Mumfrey** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  adam@eq2.serveftp.net
    Domain eq2.co.uk has exceeded the max emails per hour (72/60 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:47100 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by web3.cov.yesit.co.uk with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.84)
	(envelope-from <noreply@github.com>)
	id 1YNeha-0003nO-BG
	for adam@eq2.co.uk; Tue, 17 Feb 2015 09:44:22 +0000
Date: Tue, 17 Feb 2015 01:44:22 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1424166262;
	bh=f9Of8a3mVJblxdJC5dNNOTmTag62m2sQx1YL7P1E8BY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=nRFMONxyXsOKr1DmU9cujUBVi+JEuWKpGtMn2b76C5BiciZixOImcwo05jPRqTULK
	 tMtcGVpbuIzUKOHLl49XVmePx06xpwOltTq4D1C6DQxH/4jcyMGZcoe4RyRPd85s4J
	 J5HNoun8kn/QlQwHCBRdW7LbNLpJHOaCHbhLsd3M=

**Comment by ST-DDT** [comment]
@Soren025  Sounds like a nice idea, there is already the `EntityState` interface, which could be used for that purpose. But we should then also have the `WorldLocation` extends `Location<WorldExtend>`, as return type for `Entity.getLocation()`

**Comment by Soren025** [comment]
@ST-DDT I foresee a problem with the generic location idea conflicting with the super type abstraction idea. Mostly to do with ```EntityState.setLocation(Location<? extends Extent>)``` not being being able to be overridden as ```Entity.setLocation(WorldLocation)```

In this case I would rather location remain the same and a method such as ```boolean EntityState.canTeleport(Location location)``` be added for entities instead. The method returning false if you are trying to teleport an ```EntityState``` from a ```World``` scope to an isolated scope or the other way around. Of cource ```EntityState.setLocation(Location)``` throwing an exception if it returns false as well.

**Comment by Soren025** [comment]
I just kinda realized with what I mentioned in my above post that a ```canTeleport(Location)``` would kinda solve the original issue on its own in a way. Although @sk89q would any of the ideas here help to solve what you were talking about above?

**Comment by sk89q** [comment]
Entity states don't have teleport problems because they are just collections of data and are not simulated and have no in-memory structures. As-is, it is possible to manually "teleport" an entity by making a state and spawning it in another world. If you don't remove the entity from the old world/extent, then you essentially duplicate the entity.

It is possible to use states purely to do teleportation

**Comment by gabizou** [comment]
I think we've resolved this with a few commits, @Zidane am I right?
