### ISSUE TITLE
Problems with entity events

### ISSUE THREAD

**Issue by caseif** [SpongePowered/SpongeAPI#462]
Over at Pore, we've been focusing on implementing events to the best of our ability within the plugin. However, in doing so, I've noticed a fair number of gaps within SpongeAPI's event system, namely pertaining to entity-related events.
Below are lists of issues I have found.

**Missing events**
- No EntityShootBowEvent
- No EntityUnleashEvent (despite an EntityLeashEvent)
- Nothing resembling an EntityDamageEvent (cannot get damage modifiers)
- No portal-related events (e.g. creation, entrance, exit)
- No event for when a bottle 'o' enchanting is used
- No event for food level changing due to factors other than food consumption
- No event for when a horse jumps (not necessarily needed, but could be helpful)
- No event for when a zombie is destroying a door (may be covered by entity AI system)
- No event for entity despawning
- No sheep-related events (dying, shearing, eating)
- No event for a projectile hitting an entity (would not necessarily be covered by a health change event due to snowballs and such)
- No event for slimes splitting upon death

**Problems with existing events**
- EntityTargetEvent defines no setters
- EntityTeleportEvent defines no setters
- EntityTeleportEvent defines no velocity-related methods
- EntityIgniteEvent defines no methods
- getFlamable and setFlamable in ExplosionPrimeEvent are misspleled
- EntityInteractEvent and children should implement Cancellable
- ProjectileLaunchEvent should implement Cancellable
- EntityExplosionEvent should implement Cancellable
- EntityTameEvent offers no way either to get the tamer

Finally, the getEntity method is ambiguous in certain cases (namely when more than one entity is involved). I would advise overriding and specifically documenting it in events such as these.

**Comment by AlphaModder** [comment]
Um, you misspelled "misspelled" as "misspleled" 
"MIS-puh-le-le-d"!

**Comment by caseif** [comment]
@AlphaModder That, er, was intentional. :)

**Comment by Deamon5550** [comment]
- EntityShootBowEvent -> ProjectileLaunchEvent
- EntityUnleashEvent Noted.
- EntityDamageEvent -> EntityChangeHealthEvent
- portal-related events -> EntityTeleportEvent, possibly missing for portal creation event
- event for when a bottle 'o' enchanting -> EntityItemConsumeEvent
- event for food level changing Noted.
- event for when a horse jumps -> EntityMoveEvent? we don't have events for any entities jumping, not just horses, and I'm not sure I see the use for one either
- event for when a zombie is destroying a door -> EntityBreakBlockEvent
- event for entity despawning -> EntityExpireEvent
- sheep-related events -> PlayerInteraceEntityEvent, PlayerInteraceEntityEvent, EntityChangeBlockEvent
- event for a projectile hitting an entity -> EntityCollisionWithEntityEvent
- event for slimes splitting upon death -> EntitySpawnEvent
- EntityTargetEvent defines no setters -> since there is no api control over AI yet the set entity could fail validation steps, pending AI api
- EntityTeleportEvent defines no setters -> can simply cancel the event and issue a new request to teleport
- EntityTeleportEvent defines no velocity-related methods -> Uhhhh, and what would the velocity be if the teleport is between dimensions? I don't see how this is at all valid
- EntityIgniteEvent defines no methods -> It extends EntityEvent as is cancellable, what else are you looking for?
- getFlamable and setFlamable in ExplosionPrimeEvent are misspleled -> OCD change
- EntityInteractEvent and children should implement Cancellable -> Noted.
- ProjectileLaunchEvent should implement Cancellable -> At the point of this event the entity has already been created, if you want to cancel this then listen for the EntityAboutToConstruct event with an EntitySpawnReason of Projectile
- EntityExplosionEvent should implement Cancellable -> from the docs "explosion already has taken place" if you want no damage from the explosion then just set the yield to zero or use the ExplosionPrimeEvent
- EntityTameEvent offers no way either to get the tamer -> Noted.

**Comment by caseif** [comment]
@Deamon5550 
- `EntityShootBowEvent` - This event could be fired for any number of reasons, though I suppose the `Cause` system may eliminate the need for it
- `EntityDamageEvent` - To quote the OP: "(cannot get damage modifiers)"
- Portal events - players can enter and exit a portal independent of a teleport event
- `HorseJumpEvent` - horse jumps are sort of special in terms of behavior, so the event could see justification in that
- `ProjectileHitEvent` - noted, but I do have a question: does `EntityCollisionWithEntity` only apply to a projectile hitting and entity, or could it be called by, say, a player pushing a pig?
- Setters `EntityTeleportEvent` - circuitous in my opinion, but I can't argue
- Velocity methods in `EntityTeleportEvent` - I'll be the first to admit I don't know exactly how Minecraft handles teleportation, but judging by the fact that they're defined in Bukkit (inb4 "'It was in Bukkit' isn't a good reason"), I imagine it can be impacted by a teleport. That being said, I'll need to look further into it.
- `EntityIgniteEvent` - it would certainly be helpful to have a `Cause

**Comment by caseif** [comment]
@Deamon5550 
- `EntityShootBowEvent` - This event could be fired for any number of reasons, though I suppose the `Cause` system may eliminate the need for it
- `EntityDamageEvent` - To quote the OP: "(cannot get damage modifiers)"
- Portal events - players can enter and exit a portal independent of a teleport event
- `HorseJumpEvent` - horse jumps are sort of special in terms of behavior, so the event could see justification in that
- `ProjectileHitEvent` - noted, but I do have a question: does `EntityCollisionWithEntity` only apply to a projectile hitting and entity, or could it be called by, say, a player pushing a pig?
- Setters `EntityTeleportEvent` - circuitous in my opinion, but I can't argue
- Velocity methods in `EntityTeleportEvent` - I'll be the first to admit I don't know exactly how Minecraft handles teleportation, but judging by the fact that they're defined in Bukkit (inb4 "'It was in Bukkit' isn't a good reason"), I imagine it can be impacted by a teleport. That being said, I'll need to look further into it.
- `EntityIgniteEvent` - it would certainly be helpful to have a `Cause` as well as a getter and setter for the duration
- Everything else - noted

**Comment by caseif** [comment]
@Deamon5550
Regarding a `HumanAttributeChangeEvent`, I would be perfectly okay with that; in fact I would prefer it.

**Comment by gabizou** [comment]
> EntityShootBowEvent - This event could be fired for any number of reasons, though I suppose the Cause system may eliminate the need for it

If an entity is shooting a bow with an arrow, they're first, a [`ProjectileSource`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/projectile/source/ProjectileSource.java) launching a [`Projectile`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/projectile/Projectile.java). Having a new event for the sake of saying "Bukkit had it." isn't valid for this case. One of the many reasons Bukkit had retained the `EntityShootBowEvent` was due to backwards compatibility. I don't see the point in having redundant, if not vague events that can cause confusion.



> EntityDamageEvent - To quote the OP: "(cannot get damage modifiers)"

Are you seeking for the `DamageModifier`s that Bukkit featured towards 1.7.10? It's been an issue I've been considering for a little over a week now.



> Portal events - players can enter and exit a portal independent of a teleport event

Ok. I'll give you that.

> HorseJumpEvent - horse jumps are sort of special in terms of behavior, so the event could see justification in that

I still don't see the point in a HorseJumpEvent. Intact, I'll put it this way: I don't want to see events recommended that are so narrowly defined for a single type of entity.

> ProjectileHitEvent - noted, but I do have a question: does EntityCollisionWithEntity only apply to a projectile hitting and entity, or could it be called by, say, a player pushing a pig?

Yes. Any entity colliding with another entity is reason for an EntityCollisionWithEntity event. If the collision is "damaging", there would be another event thrown.


> Setters EntityTeleportEvent - circuitous in my opinion, but I can't argue

No. Teleport events should be immutable. Cancel the teleport and teleport the entity yourself.

> Velocity methods in EntityTeleportEvent - I'll be the first to admit I don't know exactly how Minecraft handles teleportation, but judging by the fact that they're defined in Bukkit (inb4 "'It was in Bukkit' isn't a good reason"), I imagine it can be impacted by a teleport. That being said, I'll need to look further into it.

I'm going to assume you're meaning to "retain velocity" after teleporting? I do remember that MC supports that sort of teleport as of 1.8.



> EntityIgniteEvent - it would certainly be helpful to have a Cause as well as a getter and setter for the duration

Will add.

**Comment by caseif** [comment]
>Are you seeking for the DamageModifiers that Bukkit featured towards 1.7.10? It's been an issue I've been considering for a little over a week now.
Precisely. Personally, I saw promise in the system, as it provides plugins with much more detailed information about what was happening within the event.

>I still don't see the point in a HorseJumpEvent. Intact, I'll put it this way: I don't want to see events recommended that are so narrowly defined for a single type of entity
I understand that it's sort of a specialized case, but it *is* unique in how it functions, and I could see plugins making use of such an event that would be difficult to impossible without it. Perhaps there could be a more generalized event such as `EntityLeapEvent`?

>I'm going to assume you're meaning to "retain velocity" after teleporting? I do remember that MC supports that sort of teleport as of 1.8.
To be completely honest, I'm not entirely sure of the function of such a mechanic or whether it's even necessary, but I wanted to publish the idea on the chance that it's necessary.

Everything else: noted.

**Comment by caseif** [comment]
@Deamon5550 

>event for when a bottle 'o' enchanting -> EntityItemConsumeEvent

Looking at this again, that's not quite how experience bottles work. They're instead thrown as projectiles, and upon destruction, drop experience orbs.

**Comment by AlphaModder** [comment]
@caseif Wouldn't that be the Consume, and then Spawn events for the orbs?

**Comment by gabizou** [comment]
> Looking at this again, that's not quite how enchantment bottles work. They're instead thrown as projectiles, and upon destruction, drop experience orbs.

So, then a `ProjectileLaunchEvent`? And subsequently, when experience orbs are spawned with `EntitySpawnEvent`, and subsequently, when `PlayerExpChangeEvent` for when a player picks up the experience.

**Comment by caseif** [comment]
@gabizou I was more thinking of an event which would fire upon the bottle breaking (thus triggering the `EntitySpawnEvent`s), but rethinking it, the `EntityCollisionEvent` is already called.

**Comment by ryantheleach** [comment]
>  events for any entities jumping.

Double jump plugin?

**Comment by advancid** [comment]
How would you detect a player that is jumping? If I remember correctly, in the vanilla client when you press the jump key, it changes your velocity without telling the server.
