### ISSUE TITLE
Remove Optional from CommandCallable

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#465]
I think it doesn't really make sense that the usage string is required while the description and help strings are wrapped in an ``Optional``. It should be required that every command has a help message!

I think in this case, it would be better to use simple strings. **That also makes it easier for plugin developers to implement the interface.**

Example how it is right now: https://docs.spongepowered.org/en/plugins/commands.html

What I propose:
```java
String getShortDescription() {
    return "Displays a message to all players";
}
String getHelp() {
    return "Displays a message to all players. It has no color support!";
}
String getUsage() {
    return "<message>";
}
```

**Comment by Zidane** [comment]
getHelp and getShortDescription should return Text objects.

@gratimax @Minecrell

**Comment by ST-DDT** [comment]
I agree on both.
Help and description should not be optional.
But they should be Texts or Message

**Comment by boformer** [comment]
Why Text objects? All of these should be **unformatted**. The module that handles the ``/help`` command sets the format.

**Comment by ST-DDT** [comment]
Maybe but you could use the format to highlight important parts.

**Comment by Minecrell** [comment]
I'm not sure if there is a big need for these to be instances of `Text`: normally these are supposed to be displayed in the help list (`/help`) as a short description of the command. For longer explanations, plugins should provide their own `/command help` command.

I agree with @boformer here, additionally allowing colors and other formatting on these would result in an inconsistent help list with a lot of different colors which would look very weird. While it may have a use in a few cases where you would like to highlight important parts as @ST-DDT mentioned it would probably cause more problems with consistency than it will actually provide any benefits for developers.

**Comment by ryantheleach** [comment]
You could maybe define styling aliases of some kind, like "keyword", or "optional keyword" and let the underlying implementations of sponge define what it means to have a consistent style, additionally allowing rich text allows for clickable links, and commands to be embedded in help text.

**Comment by boformer** [comment]
I also thought about links in the long help description that is only displayed when you use ``/help <command>``.

Is it possible to modify the ``Text`` provided by the ``CommandCallable`` to limit the formatting options?

(e.g. remove all colors and formats, underline links)

**Comment by ST-DDT** [comment]
Maybe some Html like message approach. The description provider can use normal text or highlights, or even use colors, but if he does not overwrite the stuff, the default use used.
Same after using RESET.
So basically an overwrite what the default is.
`Player.sendMessage(Message message, TextStyle defaultStyle)`

**Comment by boformer** [comment]
@ST-DDT There is ``TextColors.NONE`` for

The new Text API: https://github.com/SpongePowered/SpongeAPI/tree/feature/text/src/main/java/org/spongepowered/api/text

**Comment by boformer** [comment]
What I noticed is that many plugins have multiple subcommands. To provide useful help message, it might be a good idea to add multiple usage strings with different help messages (UsageString <-> HelpString Map).

When you enter ``/help``, the server lists all the commands with the short one-line description:
```
--- Command Help [Page 1/7] ---
/ban - Ban players
/broadcast - Send a message to all players
/kill - Kill players or entities
/msg - Send a message to a single player
/tp - Teleport to a player or location
..
Usage: /help [page] or /help [command]
```

When you enter ``/help tp``, the server lists all the usage strings with the detailed descriptions:
```
--- /tp Command Help ---
/tp <target> [-f] - Request to teleport to a target player. Use the -f flag to force a direct teleport.
/tp <player> <target> - Teleport the player to the target player.
/tp [world] <x> <y> <z> [-o|-n|-e]  - Teleport you to a specific location. Use the optional flags to choose between -o Overworld, -n Nether or -e The End.
Aliases: /teleport, /goto, /to
..
Usage: /help [page] or /help [command]
```

**Comment by ST-DDT** [comment]
@boformer I know the new text API.
But there is a difference between NONE and what i had in mind, because NONE also inherits from previous Text parts if i got it right. I would like to use RESET and then replace reset using a method to apply a new default there.

'Awesome' + RED + 'Part' + NONE + 'End' => 'Awesome' + RED + 'PartEnd'
`NONE` does not change the format.
'Awesome' + RED + 'Part' + RESET + 'End' => 'Awesome' + RED + 'Part' + WHITE + 'End' 
`RESET` does change the format to the default (white in this case).

> To provide useful help message, it might be a good idea to add multiple usage strings with different help messages (UsageString <-> HelpString Map).

If you show details for subcommands the plugin author can style and format his own (long) description to show the appropriate values or are you suggesting something like:
`getShortHelp(String subcommand)`

**Comment by boformer** [comment]
@ST-DDT The easiest way is to give plugins full control.

The "usage" string works for simple commands, but not for complex overloads and subcommand structures. That's why I propose to remove it.

When the ``call`` method returns false, the server can send a help message like this to the client instead of the "usage" string:

```
Error: Look at the __command help page__ to see how this command works
```
Clicking on the underlined ``__command help page__`` link calls ``/help <command>``.

I thought about something like this
```java
// Displayed in the /help command list, unformatted
String getShortDescription(CommandSource source);

// A full help page with multiple formatted lines, displayed on /help <command>
// Can contain different usage examples, etc.
List<Text> getHelp(CommandSource source);

//No getUsage...
```

There is a ``CommandSource`` argument for both methods to return a individual message for different players (e.g. based on permissions).

Example for a multiline help page:
```
/tp <target> [-f] - Request to teleport to a target player. Use the -f flag to force 
a direct teleport.
/tp [world] <x> <y> <z> [-o|-n|-e]  - Teleport you to a specific location. Use the 
optional flags to choose between -o Overworld, -n Nether or -e The End.
```

**Comment by ST-DDT** [comment]
Thanks for your explanation.
A argument parameter would be nice for getHelp().
For example to add pagination
getHelp(CmdSource, String args)
/help tp
/help tp page2
/help tp flags

**Comment by boformer** [comment]
The used command alias should also be an argument of ``getHelp``. When you register the 3 aliases "tp" and "goto", the plugin has to know which alias the player used.

To simplify this, we could also replace ``List<Text> getHelp(...)`` with ``boolean callHelp(CommandSource source, String args, String usedAlias`` and let the CommandCallable handle everything.

**Comment by ST-DDT** [comment]
@boformer You are right, it is better to push the entire help display stuff to the command itself, because its quite easy to sendMessages to CommandSources IIRC.
But i would flip param order to:
`boolean callHelp(CommandSource source, String usedAlias, String args)`
The boolean indicates the  same as `call(...)` does: "Whether the command was found", or doesn't it?

[CommandCallable](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/command/CommandCallable.java)

**Comment by boformer** [comment]
I still don't understand what ``List<String> parents`` actually means. 
The javadoc is **"A stack of parent commands, where the first entry is the root command"**

Is it something like this? 
1. ``{"usedAlias", "unusedAlias", "AnotherUnusedAlias"}``

Or is it something like this that lists up the subcommands?
2. ``{"sponge", "conf"}`` when typing ``/sponge conf -d nether logging.chunk-load true``

I guess it is the second one.

**Comment by boformer** [comment]
Looking at the implementation, the parents seem to be the ``parent`` commands of a subcommand, and the ``args`` string also contains the command itself.

That's why parents is an empty list for "root commands":
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/service/command/SimpleCommandService.java#L97

**Comment by sk89q** [comment]
For more documentation on the commands code, see https://github.com/sk89q/Intake/wiki

I do agree that usage and help are not that relevant in Sponge. They are more relevant when the help command code and the commands are of the same project, but that is not the case here and the variation is too large.

**Comment by boformer** [comment]
@ST-DDT I looked at this again. I finally understood that Sponge officially supports subcommands with ``Dispatcher``, so there is no need for plugins to manually generate subcommand lists. The help system can do that

I propose the following methods. I added a ``source`` argument to all of these commands, so that the strings can be permission-dependent:

```java
// Short one-line description for "/help" command list
String getShortDescription(CommandSource source)

// Detailed multi-line help message. No format support
List<String> getHelp(CommandSource source)

// Usage String, e.g. "<player> <msg>"
String getUsage(CommandSource source)
```

**Comment by ST-DDT** [comment]
@boformer You may be right with the `Dispatcher` supporting that feature. But maybe the plugin owner uses two ways to be able to adress a command like
/spawn <Entity>
(this alias is the main one, but it is unavailable due to another plugin overwriting it.)
/mySpawnPlugin spawn <Entity>
The command should be able to present the help in a way that is actually usable.
Let my explain it with an example:
````
1) Player types: /help mySpawnPlugin spawn
2) Plugin shows: Allows the spawning of entities.
   Usage: /spawn <entity>
3) Player types: /spawn ZOMBIE
4) Player is teleported to the spawn
5) Player blames the plugin for showing wrong info, but the plugin cannot do anything about it.
````

If the command displayed the usage `/mySpawnPlugin spawn <Entity>` in 2) everything would be fine.

> No format support

You know my opinion on that.

`URL getHelpUrl(CommandSource source)`

This shouldn't be a separate method, if a plugin has a web page for commands, it can use the description to link that page. That's another reason to make the description a `Message`/`Text`.

**Comment by boformer** [comment]
@ST-DDT When a player executes /help mySpawnPlugin spawn, the help system extracts the string cmdString = "mySpawnPlugin spawn". It searches the command service for a command named "mySpawnPlugin". If the found CommandCallable is a Dispatcher, it searches the Dispatcher for a command named "spawn". Then it displays something like this:

```--- command help ---
Usage: /mySpawnPlugin spawn {getUsage(...)}
{getHelp(...)}
Subcommands:
{List of subcommands with short desc if command implements dispatcher}
```
Only the {} parts are taken from the CommandCallable itself.
There is no need for the getHelp() method to know the used command alias. The help plugin generates the text for it.

I agree with you, it might be better to use Message/Text for the long help, so that the plugin author can embed links etc...

**Comment by ST-DDT** [comment]
@boformer Maybe i explained myself wrong.
````java
CommandCallable spawnCmd = new MyPluginSpawnCommand();
Dispatcher mainCmd = new MyPluginMainCommand();
Dispatcher serverCmdDispatcher = server.getCommandDispatcher();
serverCmdDispatcher.register(spawnCmd, "spawn");
serverCmdDispatcher.register(mainCmd , "mySpawnPlugin");
mainCmd.register(spawnCmd, "spawn");
````

So basically the same command object is used in different command hierarchies.

> Only the {} parts are taken from the `CommandCallable` itself.

Yes, but what if the plugin want to display something command related on its own?

Example WorldBorder: 
````
--- command help ---
Usage: /wb trim <speed> ...
Trims the world to the specified worldborder size.
Notice:
You will be asked to confirm your request with /wb trim confirm
Subcommands:
None
````

Maybe you want to address it with /worldborder or you have to qualify it using /worldborder:wb it should be possible for the plugin to use the right command. Its not 100%ly needed i agree with you, but i don't see a point in hiding arguments from the `CommandCallable` the user has entered in order to get this help.

Maybe we should finish the first part of your suggestion in a PR, to have some progress on this and in the meanwhile the team should decide on the other point. Because we cannot decide that one.

PS: Thanks for your good descriptions.

**Comment by sk89q** [comment]
In WorldEdit, I do handle subcommands in `//help` by looking for `Dispatcher`s, and I think it's pretty readable: https://www.youtube.com/watch?v=yAqFjAfck-I

However, checking for Dispatchers is not ideal because it sort of breaks good OO practices, as making a "wrapper" object around a Dispatcher will lose that important information. Ideally, help would be retrieved and handled by all `CommandCallable`s in the same way that `call()` functions (a dispatcher would build a subcommand list). The main downside with that approach, however, is even greater inconsistency.

**Comment by boformer** [comment]
@ST-DDT ``/wb trim confirm`` would actually be a subcommand of ``/wb trim``, so it would be displayed in the subcommand list.
Maybe you are right and we should pass the ``parents`` list or something similar. If plugin devs want to build their own subcommand system for some reason, they can do it and list up the subcommands. 

I like consistency, that's why I think that the help message should only contain relevant stuff and not repeat the command. If you want to mention a subcommand, you can just say "After that you have to use the confirm subcommand".

For consistency, there could be some kind of "FormatDefaultsService" where plugins can obtain the default colors for help elements and general plugin messages: ``getDefaultColor("help-command-usage") ``. 
That would at least give developers a chance to display the messages in the right color, even when the server admin changed the defaults or uses a different help plugin.

This is getting complex, that's why prefer simple solutions (strings, only necessary arguments).

**Comment by boformer** [comment]
It was just confirmed that you can use ``\n`` in ``Text`` instances to create new lines. That means we don't need a ``List<Text>``.
