### ISSUE TITLE
Shared interface for CommandBlock/MinecartCommandBlock

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeAPI#476]
Right now [`CommandBlock`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/block/data/CommandBlock.java) and [`MinecartCommandBlock`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/vehicle/minecart/MinecartCommandBlock.java) are completely separate and only both implement `BlockCommandSource` but don't share the other methods available for command blocks.

This also results in inconsistent methods for `CommandBlock`/`MinecartCommandBlock` and the minecart command block is even missing most of the methods that exist for `CommandBlock`. We should put these in a separate interface (not sure about a name, `CommandBlock` exists already as the tile entity) and let both interfaces implement that.

Another way to fix, especially with SpongePowered/Sponge#187 in mind would be to move the methods to `BlockCommandSource` and have just a `BlockCommandSource getSource()` method on `CommandBlock`/`MinecartCommandBlock` as all of the properties accessed via the methods are internally actually saved in the same class as the command sender. However, as described in the mentioned issue, this might be an implementation leak then because not all implementations need to have this separate from the actual `CommandBlock` normally.

**Comment by AlphaModder** [comment]
If we're gonna add this, might we also do something about the other minecarts? Chest, Furnace, and Hopper all have minecraft counterparts.

**Comment by Minecrell** [comment]
@AlphaModder Good point, didn't know they were also separated. As these all work similar to their tile entity version we should provide a shared interface for all of them so we don't get an inconsistent API.

**Comment by AlphaModder** [comment]
@Minecrell Perhaps you should rename this to "Shared interface for dual Entity/TileEntity objects" or something.

**Comment by ST-DDT** [comment]
In my opinion `EntityCommandSource` and `BlockCommandSource`/`TileCommandSource` are different things that should not be merged together. The `CommandSource` is good enogh for this already.
But there should be some shared interface for `MinecartCommandBlock` and `CommandBlock` like `CommandStorage`. Due to their abilty to store (and execute) commands. But this should be unrelated to Chests etc.

**Comment by ryantheleach** [comment]
Furnace carts do not act similarly to the tile entities, at all. They are some of the oldest buggiest seeming code in the game IMO.

**Comment by gabizou** [comment]
It's interesting to note that in #475, I created the [`CommandData`](https://github.com/SpongePowered/SpongeAPI/blob/feature/tile-entities/src/main/java/org/spongepowered/api/block/tile/data/CommandData.java) class as a data object representing the actual data for a `CommandBlock` tile entity. I'm curious if then that since the `MinecartCommandBlock` shares very much of the same data, perhaps we need to have a grander PR to handle a form of `EntityData` of which `CommandData` does not extend, but simply there would exist `MinecartCommandData extends EntityData, CommandData` and the `CommandBlockData extends TileEntityData<CommandBlock,CommandBlockData>, CommandData`. That way the super interfaces would work out quite nicely.

**Comment by JBYoshi** [comment]
Is this still an issue, or has the Data API resolved it?

**Comment by gabizou** [comment]
@Minecrell If I remember correctly, there's proxy command sources now? If so, wouldn't this issue be resolved?

**Comment by JBYoshi** [comment]
@gabizou Yes, there are proxy sources, but this issue isn't about those. This is about being able to access data pertaining to both command blocks and command block minecarts using a shared interface.

**Comment by gabizou** [comment]
So, the `CommandData` then?

**Comment by JBYoshi** [comment]
Yep. I think the easiest way to fix this would to make `CommandBlockSource` extend `DataHolder` and provide a `default` method to get the `CommandData`. It shouldn't require any implementation changes, since both `CommandBlock` and `MinecartCommandBlock` implement `DataHolder`.
