### ISSUE TITLE
Create API to spawn Human entities.

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#502]
Currently, the API does not allow simply spawning human entities, for reasons that I can explain:
- I didn't add support for spawning human entities when there is no testable implementation
- I didn't want to be the one to blame for adding to API that can't be implemented

So, here are the stakes: Someone writes additions to the API to *allow* spawning of Human entities (NOT Players!) AND provides an implementation PR to Sponge to allow testing of said Human entities.

**Comment by ZephireNZ** [comment]
Yes! In Bukkit, it was a pain in the ass to spawn human entities, usually resorting to NMS to get the job done. You'd usually have to use an plugin like Citizens, which often had way to much feature creep for something simple.

I'd definitely like to see this implemented, even if it's a pain for Vanilla to implement, other implementations like Glowstone may find it very easy to do.

**Comment by ST-DDT** [comment]
I have added this feature in one of my plugins.
The hardest part isnt implementing the human (Player). Its adding the created entity to the world. Because Bukkit does not provide any API for that and uses a lot of Wrapper classes that covers the real mc instances and need to be carefully unpacked (using reflections) before you can use them.

Iirc this API already has a method to add an existing entity. Because its seperates Entity creation and entity spawning
`EntityUniverse.spawnEntity(Entity)`

**Comment by gratimax** [comment]
@simon816 has already done some cool stuff with this, any input?

**Comment by simon816** [comment]
I have experimented and successfully got human entities to spawn, see http://puu.sh/gBrFB/ea8dcf954b.png
most of what's needed is already in the vanilla code, just needed to tweak some things to support the `HumanEntity` class which is a class that extends directly from `EntityPlayer`.
It's a pain that vanilla does special things for `EntityPlayer` when it should be `EntityPlayerMP` but that's likely because they can then share the same code between client and server.
So I've had to use some overwriting using mixins, which isn't too bad.

The biggest pain is that the vanilla packet `S0CPacketSpawnPlayer` does not send the `GameProfile` of the player being spawned. Instead, the profile is sent separately in a `S38PacketPlayerListItem` packet, which means that the human entity will appear in the server player list. That is not ideal so I am currently trying to remove the entry from the list, I've done that but now the skin is always the steve skin, not ideal but it works.

I have yet to see if there are any side effects of the 'fake' player (note: It's not using forge's FakePlayer) but it _can_ work without too many code injections.

**Comment by ST-DDT** [comment]
> I've done that but now the skin is always the steve skin, not ideal but it works.

Using (custom) skins is one of the most important features we developer need `Player`s/ `Human`s for.

> I have yet to see if there are any side effects of the 'fake' player

I experienced some (chunk??) memory leaks with my own implementation. (Took round about ~1k spawned and killed players to cause a noticeable effect (> 100 MBs), but somewhere close to 10k the heap was full. (i used a local server setup with low memory). 
The API'S `Human` suggestion should guarantee to avoid this kind of leak.
How is the behaviour concerning keeping chunks loaded for those fake players?
- Do these fake players cause the chunks to stay loaded at all times?
- If not, if the chunk gets unloaded and reloaded, will the player/human be still there like (tamed) animals or is he lost as most monsters are?

**Comment by ZephireNZ** [comment]
> Is the Human implementation gravity bound?

Like most living entities, I would say yes.

> Is he capable of having AI/PathFinder?

I'm sure the API will have a framework for AI at some point. For now, I'd personally go for a blank AI by default. Once the AI API comes in, developers could choose whether it wanders, fights, etc.

> Do these fake players cause the chunks to stay loaded at all times?
I'd personally say no by default, but it would be good to have an API for configuring whether an entity keeps chunks loaded.

> If not, if the chunk gets unloaded and reloaded, will the player/human be still there like (tamed) animals or is he lost as most monsters are?

I'd lean towards them not being despawned by default, like Villagers. Again, this is already configurable in the API.

**Comment by ST-DDT** [comment]
>> Is the Human implementation gravity bound?

> Like most living entities, I would say yes.

Well, Minecraft' s `Player` is not gravity bound at least not by the `tickEntity()` based gravity.

>> Is he capable of having AI/PathFinder?

> I'm sure the API will have a framework for AI at some point. For now, I'd personally go for a blank AI by default. Once the AI API comes in, developers could choose whether it wanders, fights, etc.

I will rephrase my question. Does he inherits from `EntityCreature` at some point?

> I'd lean towards them not being despawned by default, like Villagers. Again, this is already configurable in the API.

The more important part is: Do they keep the (surrounding) chunks loaded.

**Comment by simon816** [comment]
> I will rephrase my question. Does he inherits from EntityCreature at some point?
No, it directly extends `EntityPlayer`
When it comes to implementing an entity AI, `HumanEntity` could be given it's own shadow implementation of the AI - that'll be sorted later I'd imagine.

The human acts identically to an AFK player. If you hit it, it'll do the standard reactions etc.

I have not tested chunks yet, but I've made it exempt from the chunk forcing that usually happens with players, I've tried to make the server see the human as a standard entity and no more, while the client sees it as another player.

**Comment by gabizou** [comment]
This is why I wanted to make sure that all implications of having a way to spawn `Human` entities with the API are understood ;) I appreciate the efforts you're going through with this @simon816 I hope to have some testing later on with regard to events and such.

**Comment by ryantheleach** [comment]
@fullwall @Morphan1 @mcmonkey4eva it would seem silly to implement this into sponge without at least asking some advice from citizens. Any suggestions?

**Comment by Morphan1** [comment]
There's many factors you'd have to keep in mind when dealing with human entities. The biggest thing you have to realize is that these entities were designed from scratch to simply give an appearance to actual players, and thus have many flaws when trying to control them otherwise. I've made a list for all the thoughts I've had that might help. Keep in mind there's no particular structure to it:
- Skins:
  * Giving human entities player skins without sending tablist information to clients is impossible.
  * However, the good news is that you can remove the information after the client has processed it. (Seems to be ~2t)
  * When players spawn into the world, an EntityTrackerEntry <b>will not</b> naturally fire for them (as far as I have been able to test).
  * All of this means that you <b>must</b> use some sort of cheaty workaround.
- Movement AI:
  * If you want to make the human entities movable, it would probably be best to provide a default implementation, but keep it changeable. An API for this would be fantastic, and allow plugins to change the way these human entities move.
  * Something to keep in mind is that ground movement and flying movement do not react the same, and should probably be controlled by two different abstractions.
  * From my testing, a human entity with no AI given is <b>not</b> affected by gravity.
  * Although you can turn the head of human entities easily, <i>the rotation of the body is handled <b>clientside</b></i>.

As you're probably already aware, taking full control of human entities is not a simple task. There are many factors to consider -- should the main Sponge implementation allow the controlling of skins via API, with possible disruptions to players such as seeing these entities in the tablist for a split second? Should it actually provide a default movement implementation? Should they be able to run commands, pick up items from the ground, or use weapons? Or should all these things simply have an API for a per-plugin basis?

At this point I think I've started rambling a little bit, but I hope I've provided some sort of decent input. There are many other things to take into account, such as the fact that servers are rate-limited for how many GameProfiles they can get from Mojang's API. This causes delays in skin information, and results in Steve and Alex skins galore until the next attempt is available.

If you have any questions about any of this, feel free to ask.

**Comment by simon816** [comment]
See https://github.com/SpongePowered/Sponge/pull/207 for how I have implemented `Human` so far.

**Comment by Zidane** [comment]
@simon816 did much of the heavy lifting and has gotten humans to spawn and have the look and feel of a player.

I'll be writing up an AI layer after my current projects to let the API do more stuff with them.
