### ISSUE TITLE
Add CommandSource to Entities

### ISSUE THREAD

**Issue by MattBDev** [SpongePowered/SpongeAPI#508]
When looking at MCP, you can see that entities are able to execute commands. It makes sense to implement this in Sponge. I am sure some plugins that work with custom entities would find a lot of use for this ability.
I don't think there would be any downside in doing this.

**Comment by gabizou** [comment]
A few questions for this:

- Which entities specifically?
- Are entities actually executing commands (aside from Players)?
- From what I could tell of the usage of ICommandSender is to get the `IChatComponent`, a `Location`, display name string, and check permissions. There isn't really any entity that *does* send out commands ever, and allowing plugins to do so, it's something I'd imagine plugins would want to control themselves.

**Comment by MattBDev** [comment]
I would apply this to just all living entities. I would not be using this myself but I do imagine that other developers would find this useful to check permissions for entities and such. I feel it should be more consistent with Vanilla.

**Comment by ST-DDT** [comment]
Are the permission checks for living entities executed using the permission service? Or are entities OP/Console?

**Comment by MattBDev** [comment]
Permissions service

**Comment by Minecrell** [comment]
In general I agree with @gabizou, the `ICommandSender` in the internal entity is only used for getting the display name and a few other properties like the location of an entity.

However, simply because it's an `ICommandSender` in the implementation, mods are able to send commands as entities already and we would need a `CommandSource` we can use for these commands (when passed into our API) anyway. Therefore I guess it makes sense to make every `Entity` a `CommandSource` in the API, which also allows plugins to access the display name like on the player or send commands as entities on their own.

**Comment by MattBDev** [comment]
Not every Entity is a command source. Things like projectiles are the exception to this.

**Comment by gabizou** [comment]
While it's a neat implementation detail, that's all it is, an implementation detail. Minecraft simply doesn't use `ICommandSender` as it should be.
