### ISSUE TITLE
Statistics API uses longs, which are not supported by Minecraft

### ISSUE THREAD

**Issue by caseif** [SpongePowered/SpongeAPI#525]
Minecraft loads and holds in memory statistics as 32-bit signed integers, meaning passing a long to a related API method will cause the statistic to overflow and display an incorrect value. Therefore, I propose methods expecting or returning longs be modified to use integers instead.

**Comment by Deamon5550** [comment]
The fact that statistics are backed by integers in the vanilla implementation is an implementation detail. Changing the statistics to use integers would restrict all implementations to using integers and would not change the issue of overflow within the standard implementation. Especially since statistics are most commonly modified in an additive nature you would be getting an overflow regardless.

**Comment by caseif** [comment]
Certainly, but in this case, "implementation" refers to the vanilla Minecraft client itself, and furthermore a facet which is quite unlikely to be changed by any given mod. Even if a server uses a long to store the statistic value, when sent to the client, it will be handled by an int.

**Comment by Deamon5550** [comment]
Yes, but the point is that overflow will happen regardless, but by changing to integers we do nothing but restrict all implementations.
