### ISSUE TITLE
Fire CommandEvent on SimpleCommandService.call()

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#551]
The ``SimpleCommandService`` does not fire a command event when the ``call`` method is used.

I don't know if this is intended. When a plugin uses the ``call`` method, there would be no way for other plugins to cancel the command execution.

**Comment by zml2008** [comment]
It might make sense, rather than the MC ServerCommandManager calling a CommandEvent which is picked up by the SimpleCommandService, to have the ServerCommandManager directly use the call method, and have the SimpleCommandService call the CommandEvent.

Another issue is integrating the Forge CommandEvent with ours. This may be more complicated because the forge event requires an ICommandSender and an ICommand, which we don't really have if we don't use the MC CommandHandler.
