### ISSUE TITLE
Standardize usage of PluginContainer and the plugin instance.

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeAPI#555]
Currently the API uses both Plugin Containers and Plugin Instances at various places such as event registration, and schedulers. This should be standardized.

**Comment by progwml6** [comment]
@me4502 i'm not sure this really can be standardized as these 2 are very very different things

i also am not sure it should be standardized

**Comment by Zidane** [comment]
@progwml6 Its too confusing for plugin devs to know when to pass @Plugin or PluginContainer. In Forge, I don't remember ever seeing where you would pass your @Mod. Its always ModContainer (if necessary, a lot of the times your mod container will be grabbed otherwise). 

We should adjust the API to require PluginContainer or grab it ourselves in impl. If the latter, that may be an issue if you wanted to register an event for another plugin (as an example).

**Comment by boformer** [comment]
@Zidane I disagree with you.
Passing the plugin object makes more sense. Internally, the Sponge classes should get the plugin containers.

The current implementation already makes it possible to pass the container instead of the plugin.

**Comment by simon816** [comment]
IMO using the `@Plugin` instance should be allowed in all cases. Methods that need a plugin should have an Object parameter, from there the impl can check the object actually is a plugin instance, or if the object is a PluginContainer. Passing `this` is a lot easier than fetching the container through dep injection or the plugin manager.
All methods should throw an `IllegalArgumentException` if it's unable to determine the container from the passed in object.

**Comment by zml2008** [comment]
Currently it looks like everything that requires a plugin instance does that by passing the Object instance. PluginManager is set up to also take a PluginContainer for this parameter, so either option can be used -- plugin instance preferred though). I think that resolves this issue.
