### ISSUE TITLE
Ability to register default `TradeOffer`s

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#559]
We all know that [`Villager`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/Villager.java)s have defacto [`TradeOffer`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/merchant/TradeOffer.java)s based on their [`Career`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/types/Career.java), and we already have the ability to modify their `TradeOffer`s they can offer from [`Merchant`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/merchant/Merchant.java), but we don't have any way to "register" custom `TradeOffer`s for a specific `Career` and maybe "level". 

Two things that would be proposed are:
- Creation of a `Level` or be able to apply [`ExperienceHolderData`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulators/ExperienceHolderData.java) to a `Villager`
- Registration of a `TradeOffer` for a `Career` with an optional level included (level 1 inferred).

**Comment by ST-DDT** [comment]
Does this include the addition of new Careers/Professions?

One important point:
Plugins should not be able to set the trade offers directly. They should only be able to set TradeOfferGenerators. Because most trade offers are randomized. Random input (amount) and random output (enchantments).

If you are able to set the TradeOffers you should be able to get them as well.

Careers:
`Map<Integer/Level, List<TradeOfferGenerator>> getTradeOffers()`
Same for setter
List<TradeOffer> generateOffers(int level)

TradeOfferGenerator:
`TradeOffer generate()`

With a simple generator where you can pass in a TradeOffer which is always returned.

**Comment by ST-DDT** [comment]
Maybe something like [this](https://gist.github.com/ST-DDT/4f36f723c7d6ed86ce68)

**Comment by ST-DDT** [comment]
May I create a PR for this?

**Comment by ryantheleach** [comment]
> Plugins should not be able to set the trade offers directly. They should only be able to set TradeOfferGenerators.

I don't understand why a plugin wouldn't be allowed to supply a single trade into a TradeOfferGenerator rather then provide a whole generator. What happens if you have multiple plugins?

**Comment by ST-DDT** [comment]
You can supply a single trade offer in the generator. The generator  is just a wrapper to allow secure access.
Plugins can overwrite the behaviour in Events.

**Comment by ST-DDT** [comment]
I created a PR that could fix this issue: https://github.com/SpongePowered/SpongeAPI/pull/662

**Comment by gabizou** [comment]
Noting for #1032 to auto close when merged.

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeAPI/pull/1032.
