### ISSUE TITLE
Change parameters for retrieving chunks in world interface

### ISSUE THREAD

**Issue by MattBDev** [SpongePowered/SpongeAPI#560]
At the moment in the world interface there are the following methods for retrieving chunks:
- `Optional<Chunk> loadChunk(Vector3i position, boolean shouldGenerate);`
- `Optional<Chunk> getChunk(Vector3i position);`

The implementations of these methods only use the X and Z integers of the position and not the Y position. For this reason, I feel the parameter should be changed to Vector2i or an additional two methods should be created using Vector2i.
It isn't a major change but I am just thinking in terms of usability for other developers.

**Comment by Deamon5550** [comment]
The use of 3 dimensional vectors was decided on in order to not explicitly preclude the usage of three dimensional chunk loading and/or the separation of chunks into a form which is not the chunk columns that we have currently. Restricting these methods to two dimensions does not offer any real usability benefits and needlessly restricts future development which would otherwise require breaking API changes to function.

So no these methods will be staying as three component vectors.
