### ISSUE TITLE
Explosion improvements

### ISSUE THREAD

**Issue by gFreezer** [SpongePowered/SpongeAPI#571]
I have some suggestions to improve the explosion events that should at least be discussed:

 - The current names are really confusing, and they seem to have [confused many people in bukkit](https://bukkit.atlassian.net/browse/BUKKIT-2231) already. They should be renamed to something like `ExplosionCreateEvent` and `ExplosionDamageEvent` (to be improved...)
 - I personally think they rather fit into the `world` package instead of `entity` as the explosion is not necessarily caused by an enity

 - `setFlammable()` is incorrect as the explosion is igniting things, not being ignited itself. It should be `setFlaming()` or `setIgniting()`. An ability to change how many blocks are ignited would also be nice, something like `setIgnitionRate(float)`

 - As vanilla is using `float` for explosion radius and block yield, it would make sense to change from `double` to `float` in the API, I don't see a need for a precision that high

 - Is there already a way to control the damage on entities? If not, the `ExplosionDamageEvent` should implement `BulkEntityEvent` (Or should there be different events for blocks and entities?)

 - Shouldn't both (all three) events be `Cancellable`? This way, you can cancel the whole explosion (not even displaying particles/playing sounds) or just block/entity damage

**Comment by AlphaModder** [comment]
How about ```setIncendiary()```?

**Comment by ST-DDT** [comment]
You are right with the names of the event and methods.

The additional precision with double instead of float makes us independent from any changes in minecraft and allows custom/own server implementations which could use double themselfes.

> as the explosion is not necessarily caused by an entity

But mainly (except plugins) IMO it fits better to entitiy than worlds.

**Comment by ryantheleach** [comment]
> The current names are really confusing, and they seem to have confused many people in bukkit already. They should be renamed to something like ExplosionCreateEvent and ExplosionDamageEvent (to be improved...)

I slightly agree, but only because it's the ExplosiveEntity that is being primed, not the explosion itself.

> I personally think they rather fit into the world package instead of entity as the explosion is not necessarily caused by an enity

ExplosivePrimeEvent should be in entities, as it is an entity that is being primed.
The EntityExplosionEvent Should have a counterpart that is not an entity caused explosion.

Unless someone wants to make a shim EntityExplosion that causes explosions with a configurable explosion, which seems a cleaner solution considering all the effects that can happen, that can be spawned without a traditional mob or projectile.

> setFlammable() is incorrect as the explosion is igniting things, not being ignited itself. It should be setFlaming() or setIgniting(). An ability to change how many blocks are ignited would also be nice, something like setIgnitionRate(float)

Flammable/flaming is fine, igniting seems to imply whether it will start chain reactions as opposed to setting stuff on fire, but what about withering, or other side effects?

> As vanilla is using float for explosion radius and block yield, it would make sense to change from double to float in the API, I don't see a need for a precision that high

True, but it's a pattern in the whole API to replace floats with doubles, I don't see why they should make an exception.

> Is there already a way to control the damage on entities? If not, the ExplosionDamageEvent should implement BulkEntityEvent (Or should there be different events for blocks and entities?)

If which entities are going to be affected is known at the time of the ``EntityExplosionEvent`` I agree that EntityExplosionEvent should implement BulkEntityEvent. It already implements BulkBlockEvent.

> ExplosionDamageEvent 
What explosion damage event? 

Does the damage to an entity vary based on the distance to the explosion?


-------------------------------------------------

Explosions can have multiple effects.
Breaking blocks and dropping the item, Damaging Entities, Setting things on fire.

Following the tnt example, we have 

1. BlockPlaceEvent player places tnt
2. BlockBreakEvent(or BlockChangeEvent) Player activates tnt (redstone vs player caused ignitition vs firespread vs player caused firespread? vs explosion vs firecharge (the list goes on, which event should be fired for each one?))
3. EntitySpawnEvent Player activates tnt stage 2
4. ExplosionPrimeEvent tnt is about to create an explosions (I really wish explosions themselves were entities of some form)
5. EntityExplosionEvent tnt is exploding Note that this relates to an entity, plugin caused explosions might not have associated entities?
6. EntityDamageEvents Damage each of the entities involved in a blast, may vary damage between entities, (should this also include knockback care of the combat system? https://github.com/SpongePowered/SpongeAPI/pull/712), Status effect changes, withering those caught in the blast?
7. BlockChangeEvents (Should there be a blockExplodeEvent? or should this use BlockBreak?)
8. BlockChangeEvents Fires caused by the explosion?


In this what decides whether the blocks drop their items? or is it that the item entities have a chance to be exploded and events 6 and 7 are out of order or interspersed?

> Shouldn't both (all three) events be Cancellable? This way, you can cancel the whole explosion (not even displaying particles/playing sounds) or just block/entity damage

The only event not cancellable (assuming gab's new cause PR goes through as EntityDamageEvent didn't exist previously!) is the EntityExplosionEvent. but at this stage the explosion has already exploded. you can either cancel the block changes, or set the yield to 0.

https://github.com/SpongePowered/SpongeAPI/blob/e590f64a475ed65e742a9963e1c23fb4549683e0/src/main/java/org/spongepowered/api/event/entity/ExplosionPrimeEvent.java#L35
    /**
     * Represents an event when an {@link Explosive} is about to explode.
     *
     * <p>Explosions usually affect a radius and ignite, depending on the explosion.</p>
    */
    public interface ExplosionPrimeEvent extends EntityEvent, Cancellable {

https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/entity/EntityExplosionEvent.java#L34
    /**
     * Represents an event when an explosion already has taken place and blocks
     * are about to be broken/affected.
     */
    public interface EntityExplosionEvent extends EntityEvent, BulkBlockEvent {


https://github.com/SpongePowered/SpongeAPI/blob/feature/cause/src/main/java/org/spongepowered/api/event/entity/EntityDamageEvent.java#L43
    public interface EntityDamageEvent extends EntityEvent, CauseTracked, Cancellable {


-------------------------

The major issue I see, is that it is currently impossible to create an explosion from a plugin without an associated entity. attempting to do so without event restructuring will cause no ExplosivePrimeEvent so the explosion can not be cancelled.

**Comment by ST-DDT** [comment]
TBD: With the changes from the Cause PR we could probably rename `EntityExplosionEvent` to `ExplosionEvent` or else because we could now get the `Explosive` entity or the causing/creating plugin from the `Cause`.

**Comment by ryantheleach** [comment]
You mean prevent it from implementing the entityEvent interface? 

Whilst I agree you may be able to then get the entity from the cause, the rest of the SpongeAPI has been pretty consistent with making events implement an event relating to their primary cause. It would feel strange to me to not do the same with the explosion events.

When I wrote the above comment I managed to forget that when calling the event, you can keep the results of the event locally, so there would be no real advantage to creating an ExplosionEntity and could create a maintenance nightmare.

**Comment by bloodmc** [comment]
@gFreezer I have a branch which addresses your issues.
https://github.com/SpongePowered/SpongeAPI/tree/feature/worldexplosion

Please review as it will be pushed to master soon.
