### ISSUE TITLE
Make SimpleDispatcher not final

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#578]
There is no reason to do so. 

Plugin developers can extend the simple implementation and overwrite single methods of it.

**Comment by zml2008** [comment]
Yes there is. We can make something unfinal at any time if someone gives us a specific use case, but once something is unfinal it can never be made final again.

Removing finality means devs can override behavior in ways we possibly haven't predicted, so it should only happen for specific sections of the code that have been reviewed so that they can be overridden in a sensible way.

**Comment by Zidane** [comment]
CLosing this until a use case comes up.
