### ISSUE TITLE
CommandSpec.builder().setArguments(....) should accept an array of CommandElements

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#585]
Internally the method should call ``GenericArguments.seq(argsArray)``.

**Comment by gratimax** [comment]
I disagree. The _sequence_ of all command arguments is treated as the element that the command takes. Having a command take more than one element makes no sense with this API, hence the "constructor" for SequenceCommandElement. Besides, it isn't much hassle to call `GenericArguments.seq` and conceptually it does something very different.

Suggestions like these belong in a PR, since there is only one possible "change" you can make.

**Comment by Zidane** [comment]
@zml2008 

Is this valid?

**Comment by zml2008** [comment]
I think this could work. seq should still stay around for more complicated setups, but this takes care of reducing a little bit of repetition.
