### ISSUE TITLE
PlayerJoinEvent improvements

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#595]
The ability to change a player's spawn location on join would be a nice bonus to this event.

**Comment by boformer** [comment]
Why would that be better than ``event.getPlayer().setLocation(..)``?

**Comment by ryantheleach** [comment]
Traditionally there has been problems with setting the spawn point on join. Maybe it was due to when the event was being called.

**Comment by Deamon5550** [comment]
If that is the case then we can look at it, but otherwise there is no point for the change. And if that is the case ideally we'd fix this by solving the issue of using `event.getPlayer().setLocation(...)` rather than modifying the event. So basically this needs some testing.

**Comment by Azatik** [comment]
Tested. Everything works fine. Code:
    @Subscribe
    public void JoinEvent (PlayerJoinEvent event){
        Player player = event.getPlayer();
        Location spawnLocation = player.getWorld().getSpawnLocation();
        player.setLocation(spawnLocation);}

**Comment by Deamon5550** [comment]
Excellent.

**Comment by kashike** [comment]
So you would prefer having to grab the player, grab the location (if required) from the player, and then set the location - versus having a getter/setter in the method directly? So you'd prefer countless plugins to set the player's location on join, rather than having an event to set the location **once**? Interesting.

I'm confused by the handling of this issue. @Zidane assigned it to a milestone, and @Deamon5550 closed it. Could someone explain why?

**Comment by RobertHerhold** [comment]
It doesn't make a whole lot of sense to offer a method for this. In my opinion, the API shouldn't be bogged down with tons of extra methods simply because there might be a use case for them. If plugins need this functionality, it will only take 1 or 2 extra lines to make it happen.

**Comment by Zidane** [comment]
Reopening as we don't want to continue calling events from setPosition from every plugin changing a player's position when we can set whoever came last after event is called.

**Comment by BlackyPaw** [comment]
I would still argue that creating any such methods which may set any of a player's attributes inside a simple event aka notification is a bad idea with the main reasons being the following two thoughts on design:

Take for instance that you will find other attributes you might want to change directly as well because there would be events which would get dispatched while still processing the outer event. You would probably just add another method as there would be no reason against it if you chose to add it this time.

Another consideration is that an event still is an event. It is not supposed to be something you modify something else with. It's just there in order to notify you of something, possibly passing in some arbitrary context you might need for interpreting the event (in the case the player reference) and possibly making any adjustments to it. In my opinion you should keep it like this in order to not bloat the API.

As for the dispatching of possibly unnecessary PlayerMoveEvents (or similar) you might also introduce a technique of locking event dispatchment while still processing certain kinds of events. Or you might even want to take it one step further into locking down event dispatchment in such a way that only the last event of a type dispatched from inside an event handler which is processing a lockable event is actually dispatched afterwards. This would also increase chronological ordering of your events which is much more natural to me at least. So I would definitely prefer this technique over the one described above.

**Comment by modwizcode** [comment]
@Zidane can you explain what you mean by your comment a little more clearly?

**Comment by SonarBeserk** [comment]
Would it be smart to add some form of Positionable interface to deal with this? For use in any event where one might want to alter the position of the event?
