### ISSUE TITLE
I can not find a method item.getMetaData.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#610]
I can not find a method item.getMetaData (subID).

**Comment by progwml6** [comment]
we do not have integer IDs/metadata in the api as mojang is phasing them out in vanilla

**Comment by ST-DDT** [comment]
This covered by (ItemStack extends) DataHolder and the DataAPI. 
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/DataHolder.java

**Comment by Azatik** [comment]
MetaData remains in MineCraft. ID are changed to names. Additional ID (SubID) - stayed.
Wrire Code:
```
 case "item":
        if (args.length == 1) {
        Optional<ItemStack> itemInHand = player.getItemInHand();
        try{
             ItemStack itemstack = itemInHand.get(); 
             ItemType item = itemstack.getItem();

             String name = item.getName();
                                
             Text ItemName = Texts.of(TextColors.GRAY,  "You hold" + name);
             player.sendMessage(ItemName);}
        catch(Throwable T) {
        Text empty = Texts.of(TextColors.GRAY, "Empty.");
        player.sendMessage(empty);}}
        break;
```
I hold in my hand a stone => return minecraft:stone;
I hold in my hand granite => return minecraft:stone.

The names are the same.
Goal: get MetaData (subID).

**Comment by ST-DDT** [comment]
The damage/data value is no longer available in this API. (/give @p stone:4). Because it is not future proof.
You have to use the https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulators/blocks/StoneData.java for that and similar classes to resolve that yourself.
There may be a util for that somewhere but i dont now it.

**Comment by progwml6** [comment]
Minecraft itself is phasing out int based metadata and moving to the block state system. This api has no representations of the old int based ID's and metadata

**Comment by Azatik** [comment]
But as we now define what it is granite, and not a stone?

**Comment by ryantheleach** [comment]
Is there something equivalent to blockstate for items?

**Comment by AlphaModder** [comment]
@Azatik I believe you want ItemStack.getData(StoneData.class);

**Comment by Azatik** [comment]
@AlphaModder And what is the result?

**Comment by AlphaModder** [comment]
@Azatik That would be an Optional<StoneData> (optional.absent() if the item isn't stone)
Call .getValue() on it, and you will get a StoneType.

**Comment by Azatik** [comment]
Return optional.absent() in all cases. About the second did not understand.

**Comment by AlphaModder** [comment]
@Azatik Oh, sorry. I forgot you meant items. You'll want '''ItemStack.getData(BlockItemData.class).getState().getManipulator(StoneData.class).getValue();''' (I think.)

**Comment by AlphaModder** [comment]
@Azatik StoneType is a pseudo-enum of STONE, GRANITE, SMOOTH_GRANITE, DIORITE, SMOOTH_DIORITE, ANDESITE, and SMOOTH_ANDESITE.

**Comment by Azatik** [comment]
Code:
```
ItemStack itemstack = itemInHand.get();                    itemstack.getData(BlockItemData.class).getState().getManipulator(StoneData.class).getValue();
```

Result: error - "getState" cannot find symbol.

**Comment by AlphaModder** [comment]
@Azatik Sorry, it's generic <BlockItemData>getData(), and <StoneData>getManipulator

**Comment by Azatik** [comment]
Without MetaData badly. It is impossible to determine exactly what the player holds in his hand.

**Comment by AlphaModder** [comment]
@Azatik What?

**Comment by ST-DDT** [comment]
I guess more importantly it returns Optionals.
So you have to check for null references and unwrap it.

**Comment by AlphaModder** [comment]
@Azatik You want to get the ItemType? That would be `itemstack.getItem()`

**Comment by Azatik** [comment]
I already did. But Stone and Granite return minecraft:stone. And the question arose. How to determine exactly what it is? Stone or Granite?

**Comment by AlphaModder** [comment]
@Azatik I told you, `itemstack.<BlockItemData>getData(BlockItemData.class).getState().<StoneData>getManipulator(StoneData.class).getValue();`

**Comment by ST-DDT** [comment]
He wants `minecraft:stone:4` aka `granite`.
ItemStack.getItemType just returns `minecraft:stone`. So he need StoneData and StoneType and similar classes as well.

**Comment by AlphaModder** [comment]
@ST-DDT Yeah, and that's what I said :P

**Comment by ST-DDT** [comment]
You forgot the optionals in your query. Thats why it does not compile for him.

**Comment by Azatik** [comment]
But there are other items. And more of the mods.

**Comment by AlphaModder** [comment]
@Azatik You need to add the Optional get calls, yes.

**Comment by AlphaModder** [comment]
@Azatik The SpongeAPI does not support modded metadata/blockstates at the moment, afaik. Not until minecraft fully switches over to the BlockState system.

**Comment by Azatik** [comment]
And what would it mean to sponge? Each unit will have its own id?

**Comment by ST-DDT** [comment]
@Azatik Iirc there is a method to get all data from the block state.

**Comment by AlphaModder** [comment]
@ST-DDT I can't find it.

**Comment by AlphaModder** [comment]
@Azatik That is, unless someone makes a mod-sponge bridge.

**Comment by Azatik** [comment]
Waiting until MineCraft will go completely on BlockState?

**Comment by ST-DDT** [comment]
@AlphaModder

`Collection<DataManipulator<?>> getManipulators()` in `DataHolder`

**Comment by gabizou** [comment]
Just to clarify a few things here:

- The reason why the block id is `minecraft:stone` for both stone and granite etc. is because they are the same block id. Their "sub" id's per say are based on the `StoneType`s available from SpongeAPI. Eventually, all sub id's of these "types" for various blocks will become individual block types themselves, so eventually you will end up with `minecraft:stone`, `minecraft:granite`, `minecraft:smooth_granite` etc.
- The "damage value" system is entirely deprecated for the above reasons. I did remove all damage values possible from various sources, however, considering there are still plenty of blocks that have these intrinsic "sub values", they are kept as "types". 
- With regards to mods, well, mods do have to adapt as well, and I'm sure that some mods will end up providing a SpogneAPI compatible "Type" catalog of their block types. 
- The reasoning for having `BlockItemData` is because the `ItemStack` is infact just wrapping around a `BlockState` according to some arbitrary damage value system (currently for backwards compatibility until the damage value system is entirely removed in later versions). It doesn't make sense to keep around a damage value system that is going to be marked as deprecated as soon as it is added. 
- With `BlockState`, you can grab all the necessary information from the `BlockState` using: 
```java
if (item.getData(BlockItemData.class).get().getManipulator(StoneData.class).get().getValue() == StoneTypes.GRANITE) { 
// you have granite!
}
```
While that example looks a bit confusing, I'm looking into ways to narrow down the data by allowing shortcuts if you will so it could be written like so:
```java
if (item.getData(StoneData.class).get().getValue() == StoneTypes.GRANITE) {
    // you have granite!
}
```
Which in effect would first check that the item is intact carrying a `BlockItemData`, and if so, grabs the `StoneData` from the `BlockItemData`. Of course, you really need to be careful that you are making these calls correctly such that you KNOW you have, in absolute certainty, a stone block itemstack.

**Comment by Azatik** [comment]
@gabizou 
```
Eventually, all sub id's of these "types" for various blocks will become individual block types 
themselves, so eventually you will end up with minecraft:stone, minecraft:granite, 
minecraft:smooth_granite etc.
```
When it will be?

**Comment by ST-DDT** [comment]
If minecraft decides to do it. Its really hard for us to make asumptions. But it will take months at least, so you shouldn't wait for it.

**Comment by hunter688** [comment]
Player have some itemstack in hand, howto universally get what item exactly hold?

example of expected results: 
minecraft:stone:1 
biomesoplenty:leaves_0:3
tconstruct:slime_grass:2

Howto with spongeforge?

**Comment by ST-DDT** [comment]
Have a look at
[`ArmorEquipable.getItemInHand()`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/entity/ArmorEquipable.java#L134) (extended by `Player`).
Then [`ItemStack.getItem()`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/inventory/ItemStack.java#L86).
And finally
[`CatalogueType.getId()`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/CatalogType.java#L53) (which is extended by `ItemType`)
The actual variant can be obtained by DataAPI. [CatalogueItemData](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulator/catalog/CatalogItemData.java)

**Comment by hunter688** [comment]
Thx a lot.

**Comment by gabizou** [comment]
Don't forget that `ItemStack`s can simply have [`BlockItemData`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/manipulator/mutable/item/BlockItemData.java#L47) of which your block states that you're asking about are going be returned as actual `BlockState`s.
