### ISSUE TITLE
Ability to send Block changes to Players

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#619]
I don't believe we have this functionality yet, but, it would be useful to be able to send block changes to players without actually having the block changes in the world.

Quite possibly something that we could add to [`Viewer`]

[`Viewer`]:https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/effect/Viewer.java

**Comment by gratimax** [comment]
Yeah, I was about to comment the same thing. There can be some sort of hierarchy between `Viewer` and `Extent`, since Viewers "see" an extent. Viewer is perfect since this is what it was made for.

**Comment by zml2008** [comment]
I agree, this would be nice

**Comment by MattBDev** [comment]
Suggestion for the method that would be added to Viewer :
`sendBlock(Player player, BlockType type, Vector3i position)`

**Comment by ryantheleach** [comment]
Wouldn't a BlockState or BlockSnapshot be more appropriate?

**Comment by MattBDev** [comment]
You're right, I forgot about those.

**Comment by Zidane** [comment]
Duplicated in https://github.com/SpongePowered/SpongeAPI/issues/738

**Comment by Aaron1011** [comment]
@Zidane: The issues are duplicated by each other...

**Comment by TBlueF** [comment]
@MattBDev I kind of dont like the idea of grabbing the world from the player. Because you have to check the players world if you want to make shure you get the right block ^^

**Comment by ST-DDT** [comment]
From my point of view `Viewer` is indeed the right place to add it to.

Class Hierarchy just for clean overview:
- [Viewer](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/effect/Viewer.java)
 - [Player](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/player/Player.java)
  - [World](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/World.java)

With this in mind adding a `Player` argument to the method does not make any sense.

Also using `BlockType` may not be the best choice since you cannot use it for `Layered Snow` or `Redstone` that well. A `BlockState` may be more appropriate.

So the method should probably should look like this:
`sendBlock(BlockState state, Vector3i position)`

However we have to keep some more points in mind.
* Is the change of view persistent or will it be overwritten with the next chunk update?
  - What happens if the player switches to another world and then back?
* How do we handle the `Player`s gravity while walking on this fake blocks?
* How do we handle/send a really big amount of fake blocks (maybe a few chunks big?) to a lot of players?
