### ISSUE TITLE
CommandResult issues

### ISSUE THREAD

**Issue by Xemiru** [SpongePowered/SpongeAPI#628]
Why are the variables for the affected counts holding integers as opposed to a list of the affected objects? Some plugins may need to be able to rollback the effects of those commands; making it just a count would eliminate that. Retrieving the count would be as simple as list.getSize() if we use a list of affected objects instead. This applies to `affectedBlocks`, `affectedItems`, and `affectedEntities`.

**Comment by AlphaModder** [comment]
Though that's a good idea, we must have the variables in some form to remain compatible with the vanilla CommandResult system.

**Comment by boformer** [comment]
Adding a map for custom data would work.

**Comment by zml2008** [comment]
This could cause issues because it means that for some operations, a large number of block/item objects would have to be retained that world otherwise not be required, leading to memory usage/object allocation performance issues, and possible memory leaks if command results are stored anywhere, if somebody wanted to do anything like command blocks.

@boformer you should get off that custom data train sometime
