### ISSUE TITLE
BlockState lacks functionality to unset boolean DataManipulators

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeAPI#631]
Problem:
Let `sponge` be a `BlockState` representing a sponge block and `wetData` a `WetData` object. Using `sponge.withData(wetData)` a blockstate referring to a wet sponge can be created. There is currently no means to reverse this, since the current API only allows to add DataManipulators, not to remove them.

To fix this either the boolean DataManipulators must be changed to contain a boolean value or a `withoutData(DataManipulator<?> property)` method must be introduced to `BlockState`.

Also, could someone please clarify how the `cycleProperty(DataManipulator<?> property)` and `getManipulatorValue(String name)` methods behave for boolean DataManipulators.

**Comment by gabizou** [comment]
> Let sponge be a BlockState representing a sponge block and wetData a WetData object. Using sponge.withData(wetData) a blockstate referring to a wet sponge can be created.

Right, that's about the right way of doing it. I forgot that `ImmutableDataHolder` should likely have a `without(DataManipulator)` method, that can be easily added (or more of a "reset" since some data manipulators can not be removed unless the state is reset to a default state).



> To fix this either the boolean DataManipulators must be changed to contain a boolean value or a withoutData(DataManipulator<?> property) method must be introduced to BlockState.

As said above, will opt for a `without(DataManipulator)`.

> Also, could someone please clarify how the cycleProperty(DataManipulator<?> property)

No longer exists. 

> and getManipulatorValue(String name) methods behave for boolean DataManipulators.

Again, no longer exists.
