### ISSUE TITLE
Add Text.format() [similar to String.format()]

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#639]
The issue is described here:

https://github.com/SpongePowered/Sponge/issues/261#issuecomment-98931861

**Comment by gratimax** [comment]
I like this idea. I'll try to take a look and write a simple Text#format/Texts.format implementation when I get time to do so.

It may be possible to unify Text.Translation and text formatting somehow, since they both technically use the same system to replace labels. The difference is that a prospective Text formatting system replaces string templates with text and the current translation system replaces them with strings.

**Comment by RobertHerhold** [comment]
Also, a `Text#replace()` would be greatly appreciated (also similar to `String#replace()`)

**Comment by TomyLobo** [comment]
For your use case, a "Text.replace feature wouldn't be useful, since then you'd have an O(warp_count*string_length) complexity as opposed to just O(string_length).

**Comment by TomyLobo** [comment]
@boformer You could xmlescape the arguments and then just use String.format.

**Comment by boformer** [comment]
@TomyLobo I want a complete, integrated solution:

Input: Text object with color, styles, text actions, translatables
Output: Similar Text object with placeholders replaced.

**Comment by TomyLobo** [comment]
Well we could have a Texts.xml().format(format, args...) function, of course.
But you want actual text objects, which is an order of magnitude harder to do.
How about xml/json formatting now and Text object formatting later, when it's done?

**Comment by gratimax** [comment]
I've summarized my current thoughts on text formatting here: https://gist.github.com/gratimax/abaa32a49b5b82c08c13.

It's a short description of a format that I worked out. It is more opinionated in order to have a better templating experience, but I think that is a good thing. I've yet to work out if one can insert arbitrary JSON in `&{}` statements or if you can template within them.

**Comment by TomyLobo** [comment]
Oh, didn't know you meant to make a 5th way of specifying colors (§, json, Text objects, xml, your inline json thing).
I thought by Text.format you meant something like String.format...
So what does this text representation offer that none of the other 4 can offer?

**Comment by ST-DDT** [comment]
The main issue i have with this suggestion is that it introduces a new Text syntax that is used nowhere else and in the worst case scenario you have to convert your existing Text object to a special (legacy) string to insert it into your Text.
````
Text displayName = player.getDisplayName();
Texts.format(myMessage, displayName.toFormatString());
````

**Comment by gratimax** [comment]
@TomyLobo @ST-DDT 

It is able to do all the features of String.format, I just changed the format syntax specifically to something that looks python-3 like because it is the easiest syntax I have found. I can change that specifically to be something more C-style, but I think that would cause readability issues.

As I explained in the gist this format is partially meant for configuration. Thousands of plugins exist that define configuration somehow, and they need a way to have templates like player names without creating it on their own. As I see it a standard configuration format like the one I proposed has multiple advantages:

- Sponge now gets a standard way for server admins to configure stuff like chat format or different messages. Server admins don't need to learn a whole bunch of formats for configuring simple stuff like a chat message or plugin message, they only need to use one (so long as plugin developers find it useable enough to use).
- The format syntax is _similar enough_ to the legacy format that there is not much overhead to switch. We are deprecating the legacy format so that its usage is not recommended, and Text objects are not a format for specifying colors on their own, meaning that this is really the 3rd way of specifying colors where usage is recommended. Even then it's just a small language on top of Mojangson, so I would call it 2.5.
- Plugin developers don't need to implement their own formats which can sometimes be a pain, i.e. with escaping names or text. All formats before the current one did not support insertion for colored text, making the proposed one more featureful.
- Instead of documentation that is sometimes arcane and not useful for developer-defined formats, we are able to put standard documentation outlining how the format works in our own Sponge documentation. Then people can look it up easier and plugin developers can simply link to it in order to explain how to configure different templates.

@ST-DDT 
The entire point of this format is that you _don't_ have to convert your text object to a legacy string, you specify the _template_ this way so you can insert text within it. And no, what you suggested does not do the same thing because it doesn't handle escaping and it is almost completely unreadable for people trying to configure stuff.

**Comment by TomyLobo** [comment]
You're mistaken about Python:
````python
$ python3.4
Python 3.4.1 (default, Oct 14 2014, 19:57:05)
[GCC 4.7.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "aaa %(bbb)s" % {"bbb": "ccc"}
'aaa ccc'
>>> "aaa &{bbb}s" % {"bbb": "ccc"}
'aaa &{bbb}s'
````

**Comment by gratimax** [comment]
@TomyLobo 

As per the link I gave in the gist (http://pyformat.info/):

> Old `'%s %s' % ('one', 'two')`
New `'{} {}'.format('one', 'two')`

Or perhaps no better place than the [Python documentation itself](https://docs.python.org/3.4/library/stdtypes.html#old-string-formatting):

> __Note__: The formatting operations described here exhibit a variety of quirks that lead to a number of common errors (such as failing to display tuples and dictionaries correctly). Using the newer `str.format()` interface helps avoid these errors, and also provides a generally more powerful, flexible and extensible approach to formatting text.

And finally:

```python
$ python3.4
Python 3.4.2 (default, Oct 19 2014, 17:55:38)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "aaa {bbb}".format(bbb="ccc")
'aaa ccc'
```

I never said that the `&{}` was exactly how it looked in python, either.. the gist specifies how `&{}` does not actually do templating, but actually only does style and/or coloring. I did say "python-3 like" for string formatting specifically because it _reminded_ me of how python 3 does it.

**Comment by TomyLobo** [comment]
> @TomyLobo @ST-DDT
> 
> It is able to do all the features of String.format, I just changed the format syntax specifically to something that looks python-3 like because it is the easiest syntax I have found. I can change that specifically to be something more C-style, but I think that would cause readability issues.

You're mistaken about Python:
````python
$ python3.4
Python 3.4.1 (default, Oct 14 2014, 19:57:05)
[GCC 4.7.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "aaa %(bbb)s" % {"bbb": "ccc"}
'aaa ccc'
>>> "aaa &{bbb}s" % {"bbb": "ccc"}
'aaa &{bbb}s'
````

> As I explained in the gist this format is partially meant for configuration. Thousands of plugins exist that define configuration somehow, and they need a way to have templates like player names without creating it on their own. As I see it a standard configuration format like the one I proposed has multiple advantages:
> 
> - Sponge now gets a standard way for server admins to configure stuff like chat format or different messages. Server admins don't need to learn a whole bunch of formats for configuring simple stuff like a chat message or plugin message, they only need to use one (so long as plugin developers find it useable enough to advocate for).

I don't get why that requires inventing a new way to specify colors. Couldn't you just use the XML format and template that?

> - The format syntax is similar enough to the legacy format that there is not much overhead to switch. We are deprecating the legacy format so that its usage is not recommended (and this newer legacy-like format is part of the way to deprecating that), and Text objects are not a format for specifying colors on their own (but are the backing for all of the formats that you listed). That means this is really the 3rd way of specifying colors where usage is recommended. Even then it's just a small language on top of Mojangson (and not an entirely new schema like XML...), so I would call it 2.5.

I don't see a similarity to Mojang's JSON format at all, except for also using {}.
It looks more like JIRA's markup language.

> - Plugin developers don't need to implement their own formats which can sometimes be a pain, i.e. with escaping names or text. All formats before the current one did not support insertion for colored text, making the proposed one more featureful.

XML has very strict escaping rules and we can just provide a format function that inserts escaped text (and even Text objects if you want) wherever it finds %s or the likes

> - Instead of documentation that is sometimes arcane and not useful for developer-defined formats, we are able to put standard documentation outlining how the format works in our own Sponge documentation. Then people can look it up easier and plugin developers can simply link to it in order to explain how to configure different templates.

Good point, but again, the XML format has the same benefit

> @ST-DDT
> The entire point of this format is that you don't have to convert your text object to a legacy string, you specify the template this way so you can insert text within it. And no, what you suggested does not do the same thing because it doesn't handle escaping and it is almost completely unreadable for people trying to configure different messages or chat formats. Another reason for having something legacy-like as a format is so that it is readable and easily modifiable.

This is pretty readable and could be implemented in a way that handles escaping and insertion of Text objects:
``Texts.xml().f[romF]ormat("<u><b>Important: %s</b></u> %s", "Must be < 3 feet tall", someTextObject)``

> I'm not saying that my format is absolutely perfect, because I'm sure it isn't. I'm more interested in ideas for how we can achieve the goals that I outlined above through a format that is easy for developers AND server admins to use. Maybe a combination of Mojangson and the legacy format isn't a way to do so, so I would really like to hear alternatives.

XML :)

**Comment by TomyLobo** [comment]
> This means that any formatting on the inserted text objects stays only on them, and does not spill over to other parts of the source.

I just read this. If you're referring to § formatting, that may indeed be an advantage of your format.
However, we can just make ``Texts.xml().f[romF]ormat("<u><b>Important: %s</b></u>", "Must be < 3 feet tall")`` translate to ``Texts.xml().from("<u><b>Important: <span>Must be &lt; 3 feet tall</span></b></u>")``, thus encapsulating the interpolated value.
Also, @zml2008 had the idea of adding a placeholder object to the Text hierarchy and allowing formatting on Text objects.

**Comment by zml2008** [comment]
Yeah, going back to the *actual* purpose of this issue, text placeholders. I don't think any format should expose a placeholder system without backing in the Text API. 

You should be able to construct a placeholder text without having to deal with any representation anybody comes up with, entirely programatically. This would entail a new interface/class in the Text system as a placeholder:
```java
public class PlaceholderText {
    /**
     * Keys referring to placeholder positioning
    */
    public Set<String> getKeys();

     // Set a single placeholder value
    public PlaceholderText setPlaceholder(String key, Text text);
    // Throws some sort of exception if placeholders can be unset
    public Text build(boolean allowUnset);
}
```

In XML, this would be represented as (dunno about gratimaxML tho):
```xml
Player <placeholder id="name" /> is in wold <b><placeholder id="world" /></b>
```
but be loaded as a PlaceholderText instance
I'm not sure how this would fit into the `TextRepresentation` API, I'm thinking something like a separate method `placeholderFrom`?
If this fits into the Text API, it'd have to work on predefined template variables rather than having a template object with mutable variables I think.

Additionally, it would be very possible to incorporate legacy format character parsing into the XML format -- just gotta wrap the LegacyTextRepresentation for String element children, if that's what people want.

**Comment by TomyLobo** [comment]
How about this: 
- Since Java doesn't provide a good way to pass named arguments, use numerical indices instead of names.
- The id attribute would contain an index
- If the id attribute is missing, increment a global counter and use that as the index. That's kinda the way Java works with %s vs. %1$s.
- Make placerholder tags translate into placeholder objects
- The content of the placeholder tag becomes the default content
- Make those placeholder objects part of the regular Text hierarchy
- Give the Text class (interface?) a varargs method to obtain a Text representation with the placeholders filtered. ``myText.format("moo", "meh")`` would replace all placeholders with index 1 by "moo" and all placeholders with index 2 by "meh"

**Comment by ryantheleach** [comment]
PlaceHolders in the API would have the added effect of being able to manipulate and move placeholders.

Someone add's a placeholder for a player prefix, and another plugin could move that placeholder if necessary.

**Comment by ST-DDT** [comment]
The formatter must accept objects or different setters. Since it must accept Items/Achievements etc...

**Comment by TomyLobo** [comment]
you can throw in whatever you want, if it's an ``Object...`` vararg method
``public String format(Object... args)``

**Comment by ST-DDT** [comment]
Yes i know, but some suggestions used Texts as params only.

**Comment by TomyLobo** [comment]
@ST-DDT That would not be very user-friendly...

**Comment by zml2008** [comment]
Why would the param be anything but a Text? How are we supposed to know the appropriate representation for an ItemStack/Achievement/whatever?

**Comment by TomyLobo** [comment]
We could offer a default and if someone doesn't like the default, they can still convert it to ``Text``.
And at the very least we should also support ``String``

**Comment by ryantheleach** [comment]
> How are we supposed to know the appropriate representation for an ItemStack/Achievement/whatever?

Use the default Mojang representation?

**Comment by simon816** [comment]
`ItemType`, `Achievement`, `BlockType` etc all extend [`Translatable`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/translation/Translatable.java) which can easily be converted to `Text`

**Comment by ST-DDT** [comment]
Items etc are hoverable. In this case you dont want to oberwrite the text itself but he background data.
`Ülayer killed Ülayer in ArenaX`
And the item shown while hovering ArenaX is provided as format. I dont want ro replace ArenaX as text nor do i want to to only its name.

**Comment by TomyLobo** [comment]
For efficiency, we could make 3 overloads:
format(Object...) which does instanceof on everything and acts accordingly
format(String...) which converts everything to unformatted Text nodes
format(Text...) which doesn't convert anything at all. This would be used as a back end by the other two and could be used by people who want to roll their own converter. They could, in theory, use format(Object...), but efficiency :)

**Comment by ST-DDT** [comment]
Mhh. I revise m decision. `Text` only as param is propably the best choice since in most cases you set the text with the item alone. The only thing you may be able to set via Objects is custom formatting. But IMO this mostly the case if you try to avoid extra messages for different purposes.
Using the `Text` method as backing solution totally destroys everything you could customly implement yourself. Custom implementations would need the object params.
For simplicity reasons it should be one format method alone. Either using `Text` or `Object`s.
But it would be cool if it would be possible to partially insert values that are independent from the player and then add the player dependent stuff in a second run (in a for each loop).
The formatable text itself should be immutable.
Maybe something like Translatable and Translations.
Maybe i should write some example code to clearify my thoughts.

**Comment by TomyLobo** [comment]
I don't see how accepting anything but ``Text`` prevents custom conversions.
For example if you have this code in your plugin
````java
private static Text[] convertMyStuff(Object... args);

myText.format(convertMyStuff(arg1, arg2, arg3));
````
You can do all kinds of conversions yourself, regardless of of whether there's an additional format overload for Object... or not

**Comment by ST-DDT** [comment]
I guess I have an idea how this can be implemented.
`Text`.java
````java
class TemplatePart extends Text.Literal {

    public String getKey();

}
````
I used Literal as base because of the Text that can be shown as default. You will never use a translation or a selector as default (because you usually try to insert those there).

But it would also be possible to just wrap the default so you don't have to extend the Literal class.

`Texts`.java
````java
// Creates a TemplatePart with the given key, this key will be shown to the client if it isn't replaced.
public static Text.TemplatePart templateOf(String key) {
    return templateOf(key, "{" + key + "}");
}

// Creates a TemplatePart with the given key, the given default will be shown to the client if it isn't replaced.
public static Text.TemplatePart templateOf(String key, String defaultText) {
    return new TemplatePart(key, defaultText);
}

public static Text format(Text template, Map<String, ?> values) {
    // Is this a template that should be replaced?
    if (template instanceof TemplatePart) {
		Object result = values.get(((TemplatePart) template).getKey());
		if (result instanceof Text) {
			// TBD: Check this for TemplateParts as well?
			return (Text) result;
		}
		// TBD: Copy style, color etc?
		return Text.of(result);
	}
	if (template.getChildren().isEmpty()) {
		return template;
	};
	TextBuilder builder = builder();
	// TBD: Is it required to copy the root as well?
	for (Text child : template.withChildren()) {
		builder.append(format(child, values));
	}
	return builder.build();
}
````
I haven't tested this approach yet, but i hope my suggestion is easy to understand.

This solution has the benefit, that it works out of the box without changing the `Text` structure.
It also removes the necessity to replace all templates/values at once.

With this approach you can modify the JSON and XML format very easily to integrate this feature.
Without reducing the cross server type compatibility (as long as unknown tags/params will be ignored).
And you don't need any new template language, as suggested before.

**Comment by ST-DDT** [comment]
I just started [implementing this](https://github.com/SpongePowered/SpongeAPI/compare/SpongePowered:master...ST-DDT:TextFormat) - I will create the PR soon.
I still have to create a proper test plugin for this and create a Sponge and SpongeVanilla version with those API commits to check whether this actually works as expected.

Currently no native support from JSON/XML/Legacy is planned. Should I?
If yes I may need some help on the specification/implementation.
To add support those representations no changes in the API are required. 
(unless special javadocs should be added somewhere)

**Usage: Create Template**
````java
// "&4Player {killer} have killed {killed} with {weapon=with his bare hands}"
TextBuilder builder = Texts.builder();
builder.color(TextColors.DARK_AQUA);
builder.append(Text.of("Player "));
builder.append(Text.placeholderOf("killer"));
builder.append(Text.of(" have killed "));
builder.append(Text.placeholderOf("killed"));
builder.append(Text.of(" with "));
builder.append(Text.placeholderOf("weapon", "with his bare hands")); // with fallback
Text text = builder.build();
````
The created `Text` instance is reusable.

**Usage: Key-Value**
````java
Text someTemplateText = ...;
player.sendMessage(someTemplateText);
// Displays :"&4Player {killer} have killed {killed} with his bare hands"
Map<String,Object> replacements = Maps.new();
replacements.put("killer", killer.getName());
replacements.put("killed", Texts.of(TextColors.GRAY, killed));
ItemStack weapon = killer.getItemInHand();
replacements.put("weapon", weapon); // Does not look really good - See TBD
player.sendMessage(Texts.format(someTemplateText, replacements)); 
// Displays: "&4Player PvPMonster have killed &7Innocent&4 with Stick of Doom"
````

**Usage: Index**
````java
Text someTemplateText = ...; // With {0} as placeholder
player.sendMessage(someTemplateText);
// Displays :"&4Player {0} have killed {1} with his bare hands"
player.sendMessage(Texts.format(someTemplateText, killer.getName(), Texts.of(TextColors.GRAY, killed), killer.getItemInHand())); 
// Displays: "&4Player PvPMonster have killed &7Innocent&4 with Stick of Doom"
````

**TBD**
While implementing this I encountered the issue of ItemStacks and a few other Objects that have a nice textual representation (colored and hoverable text), but the `Text.of(Object...)` does not convert it appropriately.
So there are three possible solutions to this:
 * Force the API user to create/wrap it himself all the time
    * May be a PITA
 * Extend `Text.of(Object...)` with a few `if else`s to cover them
    * makes the method more and more messy
 * Add a `TextRepresentable` interface with a `toText() : Text` method and check for it in `Text.of(Object...)`
    * probably the cleanest and most extensible solution

The `Texts` class has javadoc line length issues and unqualified access to static fields.
OCD or fix with this (to be) PR?

**Comment by boformer** [comment]
Support for json or xml is important for plugins with customizable messages.

**Comment by ST-DDT** [comment]
Yeah I know.
I just don't know how to implement this.
For JSON I would just add a placeholder key to the object but how do i manage serialisation?
Its pretty deep inside NMS.
````json
{
"placeholderKey":"killer",
"text":"UNKNOWN", // used as fallback
...
}
````

For XML this is easier, because i could just add a new tag. But this would destroy the cross server compatibiliy if such thing exists. If I just use a param this would still work but i dont know how to change classes based on the existance of a param.

````xml
<template key="killer">
UNKNOWN
</template>
````
or the same as above with just the tag name of the existing plain text tag.

For JSON I will just try.
But for XML I would like to know which way to follow.

**Comment by boformer** [comment]
@zml2008

**Comment by ST-DDT** [comment]
I just identified the place where i must add the handling for the JSON, but i don't know how i can add code inside a method without copy pasting it entirely. Mixins? But how?

`IChatComponent.Serializer.deserialize(...)` from Minecraft v1.8.4
````java
[..]
else {
	JsonObject var4 = p_deserialize_1_.getAsJsonObject();
	Object var5;

	// Customization - START
	if (var4.has("templateKey")) {
		if (var4.has("text")){
			var5 = new ChatComponentPlaceholder(var4.get("templateKey").getAsString(), var4.get("text").getAsString());
		} else {
			var5 = new ChatComponentPlaceholder(var4.get("templateKey").getAsString());
		}
	}
	// Customization - END
	else if (var4.has("text")) {
		var5 = new ChatComponentText(var4.get("text").getAsString());
	}
	[..]
````
for serialization this would be very similar

**Comment by JBYoshi** [comment]
You can use `@Inject` to add code into methods.

**Comment by ST-DDT** [comment]
Cool, but how do I convert the `if` to an `else if` or change the result of the check in the if clause.
`var4.has("text")` -> `var4.has("text") && !var4.has("placeholderKey")`
I cannot `return` because the style is deserialized later in the code

````
19  aload_1 [☃]
20  invokevirtual com.google.gson.JsonElement.isJsonObject() : boolean [50]
23  ifeq 509
26  aload_1 [☃]
27  invokevirtual com.google.gson.JsonElement.getAsJsonObject() : com.google.gson.JsonObject [54]
30  astore 4 [☃]
// Customization - START (Simplified)
__  aload 4 [☃]
__  ldc <String "placeholderKey"> [56]
__  invokevirtual com.google.gson.JsonObject.has(java.lang.String) : boolean [62]
__  ifeq 64
__  new TextComponentPlaceholder[40]
__  dup
__  aload 4 [☃]
__  ldc <String "placeholderKey"> [56]
__  invokevirtual com.google.gson.JsonObject.get(java.lang.String) : com.google.gson.JsonElement [66]
__  invokevirtual com.google.gson.JsonElement.getAsString() : java.lang.String [44]
__  invokespecial TextComponentPlaceholder(java.lang.String) [47]
__  astore 5 [☃]
__  goto 406 <-- How can I add that there (goto 61 would work as well and would be less error prone)
// Customization - END
32  aload 4 [☃]
34  ldc <String "text"> [56]
36  invokevirtual com.google.gson.JsonObject.has(java.lang.String) : boolean [62]
39  ifeq 64
42  new ChatComponentText[40]
45  dup
46  aload 4 [☃]
48  ldc <String "text"> [56]
50  invokevirtual com.google.gson.JsonObject.get(java.lang.String) : com.google.gson.JsonElement [66]
53  invokevirtual com.google.gson.JsonElement.getAsString() : java.lang.String [44]
56  invokespecial ChatComponentText(java.lang.String) [47]
59  astore 5 [☃]
61  goto 406
64  aload 4 [☃]
66  ldc <String "translate"> [68]
````

**Comment by ryantheleach** [comment]
You can use a redirect annotation targetted at JsonObject.has. It will redirect only that method call and then you can return the result you want.
