### ISSUE TITLE
Redundant or inconsistant get methods in PlayerEvents

### ISSUE THREAD

**Issue by SonarBeserk** [SpongePowered/SpongeAPI#641]
getEntity()/GetHuman()/getLiving()/getPlayer()/getUser() all return player. As per documentation getHuman() should seemingly specifically return a human object and getLiving() a living object. getEntity()/getPlayer()/getUser() however seems outright redundant.

**Comment by gratimax** [comment]
I don't quite see what the issue is. Sure a lot of these methods seem redundant, but they're useful in terms of several event base types, like HumanEvent, PlayerEvent, UserEvent, and EntityEvent. Technically a PlayerEvent's getPlayer/getLiving/getEntity/getHuman/getUser all return the same thing, but it means that the PlayerEvent has a specific set of methods related to what it can actually return. 

If we took out these methods, we would have to cast to player from PlayerEvent like this:
```java
PlayerEvent myEvent;
myEvent.getEntity() // -> Entity
(Player) myEvent.getEntity() // -> Player 
```
So we basically trade a concise getPlayer method for a less concise getEntity method that _also_ requires an unchecked cast, making the compiler issue warnings or require a `@SuppressedWarnings` annotation.

No, generics are not a solution (`EntityEvent<E extends Entity>`) because they are not available at runtime, meaning that the event buses wouldn't be able to differentiate EntityEvents based on whatever subtype is expressed by the generics.

All in all, I don't see a problem. And even if there was a problem, trading more concise methods for less concise ones causes more problems than it solves.

**Comment by SonarBeserk** [comment]
Proper code wouldnt be making an unchecked cast imo. Should be type checking.
