### ISSUE TITLE
Ageable.setScaleForAge() should take arguments.

### ISSUE THREAD

**Issue by MikaalSky** [SpongePowered/SpongeAPI#647]
As the java doc says...
"Sets the scaling to be 1 if this entity is an adult and 0.5 if it is a baby."
It seems that you should be able to call Ageable.getAgeableData(), edit that and send it back to the AgeableEntity. It wasn't implemented in that way, though, which is kind of strange. Might of been a bit of an overlook.

@Xemiru

**Comment by Xemiru** [comment]
not necessarily that it should take arguments; again, the intention seems to be that it requires use of the data api. (pinging @gabizou as the author of the api)

we _could_ remove the method, however we can also let it stay there as a convenience method and also use it to help point to the proper usage via the java documentation.

though personally i'd go with removal since not everyone reads the docs until they figure out they have no idea what the hell they're doing.

**Comment by MikaalSky** [comment]
@Xemiru 
"not everyone reads the docs until they figure out they have no idea what the hell they're doing."
Exactly what I realized when I was making plugins initially. :+1:

**Comment by ryantheleach** [comment]
I think it's supposed to be a reset or update method, to reset the scaling to whatever it's supposed to be depending on the age of the entity. Maybe ask @gabizou .

https://github.com/SpongePowered/SpongeAPI/blame/62e90bd230c0ef0ce5487e7a1f6f53c239a49ba2/src/main/java/org/spongepowered/api/entity/living/Ageable.java

**Comment by gabizou** [comment]
I've been sick for the last few days so I haven't been able to do much with regards to improving documentation on both Data and Entity API since the Data API merge, on top of having to write the implementation and documenting *that*. The `setScaleForAge()` is intended to "reset" the scale according to the current age of the `Entity`, regardless of any scale options previously set. This interaction will be fixed soon when I get some time to clean up.

**Comment by gabizou** [comment]
This really shouldn't take any arguments, just that the state of the entity changes and is therefor a functional method on the entity itself, not on the data.
