### ISSUE TITLE
BulkBlockEvent mutability

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/SpongeAPI#653]
@gabizou and @Deamon5550 have both called into question in IRC some of the problems with BulkBlockEvent. Pinging them so that they can contribute to this discussion. I agree with their points, and I think some discussion is warranted:

- Under what circumstances can the blocks in a BulkBlockEvent _not_ be edited? The default behavior is a completely immutable bulk block event, for which we could find no use case
- The javadocs are unclear in terms of what makes the list in BulkBlockEvent mutable. Is the returned list from `getBlocks` mutable, or is the conceptual internal list of blocks mutable?
- The List of `getBlocks` shouldn't be a list in all cases, since not all bulkblockevents have an order in terms of the blocks they affect
- If the list returned from `getBlocks` is mutable, it means that it's possible to _add_ blocks to the bulk event, which doesn't really make sense without doing the modification manually

**Comment by Deamon5550** [comment]
There is a related issue #510 which TL;DR suggests that many (perhaps all) of the BlockEvents should really be extending BulkBlockEvent in order to cover the cases where they actually affect multiple blocks (for example placing doors or beds), so we should certainly take a good look at the function of the BulkBlockEvent.

First of all, regardless of any decision made the collection of affected blocks should **never** be mutable and those javadocs need to be cleaned up.

In my opinion the best course would be to replace the List<Location> with a pair of of collections, one representing the original affected blocks and the other the final affected blocks. The filter method would then always apply to the original blocks and would overwrite the final affected blocks each time it was called.

All BulkBlockEvents would therefore be cancellable, if that was not desired then we should probably split BulkBlockEvent into two events, one with the filter method and one without. For the cancellable one the `setCancelled` method would act as a shortcut for `BlockBlockEvent.filter(Predicate.alwaysFalse());`.

**Comment by gabizou** [comment]
This has been resolved in 36ba40439d38eaade3833bd45048849742ff79d2 with the addition of [BlockTransaction](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/block/BlockTransaction.java).
