### ISSUE TITLE
Is direction facing the wrong way or am I crazy?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#659]
https://github.com/SpongePowered/SpongeAPI/blob/20d434c769090c6b87696448d26b158fa9e02a90/src/main/java/org/spongepowered/api/util/Direction.java#L42

Defines north as (0,0,-1)

But Vector3d in flow defines that as https://github.com/flow/math/blob/2fde4364b8b65af4eadd5ef0d4adc713dd00f2b2/target/generated-sources/template/com/flowpowered/math/vector/Vector3d.java

(x,y,z)

I'm assuming the java docs are wrong, and we want to keep north in SpongeAPI as "new/notch North" and not as the oldschool sunnorth.

**Comment by gratimax** [comment]
I think that you are missing up two constants that represent different things. Yes, Sponge keeps north as the "Notch north" because doing otherwise wouldn't really be keeping consistency. But the "forward" constant defined in flow is the z unit vector commonly called "k" in linear algebra, and is a mathematical concept. I'm not sure exactly why it is given another name (perhaps @DDoS can answer), but in any case it's not a Sponge issue.

**Comment by DDoS** [comment]
These where inherited from the previous math library Spout used. I don't know their source, they just made it in the rewrite for compatibility.

**Comment by ryantheleach** [comment]
I double checked stuff, the values align with new north, but the javadocs don't.

**Comment by ST-DDT** [comment]
I agree with @ryantheleach 

It should be:
````java
 * <ul>
 * <li>{@link #NORTH} targeting towards -Z</li>
 * <li>{@link #EAST}  targeting towards +X</li>
 * <li>{@link #SOUTH} targeting towards +Z</li>
 * <li>{@link #WEST}  targeting towards -X</li>
 * <li>{@link #UP}    targeting towards +Y</li>
 * <li>{@link #DOWN}  targeting towards -Y</li>
 * </ul>
````
