### ISSUE TITLE
TextBuilder usability

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#660]
The result of the first block of code is entirely DARK_GRAY (unexpected), the result of the second block of code is coloured as expected (DARK_GRAY + dashes + RESET + header + "("...).

The [TextBuilder#append](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/TextBuilder.java#L220) method works differently then the [BungeeCord](https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/api/chat/ComponentBuilder.java#L76) variant. I'm curious what others think of using an approach similar to BungeeCord instead, or having a method to do similar.

SpongeAPI:
```java
TextBuilder builder = Texts.builder();

builder.append(Texts.of(dashes))
    .color(TextColors.DARK_GRAY)
    .append(Texts.of(header))
        .color(TextColors.RESET)
    .append(Texts.of("("))
        .color(TextColors.GRAY)
    .append(Texts.of(page))
        .color(TextColors.WHITE)
    .append(Texts.of("/"))
        .color(TextColors.GRAY)
    .append(Texts.of(maxPages))
        .color(TextColors.WHITE)
    .append(Texts.of(") "))
        .color(TextColors.GRAY)
    .append(Texts.of(dashes))
        .color(TextColors.DARK_GRAY);
```
BungeeCord:
![meow](http://i.kitteh.club/ZTEzN)

**Comment by RobertHerhold** [comment]
Personally, I think it's a bit of a pain to keep track of a lot of `.build()`s when chaining together a lot of Text instances, but I usually just use `.of()`. That said, I would like to see this feature.

**Comment by simon816** [comment]
When calling `color` on the _same_ builder object, it should change the color for that builder which is what sponge does at the moment. You just need to go into a child builder to change its color. 
Without creating lots of nested builders, use `Texts.of`
```java
Texts.of(dashes, TextColors.DARK_GRAY, header, TextColors.RESET, "(", TextColors.GRAY, page, TextColors.WHITE, "/", TextColors.GRAY, maxPages, TextColors.WHITE, ") ", TextColors.DARK_GRAY, dashes, TextColors.DARK_GRAY);
```

**Comment by gratimax** [comment]
I don't think that this is really a usability issue so much as it is a miscommunication of how Text works.
We designed the Text API (and text builders in particular) to mirror the actual Minecraft JSON as much as possible. 

So when you do
```java
builder.append(myText);
```
you're most closely adding text json to the `children` property of text, like this: 
```js
{
  "children": [
    ...
    ...
    myText // <- adding your object right here
  ]
}
```

Doing chained `.append`s:
```java
builder
  .append(myText)
  .append(myText2);
```
results in this:
```js
{
  "children": [
    ...
    ...
    myText
    myText2
  ]
}
```

Calling `.color()` the way you're doing colors the _text builder you are calling the method on_. This means that you're resetting the color each time until finally the color settles on dark gray. 

This is a difference from the Spigot mindset of their `ComponentBuilder` class, where the nesting in calling the color methods is implicit. But this is strange because you're calling methods on a builder that is conceptually modifying text that is nested. Instead, our builders map one-to-one to the JSON (pretty much). Yes, this takes some getting used to (and we have gotten some fire because we have our own method), but we believe that it is the better way to go about it, ultimately.

What @simon816 says is correct. The easier way to do this (in fact, easier than Spigot in my opinion) would be to use `Texts.of`:

```java
Texts.of(
  dashes, 
  TextColors.DARK_GRAY, header, 
  TextColors.RESET, "(", 
  TextColors.GRAY, page, 
  TextColors.WHITE, "/", 
  TextColors.GRAY, maxPages, 
  TextColors.WHITE, ") ", 
  TextColors.DARK_GRAY, dashes);
```

Earlier on I proposed a DSL that looks somewhat like the current commands DSL. If you wish, I can try to put it in another PR to elaborate it more:

```java
import static org.spongepowered.api.text.Texts;

join(
  dashes,
  darkGray(header),
  reset(of("(")),
  gray(page),
  white(of("(")),
  darkGray(dashes));
```

But this DSL pretty much just adds some more complexity for no real benefit.

Perhaps this issue belongs better on SpongeDocs to assert that the Text API needs to be documented in this way.
