### ISSUE TITLE
Subscribe annotation javadoc clarification

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeAPI#677]
As discussed in https://github.com/SpongePowered/Sponge/issues/223
subscribing to Events using the annotation is only possible 
when the method and the class it is in are public.
It was possible to register private methods/classes in Bukkit, 
so to prevent confusion it should be clarified somewhere
[in Subscribe](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/Subscribe.java#L37) and/or [on EventManager#register](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/service/event/EventManager.java#L46).

**Comment by Zidane** [comment]
Actually, the manager should be changed to allow this.

**Comment by progwml6** [comment]
I disagree We are going to slow it down doing so

**Comment by kashike** [comment]
https://github.com/SpongePowered/Sponge/issues/223

**Comment by Minecrell** [comment]
This issue is not about discussing if event handlers can be private, it's not going to be possible simply because that would require reflection or additional work to make it work together with our fast event system using classes generated by ASM.

This issue is basically simply about adding a note about this to the Javadocs.
