### ISSUE TITLE
Unloading worlds without saving

### ISSUE THREAD

**Issue by verbeto** [SpongePowered/SpongeAPI#701]
In bukkit, we had the ability to unload worlds without saving their changes to the world file (see [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Bukkit.html#unloadWorld(org.bukkit.World,%20boolean))). Is there anything inherently wrong with supporting this? It would be easy to add to the API, although I'm unsure how feasible this would be with the current world loading system.
````java
boolean unloadWorld(World world, boolean save);
````

**Comment by Mumfrey** [comment]
Adding boolean flags to API methods should generally be avoided because it makes methods harder to use (because consumers *always* have to look up the meaning of the flag because booleans don't have any intrinsic contextual meaning) and tends to proliferate (what happens when you want to add some other, on/off behaviour to the call).

I personally thing it would be better to add a method to `World` to inhibit serialisation such as `setSerialisation(Z)` or better yet have the same method take a `SerialisationBehaviour` which can be extended if need be:

```java
world.setSerialisation(SerialisationBehaviour.NONE);
server.unloadWorld(world); // respects serialisation behaviour defined on World
```

**Comment by gratimax** [comment]
I think that what @Mumfrey is suggesting is useful, but different from what this issue is actually about. This issue is specifically about world persistence _at the time of unloading_. This is related to but distinctly different from the issue of the world being persistence overall. 

It seems to me that world persistence belongs in [WorldBuilder](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/WorldBuilder.java) or [WorldCreationSettings](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/WorldCreationSettings.java) as a property of the world itself, rather than as a single property on the unload method. However, this achieves something different than what this issue is originally asking. I think that handling world persistence in this manner walks the fine line along implementation specifics, and while I see it as possibly useful it is adding a new behavior to worlds altogether. 

I would say that the simplest resolution to this issue in specific would be to add a `unloadWorldNoPersistence` method or something like that. World persistence on the scale of what @Mumfrey suggests is something that is conspicuously missing from the current API and I am not quite sure why.

**Comment by Mumfrey** [comment]
@gratimax my point about specifying a `SerialisationBehaviour` enum though would be that there could be options like `SerialisationBehaviour.NONE`, `SerialisationBehaviour.EXPLICIT`, `SerialisationBehaviour.ALWAYS` for example, where `EXPLICIT` means that no *implicit* saves (like on unload, or periodic world saves) would take place but serialisation could still be triggered manually, `NONE` would mean that chunks/data are never saved, even when triggered explicitly etc. I'm not sure I agree with the idea of a `unloadWorldNoPersistence` method because I can't see any use-cases for it which wouldn't be better handled by being explicit about serialisation intentions in the first place. We could do with @bloodmc or @Zidane weighing in on this and as you say, possible fleshing-out of world persistence API in general.

**Comment by bloodmc** [comment]
@verbeto Why do you need prevent saving only during unloads? Chunks are unloading constantly and saving to file. Disabling saving during unloads would only prevent saving for the currently loaded chunks in the world. It makes more sense to have a toggle to turn off chunk saving (ex. backups) than to only have an option for unloads. One example I can think of that would make use of this would be a pre-generated world that must never change (ex. HungerGames plugin). As for where to place the option, this definitely belongs in WorldProperties as @gratimax suggested. I would call it "saveChunks" with the default being set to true. As for @Mumfrey suggestion, we could definitely provide a user-friendly API for this that uses an Enum with the impl just modifying WorldProperties based on the value.

WorldServer.saveAllChunks would have to be modified and DimensionManager.unloadWorlds.

**Comment by verbeto** [comment]
@bloodmc I was probably thinking too much in terms of bukkit, but yes, I'm suggesting that there should be a way to put the world file in "read only" so to speak, so that the chunks are never written. Hunger games would be one example, I'd imagine it would be mostly for minigames where you want the world to reset when the game ends. 

Rethinking it through, I think Mumfrey's suggestion would be the best way of adding it to the API, especially as that way would ensure the world was saved correctly with a sudden shut down or similar.

**Comment by KieronWiltshire** [comment]
@gratimax I don't think setting it as a property of the world is a good idea, imagine I want to build a "Survival Games" map, once completed I save the world and then I'd like to be able to play on that map without the worry of messing anything up, so then my plugin could just unload the world without it saving after the map is completely destroyed, and then reload it so to speak.

I don't know, I like @Mumfrey concept.

**Comment by modwizcode** [comment]
This seems along the same vein as https://github.com/SpongePowered/SpongeAPI/pull/751, suggesting a merge to get related world management apis in one cohesive PR.

**Comment by gabizou** [comment]
@modwizcode Probably best to just close the issue when the PR is actually merged in. It's always possible to have a PR resolve several issues, but don't close the issues unless the issues are actually resolved.

**Comment by modwizcode** [comment]
@gabizou I didn't close any issues I don't think? I was suggesting that this be added to the changes desired in #751 so I could add it to the PR. Currently this seems like a related change and I wanted to know if the result of this discussion was implemented via #751.

Did I click close by mistake somehow?

**Comment by gabizou** [comment]
@modwizcode not at all, just I misinterpreted your earlier comment as suggesting to close this issue and add it to #751.

**Comment by modwizcode** [comment]
This got missed, I'll pickup the issue again. Just want to make sure no more world changes are coming that working on this would disrupt. @bloodmc any concerns? I'm planning on implementing the `saveChunks` method on `WorldProperties` along with a other method for auto save interval management.

**Comment by Zidane** [comment]
@modwizcode 

Don't touch this. There is a massive amount of world changes coming in 1.9.

**Comment by modwizcode** [comment]
Yeah I noticed. That's why I asked to be safe.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/669f84a77187d1a4932014155e10a945567d67ee
