### ISSUE TITLE
Add callback function for Text onClick

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeAPI#719]
This would abstract away some of the difficulty in performing custom actions on click. Rather than
- Create custom command or find syntax of existing command that performs the desired function
- Adding an onClick action to run the command with the appropriate arguments,

this would make an action as simple as:

```java
Texts.builder("Click me!").onClick(TextActions.runCallback(src -> src.sendMessage(t("Action performed")));
```

**Comment by gratimax** [comment]
This is a pretty cool idea. However, in order to support Java 8 we would need a simpler interface than CommandCallable that supports the lambda syntax. It would probably just have the `process` method of CommandCallable and it might belong as a supertype of CommandCallable (meaning that you can pass in any arbitrary CommandCallable in order to "run a callback", which I think would be pretty useful).

Also we should _definitely_ note in the javadocs that the `runCallback` text action is not, strictly speaking, an action that Mojang provides and simply a utility for running an arbitrary command without needing to give it a name.

**Comment by zml2008** [comment]
I'm not sure the callback would make sense as a CommandCallable. It doesn't really take any arguments, since it is run in response to a click (no opportunity for user input -> *does it make sense to have one for suggestCommand?*), so it would probably be best as a `Consumer<CommandSource>`

**Comment by ST-DDT** [comment]
Isnt this a potential memory leak?
I agree  on `Consumer<CommandSource>`.

**Comment by modwizcode** [comment]
Wouldn't the command still need to have a name?

**Comment by simon816** [comment]
@modwizcode It could be a sort of 'magic' command argument as part of the `/sponge` command

So when you attach a click handler, it registers a random UUID with the handler in a
`Map<UUID, Callable>`.
The run_command would be something like `/sponge clickHandle {theUuid}` which the `/sponge` command handler can extract the argument and run the associated handler

**Comment by modwizcode** [comment]
Hmm yeah that makes sense.

**Comment by KieronWiltshire** [comment]
I created something that I think maybe somewhat relevant here as I applied the same concept:
https://github.com/KieronWiltshire/EssentialServices/blob/master/src/com/kieronwiltshire/essential_services/core/api/services/RequestService.java

The idea was to generate a Request with a unique id, and then use a command such as [ /request accept uuid ] or [ /request deny uuid ].
