### ISSUE TITLE
TextStyle does not extend CatalogType

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#730]
[`TextStyle`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/format/TextStyle.java#L59) does not extend `CatalogType`

**Comment by modwizcode** [comment]
@SpongePowered/developers I just took a look, I don't know if this can be a `CatalogType` because it's a class and composite types exist. I'm not sure though.

**Comment by ST-DDT** [comment]
IMO CatalogType is just a helper to get our enum like classes by name. So it should use it although it cannot do the complex stuff. Or is there an alternative we can use to map Strings to TextStyles?

**Comment by simon816** [comment]
Before the registry was refactored (https://github.com/SpongePowered/SpongeAPI/commit/00bd9cd0ae24a157f73ac7794ee2e5b2961dcb18), there was a method [`Optional<TextStyle> getTextStyle(String name)`](https://github.com/SpongePowered/SpongeAPI/blob/3d2f9a80a813c238b6aa571172bec87007176e5f/src/main/java/org/spongepowered/api/GameRegistry.java#L734) which no longer exists because `getType` should now be used. Therefore `TextStyle` needs to extend `CatelogType`
@SpongePowered/developers can a trivial fix be pushed?

**Comment by simon816** [comment]
Looking at TextStyle again, I think `TextStyle.Base` would be the appropriate target for `@CatalogedBy` and `CatalogType`. Unless there should be support for composite style IDs e.g. "BOLD;ITALIC;UNDERLINE"
