### ISSUE TITLE
Question: Update client when a sign changes?

### ISSUE THREAD

**Issue by mcmacker4** [SpongePowered/SpongeAPI#752]
I am trying to create a plugin that uses signs that change their text. I am only able to see the changes applied to the sign if I disconnect and reconnect. Is there any way to tell the clients that the sign (or any other block) has changed?
I was told by Simon816 that the API doesn't do this itself in this post: https://forums.spongepowered.org/t/always-get-empty-optional-when-getting-block-data/8256/5

**Comment by simon816** [comment]
There should not be any additional actions needed in the API to update it on the clients.
I think it's the implementation (SpongeCommon) that is incomplete and it should send an update to clients. So this is more of an issue with SpongeCommon.

**Comment by mcmacker4** [comment]
So the only thing I can do right now is wait? I would do it and send a pull request myself but i don't know how the API works and it would take me longer to understand how it works than anyone else to have it done.

**Comment by RobertHerhold** [comment]
Really? This was just working with my plugin, [BLWarps](https://github.com/BlockLaunch/BLWarps). The plugin currently does not work for actually warping (due to scheduler changes), but you can follow the instructions on the README to create a warp sign. When you put the right info on the right lines, it will reformat the sign... I never needed to reconnect to see the changes

**Comment by simon816** [comment]
@RobertHerhold I took a quick look at your code and it looks like you set the data when the `SignChangeEvent` is fired (your [SignChangeEventHandler](https://github.com/BlockLaunch/BLWarps/blob/master/src/main/java/com/blocklaunch/blwarps/eventhandlers/SignChangeEventHandler.java#L34)).
This issue is when offering the data outside of the `SignChangeEvent`.

I'll write a quick test to see whether I can reproduce the issue.

**Comment by RobertHerhold** [comment]
Got it. Thanks for the clarification.

**Comment by simon816** [comment]
I can confirm this is indeed an error in the implementation. The following code was ran where `loc` was a valid sign placed in the world
```java
Optional<TileEntity> opTileEntity = loc.getTileEntity();
if (!opTileEntity.isPresent()) {
    System.out.println("Tile entity doesn't exist");
    return;
}
TileEntity signTile = opTileEntity.get();
Optional<SignData> optSignData = signTile.getOrCreate(SignData.class);
if (optSignData.isPresent()) {
    SignData sign = optSignData.get();
    sign.setLine(0, Texts.of("Some Text"));
    DataTransactionResult result = signTile.offer(sign);
    System.out.println(result);
} else {
    System.out.println("Data unable to be created");
}
```

When executed, the sign still had the old text. After reconnecting I could see the updated text.

@mcmacker4 could you make an issue on SpongeCommon so someone can address the issue at some point.

**Comment by mcmacker4** [comment]
Ok, I will. Can i use your code as a proof of the issue?

**Comment by simon816** [comment]
Sure. Also link to this issue for reference.
