### ISSUE TITLE
sendMessage request: Overload with string param

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeAPI#763]
Would it be possible/feasable for the sendMessage() method used in command sender, player..  to have a String parameter argument that it then just converts into text.

Having to wrap every simple, non colored, non formatted simple string with Texts.of() within the argument get tedious and seems overkill, when a simple String could be detected and converted in the method itself.  Then Text is still there for its robust, feature rich use, but not required .

Or is the concern that folks may take porting to an extreme and encode color characters in the string that would break a simple Texts.of() wrapping of it?

**Comment by Zidane** [comment]
We've went around the block with this internally before. The biggest issue against it is providing the overload fuels bad habits cause people will absolutely try and do color codes in the raw text. When it breaks, they'll blame us as it "Just worked in Bukkit" when in reality Minecraft's chat system is completely different than it was in versions before.

While I can definitely understand not wanting to wrap in Texts.of, from a support perspective the gain isn't worth it imo. As always, I'm open for debate.

**Comment by ST-DDT** [comment]
You are referring to the sendMessage for chat purpose, aren't you?

If it solely for chat, it should not have a `String` overwrite. Due to the following reasons
* Unexpected results
  * How to deal with color codes? Forward to `Texts.legacy...`?
  * How to deal with JSON String literals?
  * How to deal with a combination of both?
  * How to enforce same support across multiple implementations?
* Bukkit compatibility/expectations
  * `Would like to send commands and chat in one method`
  * probably some more

On the other hand
* Little coding overhead

IMO There are far to many issues in comparison to the benefits.
Although I can understand how annoying wrapping messages in `Text`s can be.

PS: Wasn't there a discussion on this topic before?

**Comment by boformer** [comment]
I don't see any problems with it. In so many cases you just want to send a string to the player, especially while the plugin is in development.

Regarding the similarity with Bukkit: If people are too lazy to read the documentation of the method, it is their own fault.

@ST-DDT the exact behavior of the method can be described in the specification. I would say that the method should just send the raw string to the client.

**Comment by ST-DDT** [comment]
> @ST-DDT the exact behavior of the method can be described in the specification. I would say that the method should just send the raw string to the client.

@boformer That assumes that there is still a possibility to send the raw string to the client.

**Comment by Zidane** [comment]
As I said above, the days of sending raw text to the client are done with and we have a simple to use Texts.of construct that can be used.
