### ISSUE TITLE
Update Contributing doc

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#777]
Any API changes now should have a related implementation PR produced, if the API PR affects implementation in any way. For this, I'd recommend actually creating a suggested template for the API and Implementation PR description to facilitate easier review and testing.

@SpongePowered/developers thoughts?

**Comment by ST-DDT** [comment]
I guess this is a valid request because you can grab all help needed from IRC and elsewhere.

Allthough there should be a notice that you can start  with just the API PR to avoid coding too much that would be rejected immediatly or having to reimplement the entire Imple because there have been some valid concerns on the API side.

**Comment by Deamon5550** [comment]
@ST-DDT The point is less that you have to have both from the get go to be considered and more so that for an API PR to be merged there must be a corresponding implementation PR also ready for merging.

**Comment by Zidane** [comment]
@gabizou 

This issue is approved. Make the changes when you have a moment.

**Comment by gabizou** [comment]
This is being handled in the SpongePowered/SpongeDocs#389.
