### ISSUE TITLE
interval() method not working for scheduler

### ISSUE THREAD

**Issue by Favorlock** [SpongePowered/SpongeAPI#813]
Here is the code I'm using: http://pastebin.com/re7kw3mB

The task runs once initially and repeats once, but after the first repetition the task no longer repeats. I have not cancelled the task anywhere in the plugin other than when re-initializing the plugin. There are no errors appearing in the console either. It would just appear that the scheduler is not scheduling more than one interval.

**Comment by Favorlock** [comment]
So after talking with some people on irc and testing out some suggestions it would appear that the issue is specifically tied to making a task async with the .async() method.

**Comment by simon816** [comment]
This is a bug in SpongeCommon, not SpongeAPI.
Nevertheless, I have tested and can confirm this bug is reproducible.
It's a race-condition in the AsyncScheduler between the time a task is scheduled to start vs the time of actually starting. It was an unnoticed consequence of the commit: https://github.com/SpongePowered/SpongeCommon/commit/4104d1bb28eff529dbd44d691b7b102bfa70cf1c which fixed an issue in the sync scheduler, but created this bug in the async scheduler.

I will push a fix to SpongeCommon shortly.
