### ISSUE TITLE
Missing Values/Manipulators

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#814]
Just as a general todo list of missing `Key`s, `Value`s and `DataManipulator`s for *data* that can be manipulated/represented from any of the existing `DataHolder`s. 

Current TODO List:

Data type | Value Type | Key
------------- | --------------- | ------

Just keep commenting and we'll see if it's Data we can represent.

**Comment by kashike** [comment]
You can `CAN_FLY`, what about `FLYING`?

**Comment by JBYoshi** [comment]
@kashike https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/key/Keys.java#L230

**Comment by ST-DDT** [comment]
* [ ] [`Keys`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/key/Keys.java#L275) - missing `ACHIEVEMENTS` key
````java
+ public static final Key<SetValue<Achievement>> ACHIEVEMENTS = null;
````

EDIT: I don't know whether this belongs here but I just put it here because its closely related.

* [ ] [`ImmutableAchievementData`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulator/immutable/entity/ImmutableAchievementData.java#L45) - typo
````java
- ImmutableSetValue<Achievement> achiements();
+ ImmutableSetValue<Achievement> achievements();
````
I can create a PR for this as well, but I consider this a too small/OCD change. [Compare/Merge](https://github.com/SpongePowered/SpongeAPI/compare/master...ST-DDT:Statistics)

Copied from: https://github.com/SpongePowered/SpongeAPI/issues/221#issuecomment-143351684

**Comment by gabizou** [comment]
All missing data has been added in 286f1ddbb2da9b2c6085a2984e07702c9ab
