### ISSUE TITLE
Question: DataBuilder.createFrom() vs DataHolder.getOrCreate()?

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeAPI#870]
They seem to do the same thing.

**Comment by gabizou** [comment]
Yes, they do. Just, occasionally, we can't rely on the DataHolder knowing the implementation of a particular `DataManipulator`, so, in it's stead, we delegate back to the `DataManipulatorBuilder`.

**Comment by JBYoshi** [comment]
@gabizou So `DataBuilder.createFrom()` should be called from the implementation only, not the API? If so, then that should be mentioned in the javadocs.

**Comment by gabizou** [comment]
`DataBuilder.createFrom` is called throughout various places, not just in the implementation. It's exposed in the API because it's necessary to be able to get a `DataManipulator` from any `DataHolder`, regardless whether it's a `DataHolder` originating from the implementation. It's something that I think I missed from implementation on checking if there's a `DataProcessor` that I'm not checking if there's a `DataManipulatorBuilder` present, but I can easily fix that in the morning along with a few other minute fixes.

**Comment by JBYoshi** [comment]
@gabizou I don't really get what you mean, unless that by
> It's exposed in the API because it's necessary to be able to get a `DataManipulator` from any `DataHolder`

you mean that it's necessary for a `DataHolder` that has no built-in knowledge of the `DataManipulator` to be able to get a `DataManipulator` from it (as in, if the `DataHolder` knows about and supports the manipulator, then it creates and returns it, otherwise it delegates to the `DataBuilder`). Is that what you mean?

**Comment by gabizou** [comment]
Correct.
