### ISSUE TITLE
Change to time scaling in TaskBuilder

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#872]
@simon816 

@Aikar brought up a good point about the inconsistency between what delay(long) means before and after async is set.

By default, everything should be in ticks unless you use the builder methods that take a TimeUnit (and we'll need to make a class that mimics Java's class and adds on TICK to that too). This should affect sync and non-sync.

**Comment by simon816** [comment]
You can't schedule an async task using ticks because it runs independently from the tick cycle.

**Comment by TBlueF** [comment]
But you could say a tick is just 20/sec?

**Comment by Zidane** [comment]
@simon816 

If you don't pulse the async task unless x amount of ticks pass, you could?

**Comment by aikar** [comment]
for async, timestampToRunAt = ticks * 50ms

Pretty simple..

And for Relative Time Sync Tasks, ticksToWait = (now + TimeInUnits) / 50ms

**Comment by simon816** [comment]
@Zidane That would mean making the async scheduler listen to ticks which is not how it works.


What I'll do is make the methods `delay(long)` and `interval(long)` take ticks and only ticks. It would be convenient for plugins to know the tick rate (since the API does not declare this detail), so a method in `SchedulerService` called `getPreferredTps()` will be added (which would be `20` in vanilla)
If the task is async, the resulting time will be `time / getPreferredTps()`

**Comment by aikar** [comment]
@simon816 
Or as I said, currently its based on timestamp for when it should run? Calculate the desired timestamp as value * preferredTickInterval (not tps, you would want 50ms, not the value 20, so 1s / preferredTPS)

While you could force plugins to calculate it themselves, having it as part of the API would be pretty clean.

Like I currently do in my Bukkit plugin TimeUnit.MINUTES.inTicks(5) to get 5 minutes worth of ticks, but .interval(5, TimeUnit.MINUTES); is a much cleaner API.

**Comment by JBYoshi** [comment]
How about having both ticks and `TimeUnit`s? `delay(int, TimeUnit)` and `delayTicks(int)`, along with corresponding `interval` methods.

**Comment by Kiskae** [comment]
One solution is to combine the overloads into a single method with a class that represents the selected time:
```java
abstract class Duration {
    static Duration ticks(int ticks);
    static Duration unit(int amount, TimeUnit unit);
}
```

Then you can use it like `<TaskBuilder>.interval(Duration.ticks(20))`

The implementation can then also be used to select the best method of timekeeping, for sync that would be exact ticks and closest future tick for timeunit values, while for async it would be exact timeunit and a perfect approximation of ticks (which assumes 20/second).

I think that basing all synchronous scheduling on internal ticks would be confusing, since a slowdown of the server changes what people presume to be an exact duration when using TimeUnit values.

**Comment by simon816** [comment]
This should hopefully cover the concerns here  https://github.com/SpongePowered/SpongeAPI/commit/9ae1a308a3e140074f57687fe245d2d3f785eb46
