### ISSUE TITLE
Integration Test infrastructure: @RunWith(MinecraftRunner.class)

### ISSUE THREAD

**Issue by vorburger** [SpongePowered/SpongeAPI#875]
Hello, just FYI I've done some work for fun to investigate integration test infrastructure, read http://blog2.vorburger.ch/2015/10/how-to-integration-test-minecraft.html. 

It's basically a custom JUnit [MinecraftRunner](https://github.com/vorburger/SwissKnightMinecraft/blob/2e016ebb7821dcf406f4a41971a9f6cb2e2b7296/SpongePowered/SpongeTests/src/main/java/ch/vorburger/minecraft/testsinfra/MinecraftRunner.java); see e.g. [this test as one usage example](https://github.com/vorburger/SwissKnightMinecraft/blob/2e016ebb7821dcf406f4a41971a9f6cb2e2b7296/SpongePowered/SpongeTests/src/test/java/ch/vorburger/minecraft/testsinfra/tests/CommandTestHelperIntegrationTest.java) - the main point here is that such @RunWith(MinecraftRunner.class) tests run within a full server.

I am creating this issue for discussion whether something like that could ever be of any interest within Sponge core.

**Comment by gabizou** [comment]
One thing that I was considering is doing something similar to this, however, it would require our [mixin](https://github.com/SpongePowered/SpongeCommon/tree/master/src/main/java/org/spongepowered/common/mixin/core)s to be applied at runtime of the unit tests, an example of this is with the current issues plaguing some of the [manipulator tests](https://github.com/SpongePowered/SpongeCommon/blob/master/src/test/java/org/spongepowered/common/data/manipulator/ManipulatorTest.java) due to the fact that some of the things require `Sponge` to be not only initialized but also set up the [`SpongeGameRegistry`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java).

**Comment by gabizou** [comment]
@vorburger Could you elaborate on whether it's possible to make a runner that does handle Mixins?

**Comment by Zidane** [comment]
Closing this for now:

We appreciate the idea (its pretty cool!) and will keep this amongst the others in-case we have a need for it in the future.
