### ISSUE TITLE
Register permission defaults through CommandCallable/CommandSpec

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#924]
Conversation: https://korobi.io/network/esper/channel/spongedev/logs/2015/11/19/#L613-644

You can currently set permission defaults using `permService.getDefaultData().setPermission(SubjectData.GLOBAL_CONTEXT, "my.perm", Tristate.TRUE);` but it's a bit obscure.
This is a request for a new method on `CommandCallable`: `registerDefaultPermissions(PermissionService)` that gets called in [`SimpleCommandService#register`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/service/command/SimpleCommandService.java#L118), as well as a new method, or two, on `CommandSpec` for people who wish to use it:
- `permission(String, Set<Context>, Tristate)`
- `permission(Set<Context>, Tristate)`
  This also ensures that, if this method is being used, permission defaults are only set when a command is registered.

**Comment by Deamon5550** [comment]
Could you change this to an actual description, no one wants to read through a log just to know what you're on about, especially when is buried in 800 lines of text.

**Comment by gabizou** [comment]
@zml2008 do you have the time to get this in before beta?

**Comment by ryantheleach** [comment]
I think that plugin defaults shouldn't be handled directly by plugins, and instead should be assigned to roles via Permission Descriptions.

@bloodmc suggested on the forums that it may even be worth having a plugin container reference.

Combining the two ideas, could allow for a Role that is plugin container aware, so roles could be split to say "griefprevention.staff" instead of just generally applying them to a staff role.

**Comment by dualspiral** [comment]
This won't happen in commands in API-7 or API-8 now, particularly as in API-8 we don't necessarily have control over the command being registered due to registrars, and checks don't necessarily need to be permission checks anyway.

Registering permission descriptions has more of a reward now anyway, as they are intended to be used as role templates. I'd rather not clutter up methods for adding permissions with permission description stuff - the two should remain separate.
