### ISSUE TITLE
SettingsService

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeAPI#934]
Sponge could use a "Settings Service", where all of the (non-permission) settings for a player are stored.

## Example 1

Essentials for Bukkit's **/sethome** permissions are very ugly:
``` /addperm Notch essentials.sethome.multiple.20 ```
Sponge can do better with a "SettingService":
``` /setting Notch someplugin.sethome.amount 150 ```

## Example 2

Currently plugins manage their prefixes in their own code.
*config/someplugin/permissions.conf*:
```
users {
  Notch {
    prefix: "[God]"
    permissions: ...
  }

  ...
}
```
It would be nice to have this:
``` /setting Notch sponge.chat.prefix = "[SettingsServiceYay]" ```

A settings service would *greatly* improve plugin interoperability.

**Comment by gratimax** [comment]
Sponge already supports this to a certain extent with [option subject data](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/service/permission/option/OptionSubjectData.java), essentially key-value option pairs like you are suggesting.

**Comment by CrystalMageX** [comment]
Could you give usage examples for the two cases above please?

**Comment by kashike** [comment]
It looks like `Player` is a `SubjectData`, and not `OptionSubjectData`.

**Comment by gratimax** [comment]
Yeah, player is only a Subject, not an OptionSubject. @zml2008 any thoughts?

**Comment by gratimax** [comment]
@CrystalMageX If you have an OptionSubject, you could use it as follows:
```java
OptionSubjectData data = subject.getSubjectData();
subject.getOption(SubjectData.GLOBAL_CONTEXT, "my.chat.prefix")
data.setOption(SubjectData.GLOBAL_CONTEXT, "my.chat.prefix", "hello")
```

**Comment by CrystalMageX** [comment]
@gratimax I am not familiar with `OptionSubject`, but it seems like it is restricted to the class `String`.

This restriction is a problem, becuase although simpler objects like `Vector3d`s can be serialized into a string, more complex objects such as entire **chests full of items** will make this impractical, if not impossible. (don't ask me why I would put my backpack plugin's data there, eventually it will be necessary, like in the next case)

It's nice to have *Settings* inside a *Service* so plugin developers could change them to their liking. Let's say I have a plugin named *"Payout"* that gives all players the kit of items defined in `io.github.crystalmagex.examples.payout.loot.amount`. Suppose there is another plugin on my server called *"RegionSettings"* which is like the actual plugin *WorldGuard*, that "flags" settings in regions instead of protecting them. Now I have regions for two cities "London," and "New York."

It would be convenient to use this `SettingsService` to configure my *"Payout"* plugin to give players, say, diamond blocks in New York, and stacks of gold ingots in London, according to **a custom variable** that cannot be hardcoded in SpongeAPI, once some crazy server owner decides to give out things, instead of in a certain city, give things out on a certain weekday, like Iron on Monday, and Redstone on Friday.

**Comment by ST-DDT** [comment]
@CrystalMageX IMO those plugin should either register a Service themselves or use their events or APIs to exchange those information. Because otherwise you have no type safety and are always check for a region a player is in an push it to the SettingsService and no other plugin cares at all. And in the end the settings service should even persist all those data causing constant IO.

No thank you.
Use your own specialized Service, listen to the other plugins events or just ask the plugin directly for that value only when you need it.

Sorry for maybe sounding a bit harsh.

PS: If your region plugin contributes to the Context calculation of the perm plugin you can just fetch the current active contexts from the subject and use them to do your stuff. [`Subject#getActiveContexts() : Set<Context>`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/service/permission/Subject.java#L183)

**Comment by gratimax** [comment]
@CrystalMageX I agree with you that there needs to be some way of configuring arbitrary key/value settings on permission subjects, since it is so useful. My thinking is something along these lines:

```java
SubjectOption<Text> myChatPrefix = SubjectOptions.of(Text.class, "my.chat.prefix");
subject.get(myChatPrefix); // Optional<Text>
subject.set(myChatPrefix, Texts.of(...));
```

Depending on how to resolve conflicts with specific subject keys, it's possible that APIs like Vault aren't even needed -- there would be some agreed-upon standard for options that plugins could use. Hopefully this also resolves @ST-DDT's type safety concerns.

Maybe @gabizou has some input here, this sort of use case might fit better for custom data? The only problem is that there's a difference between Subject and ValueContainer, and it bothers me that there's a big intersection  between the Data API and permissions APIs for this use case.

**Comment by ST-DDT** [comment]
@gratimax:
Why not just:
`subject.get(Text.class, "some.key")`

Signature:
`<T> Optional<T> get(Class<T> clazz, String key)`

**Comment by CrystalMageX** [comment]
@gratimax @ST-DDT It turns out that `subject.get(Class<T> clazz, String key)` is not necessarily required, but the workaround is quite ugly and hacky.

## The workaround is as follows:

1. Create a configuration, but set the source, and sink to some **memory buffer**.
2. Register some type loaders with *Configurate*.
3. Get a node, named "data", and set the Object *into that node*.
4. Get a node, named "type", and set it to the Object's class.
5. Save the configuration into the buffer.
6. Extract the characters of that buffer, and construct a *String* with them.
7. Put the *String* into an *OptionSubjectData*, and set it into something.

## Limitations

Even with the above workaround, we still need somewhere to put the *OptionSubjectData*, and the resulting code will be **very ugly**.

**Comment by gratimax** [comment]
@ST-DDT That's a good question. I'm fine with the API you suggested as well and considered it. I mainly wanted a special class because it would allow registration like so:

```java
registry.register(mySettingKey); 
// might return false or something if there's a conflict with an existing key
```

And also some constant classes for commonly used options:

```java
public class SpongeSubjectOptions {

  public static final SubjectOption<Text> PREFIX = 
    SubjectOption.of(Text.class, "sponge.prefix");
  public static final SubjectOption<Text> SUFFIX = 
    SubjectOption.of(Text.class, "sponge.suffix");

}
```

I'm not saying that PREFIX and SUFFIX should be defined as options, but I hope my point is clear. Because subject options are shared between plugins, it might be useful to hold on to an instance that represents the option. This is also more useful than just defining string constants because we expect options to be of a certain type.

@CrystalMageX I agree that the workaround is really ugly. I think that forcing plugins to implement the pattern you described again and again is sort of wasteful. In addition, there don't seem to be many useful alternatives to that pattern, so I don't think it would make the API any more opinionated.

My only concern is that this might already be solved with the data API if your plugin creates a custom manipulator, however that would force plugins to include that manipulator in the classpath. I can't really specify the line between the permissions and data APIs, so I don't really know where it should fall. For now, I'm leaning more toward reworking OptionSubject in the permission API. Here are some thoughts on the steps forward:

1. Make User an OptionSubject, or remove OptionSubject and OptionSubjectData and their methods to Subject and SubjectData
2. Add a SubjectOption api or simple string/type API.

**Comment by CrystalMageX** [comment]
If we ever make User an OptionSubject, should we link the permissions with it, making getting the value of `permission "someauthor.someplugin.admin"` a layer on top of `setting "permissions.someauthor.someplugin.admin = true"` ?

**Comment by Zidane** [comment]
API 5 will have OptionSubject and Subject as one so the initial thoughts is easily settable and acheivable.
