### ISSUE TITLE
Texts.of() Doesn't work with TextActions.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeAPI#936]
My code that doesn't work:
```java
Texts.of(FGHelper.getColorForHandler(handler), 
        TextActions.suggestCommand("/foxguard detail handler " + handler.getName()), 
        "\n" + handler.getShortTypeName() + " : " + handler.getName())
```
My code that does work:
```java
Texts.of(FGHelper.getColorForHandler(handler),
        "\n" + handler.getShortTypeName() + " : " + handler.getName()
).builder().onClick(TextActions.suggestCommand(
        "/foxguard detail handler " + handler.getName()
)).build()
```

Somehow... like magic...

It looks like It should work but it doesn't.

**Comment by JBYoshi** [comment]
What do you mean by “it doesn't work”?

**Comment by ST-DDT** [comment]
The TextAction does not get applied in the first case.
This poped up due to the latest fix that reduces the depth of single element Text objects returned by Texts.of(Object)

Simplfied Testcase:
````java
System.out.println(Texts.of(TextActions.suggestCommand("/cmd"), "Some text"));
System.out.println(Texts.of("Some text").builder().onClick(TextActions.suggestCommand("/cmd")).build());
````
Just execute it as a Test class with a main method in the API to confirm.

Results in:
````
Literal{Text{format=TextFormat{style=NoneTextStyle{}, color=NONE}, children=[], clickAction=Optional.empty, hoverAction=Optional.empty, shiftClickAction=Optional.empty}, content=Some text}
Literal{Text{format=TextFormat{style=NoneTextStyle{}, color=NONE}, children=[], clickAction=Optional[SuggestCommand{/cmd}], hoverAction=Optional.empty, shiftClickAction=Optional.empty}, content=Some text}
````

The following commit/changes will fix the issue:
[#808@79d428c5](https://github.com/ST-DDT/SpongeAPI/commit/79d428c5953bc99c814c7109b38d3e09903755b0)
Apply TextActions to the childbuilder instead of the parent builder. This will also fix the issue that only the last TextAction of a type will be apllied to the (entire) message.
