### ISSUE TITLE
Add a way to parse a double/float using GenericArguments

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeAPI#937]
Currently, the only Java base types that the command arguments parser will parse are `Boolean`, `String`, and `Integer`. It would be very useful for some commands where very precise numbers are needed, such as tweaking `/flyspeed` to the most comfortable rate.

**Comment by gratimax** [comment]
Seems reasonable. There doesn't seem to be too much effort in adding doubles and floats, since the implementation would be almost exactly the same. Although, maybe there's a reason why @zml2008 didn't put in double and float generic arguments?

If not, I would also like to see specifying a number of decimal points to round to:

```java
GenericArguments.double(3); // 3 decimal points precision
```

**Comment by gabizou** [comment]
Closing as we can discuss everything in #947.
