### ISSUE TITLE
Allow sending packets natively

### ISSUE THREAD

**Issue by JamesTheCoder** [SpongePowered/SpongeAPI#967]
Currently, sponge has no way to send a packet to a player, I consider this a good thing to have, as it can:

1. Allow different players to see different things (ie. the glowing effect from 1.9 could be visible to one player only)
2. Future-proof the API some more, stopping the API from having to abstract all the newly possible things. This would reduce the update time between Minecraft versions.
3. Be really cool.

The way I, personally, would want to see this implemented is similar to [ProtocolLib](http://dev.bukkit.org/bukkit-plugins/protocollib/) from Bukkit combined with [PacketWrapper](https://github.com/dmulloy2/PacketWrapper), in a hope to make it as easy as possible to use. It could also support raw packet data, for those who know the packet format, so they don't have to wait for the PacketWrapper equivalent to update.

I have spoken to people on #spongedev about this, and they raised some good points, but I wanted to bring it here so it could be discussed in a cleaner way.

**Comment by simon816** [comment]
There will not be a packet API. Pull Request #286 was rejected because we weren't going ahead with such API.

All per-player things you mention there will be possible with things like contextual data (https://github.com/SpongePowered/SpongeAPI/pull/945), per player world borders (https://github.com/SpongePowered/SpongeAPI/issues/282) and more.
A lot of things can already be sent to an individual player, see the [`Viewer`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/effect/Viewer.java) interface.

**Comment by Mumfrey** [comment]
The best way to summarise this is:

If you have a request along the lines of 

> There should be a packet API because you can do `<x>` with it, sending raw packets would allow `<x>` to be achieved.

Realise that as Simon said we are never going to add a packet API because the very phrase is kind of an oxymoron, by definition it goes against the idea of a stable API, by exposing the very guts of an implementation detail. Instead say:

> I want to achieve `<x>`, this should be in the API

So for example your point 

> 1.Allow different players to see different things (ie. the glowing effect from 1.9 could be visible to one player only)

is good, because it's a use-case which can be presented by the API in an abstract and version-independent way, and as Simon already points out is already possible. However the second point 

> 2. Future-proof the API some more, stopping the API from having to abstract all the newly possible things. This would reduce the update time between Minecraft versions.

is the very antithesis of such a case. Because it doesn't just erode version-independence, but actually *encodes* version-dependence in the very fabric of anything consuming said API, which is bad.

Generally the motivations for this request are well-meaning, but it just can't - from a practical standpoint - ever go anywhere. This has been interated in various fora, such as IRC, the sponge forum, and SoS Q&A, etc. for quite some time, and the arguments "against" simply steamroller over the arguments "for".

Hope that explains the situation sufficiently, feel free to submit issues for *features which would (in the underlying implementation) rely on a custom-packet-based approach* but closing this as it's not productive to discuss further.

**Comment by JamesTheCoder** [comment]
Thanks for that, I understand completely. I'll come up with some use cases and submit them as issues.
