### ISSUE TITLE
Local weather

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeAPI#976]
There is currently no easy way to get the weather that applies to a specific location, maybe something like a `getWeatherAt(Vector3d position)` in the WeatherUniverse (which is affected by the biome). And on top of this maybe provide a `SNOW` weather? I don't know how we could handle this because of the global weather system but it would be useful.

Regarding the `getWeatherAt` method can you also provide a `WeatherScope` which can give more information about a specific location.

**Comment by ST-DDT** [comment]
It would be cool if we could replace the entire weather layer of a world, so that we have full control over rain durations and locations or the ability to disable the weather cycle of a world completely. 

So that we could have moving patches of rain moving around. It does not matter that the client cannot actually see them unless he is actually in them. (Like in a real world)

**Comment by DDoS** [comment]
As far as I know all weather is a global effect and rendered on the client side depending on the biome. Weather doesn't have a location and the snow variation is just rain but in cold biomes.

This could be done by controlling weather packets sent to each client to make it appear as if it is local, but it would be limited as a player would still see the whole word as raining.

**Comment by Zidane** [comment]
@DDoS is right...weather is a global concept. Until this changes in Vanilla, we can't really do it in Sponge...not without overwriting much of Vanilla's logic (and fundamentally changing the game drastically).
