### ISSUE TITLE
Suggestions for Text API revision 3

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeAPI#987]
I'm looking for feedback on the current Text API and suggestions to improve it. I'm currently working on a major rework of the Text API before Beta (Text API revision 3), so if you'd like to have anything changed in the Text API there is now your chance!

If you have any suggestions, please comment the suggestions here in the next few days and I will consider them before merging the new changes. Thanks!

**Current changes:**
- Split Text into separate classes and move the builders into these classes:
  - `Text` -> `Text`, `TextBuilder` -> `Text.Builder`
  - `Text.Literal` -> `LiteralText`, `TextBuilder.Literal` -> `LiteralText.Builder`
- Move methods in `Texts` to the `Text` class, e.g. `Texts.of("Hi")` is `Text.of("Hi")` now
- Added locales class with a list of locales in Vanilla Minecraft
- Refactor `TextRepresentation` -> `TextSerializer`
- Implementation related: Remove `TextFactory`

**Comment by Minecrell** [comment]
Moved here from https://github.com/SpongePowered/SpongeAPI/issues/984:
> `PLUS_TEXT` isn't a plus, and `ELIPSES_TEXT` is just a disaster.

**Comment by kashike** [comment]
text builder methods:
- `onClick` -> `click`
- `onHover` -> `hover`
- `onShiftClick` -> `shiftClick`

**Comment by ST-DDT** [comment]
Just for reference the current changes can be viewed [here](https://github.com/SpongePowered/SpongeAPI/compare/feature/text3)

Another important change:
* `Text.Placeholder` and `Texts.format(X)` have been temporarily removed, so that things won't break after beta with my additions to the Text API #808.

Here are some features I would like to see:
* `of(Iterable<?>)` similar to `of(Object...)` even if it defaults to `of(it.toArray())`
  * to avoid [`Texts.of(list.toArray())`](https://github.com/SpongePowered/SpongeAPI/blob/fd46f4336d8988007982fbb1c836dfacc06fc9ee/src/main/java/org/spongepowered/api/command/args/CommandFlags.java#L204)
* "Shortifications" such as [`t("Available commands:\n").toBuilder()`](https://github.com/SpongePowered/SpongeAPI/blob/fd46f4336d8988007982fbb1c836dfacc06fc9ee/src/main/java/org/spongepowered/api/command/dispatcher/SimpleDispatcher.java#L370) should be removed from the API.
  * vs `Text.builder("Available commands:\n")`
* Partially merge content from #808.
  * Move `TextRepresentable` check to the top (to avoid the unnecessary builder creation)
    * See [`Texts.of(Object...)`](https://github.com/SpongePowered/SpongeAPI/pull/808/files#diff-b86a6b8d128bd6f6b99f8120e3954b22R215)
  * Add support for `joinOf(Text separator, Object...)` or replace the current `Texts.join(Text, Text...)` method with this one (as they basically do the same), same for `joinOf(Text separator, Iterable<?>)` and use them in `Texts.of(Object...)`
    * See [`Texts.of(Object....)`](https://github.com/SpongePowered/SpongeAPI/pull/808/files#diff-b86a6b8d128bd6f6b99f8120e3954b22R276)
    * See [`Texts.joinOf(Text, Object....)`](https://github.com/SpongePowered/SpongeAPI/pull/808/files#diff-b86a6b8d128bd6f6b99f8120e3954b22R318)
    * See [`Texts.joinOf(Text, Iterable<?>)`](https://github.com/SpongePowered/SpongeAPI/pull/808/files#diff-b86a6b8d128bd6f6b99f8120e3954b22R344)
  * Add support for `Translatables` in `Texts.of(Object...)`
    * See [`Texts.of(Object...)`](https://github.com/SpongePowered/SpongeAPI/pull/808/files#diff-b86a6b8d128bd6f6b99f8120e3954b22R270)
  * Add proper support for `Text`s and `TextRepresentable`s in `Texts.of(Object...)`
    * See [`Texts.of(Object...)`](https://github.com/SpongePowered/SpongeAPI/pull/808/files#diff-b86a6b8d128bd6f6b99f8120e3954b22L193)
    * See [`Texts.of(Object...)`](https://github.com/SpongePowered/SpongeAPI/pull/808/files#diff-b86a6b8d128bd6f6b99f8120e3954b22R245)
    * See [`TextFormat.merge(TextFormat)`](https://github.com/SpongePowered/SpongeAPI/pull/808/files#diff-47403c10eaf2083821baee122f4174c7R121)

Other change requests
* The builders should use the same `protected Objects.ToStringHelper toStringHelper()` strategy as the normal `Text` classes do
* Remove duplicate generic type in [`Optional.<ClickAction<?>>ofNullable(this.clickAction)`](https://github.com/SpongePowered/SpongeAPI/blob/fd46f4336d8988007982fbb1c836dfacc06fc9ee/src/main/java/org/spongepowered/api/text/Text.java#L390)

**Comment by simon816** [comment]
`Text.isEmpty()` that computes this value in the `Text` constructor.
Because `Texts.toPlain(text).isEmpty()` is quite expensive as it has to convert the whole structure to a string

**Comment by ST-DDT** [comment]
Here the associated PR: https://github.com/SpongePowered/SpongeAPI/pull/988

**Comment by Minecrell** [comment]
Closing this for now, if anyone has additional suggestions, post them in #988
